/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class AbstractSocket {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public AbstractSocket(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(AbstractSocket obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(AbstractSocket obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimCommonJNI.delete_AbstractSocket(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AbstractSocket clone() {
    long cPtr = opensimCommonJNI.AbstractSocket_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new AbstractSocket(cPtr, true);
  }

  public String getName() {
    return opensimCommonJNI.AbstractSocket_getName(swigCPtr, this);
  }

  public Stage getConnectAtStage() {
    return new Stage(opensimCommonJNI.AbstractSocket_getConnectAtStage(swigCPtr, this), true);
  }

  public boolean isListSocket() {
    return opensimCommonJNI.AbstractSocket_isListSocket(swigCPtr, this);
  }

  public long getNumConnectees() {
    return opensimCommonJNI.AbstractSocket_getNumConnectees(swigCPtr, this);
  }

  public boolean isConnected() {
    return opensimCommonJNI.AbstractSocket_isConnected(swigCPtr, this);
  }

  public String getConnecteeTypeName() {
    return opensimCommonJNI.AbstractSocket_getConnecteeTypeName(swigCPtr, this);
  }

  public OpenSimObject getConnecteeAsObject(int index) {
    return new OpenSimObject(opensimCommonJNI.AbstractSocket_getConnecteeAsObject__SWIG_0(swigCPtr, this, index), false);
  }

  public OpenSimObject getConnecteeAsObject() {
    return new OpenSimObject(opensimCommonJNI.AbstractSocket_getConnecteeAsObject__SWIG_1(swigCPtr, this), false);
  }

  public boolean canConnectTo(OpenSimObject arg0) {
    return opensimCommonJNI.AbstractSocket_canConnectTo(swigCPtr, this, OpenSimObject.getCPtr(arg0), arg0);
  }

  public void connect(OpenSimObject connectee) {
    opensimCommonJNI.AbstractSocket_connect(swigCPtr, this, OpenSimObject.getCPtr(connectee), connectee);
  }

  public void findAndConnect(SWIGTYPE_p_ComponentPath connectee) {
    opensimCommonJNI.AbstractSocket_findAndConnect__SWIG_0(swigCPtr, this, SWIGTYPE_p_ComponentPath.getCPtr(connectee));
  }

  public void findAndConnect(String connectee) {
    opensimCommonJNI.AbstractSocket_findAndConnect__SWIG_1(swigCPtr, this, connectee);
  }

  public void finalizeConnection(Component root) {
    opensimCommonJNI.AbstractSocket_finalizeConnection(swigCPtr, this, Component.getCPtr(root), root);
  }

  public void disconnect() {
    opensimCommonJNI.AbstractSocket_disconnect(swigCPtr, this);
  }

  public void setConnecteePath(String path, int index) {
    opensimCommonJNI.AbstractSocket_setConnecteePath__SWIG_0(swigCPtr, this, path, index);
  }

  public void setConnecteePath(String path) {
    opensimCommonJNI.AbstractSocket_setConnecteePath__SWIG_1(swigCPtr, this, path);
  }

  public String getConnecteePath(int index) {
    return opensimCommonJNI.AbstractSocket_getConnecteePath__SWIG_0(swigCPtr, this, index);
  }

  public String getConnecteePath() {
    return opensimCommonJNI.AbstractSocket_getConnecteePath__SWIG_1(swigCPtr, this);
  }

  public void appendConnecteePath(String path) {
    opensimCommonJNI.AbstractSocket_appendConnecteePath(swigCPtr, this, path);
  }

  public void assignConnecteePath(String path) {
    opensimCommonJNI.AbstractSocket_assignConnecteePath(swigCPtr, this, path);
  }

  public void clearConnecteePath() {
    opensimCommonJNI.AbstractSocket_clearConnecteePath(swigCPtr, this);
  }

  public boolean isConnecteePathEmpty() {
    return opensimCommonJNI.AbstractSocket_isConnecteePathEmpty(swigCPtr, this);
  }

  public Component getOwner() {
    return new Component(opensimCommonJNI.AbstractSocket_getOwner(swigCPtr, this), false);
  }

}
