/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class AbstractGeometryPath extends ModelComponent {
  private transient long swigCPtr;

  public AbstractGeometryPath(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.AbstractGeometryPath_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(AbstractGeometryPath obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(AbstractGeometryPath obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_AbstractGeometryPath(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static AbstractGeometryPath safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.AbstractGeometryPath_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new AbstractGeometryPath(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.AbstractGeometryPath_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.AbstractGeometryPath_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.AbstractGeometryPath_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new AbstractGeometryPath(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.AbstractGeometryPath_getConcreteClassName(swigCPtr, this);
  }

  public void set_has_output_length(boolean value) {
    opensimSimulationJNI.AbstractGeometryPath__has_output_length_set(swigCPtr, this, value);
  }

  public boolean get_has_output_length() {
    return opensimSimulationJNI.AbstractGeometryPath__has_output_length_get(swigCPtr, this);
  }

  public void set_has_output_lengthening_speed(boolean value) {
    opensimSimulationJNI.AbstractGeometryPath__has_output_lengthening_speed_set(swigCPtr, this, value);
  }

  public boolean get_has_output_lengthening_speed() {
    return opensimSimulationJNI.AbstractGeometryPath__has_output_lengthening_speed_get(swigCPtr, this);
  }

  public void copyProperty_Appearance(AbstractGeometryPath source) {
    opensimSimulationJNI.AbstractGeometryPath_copyProperty_Appearance(swigCPtr, this, AbstractGeometryPath.getCPtr(source), source);
  }

  public Appearance get_Appearance(int i) {
    return new Appearance(opensimSimulationJNI.AbstractGeometryPath_get_Appearance__SWIG_0(swigCPtr, this, i), false);
  }

  public Appearance upd_Appearance(int i) {
    return new Appearance(opensimSimulationJNI.AbstractGeometryPath_upd_Appearance__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_Appearance(int i, Appearance value) {
    opensimSimulationJNI.AbstractGeometryPath_set_Appearance__SWIG_0(swigCPtr, this, i, Appearance.getCPtr(value), value);
  }

  public int append_Appearance(Appearance value) {
    return opensimSimulationJNI.AbstractGeometryPath_append_Appearance(swigCPtr, this, Appearance.getCPtr(value), value);
  }

  public void constructProperty_Appearance(Appearance initValue) {
    opensimSimulationJNI.AbstractGeometryPath_constructProperty_Appearance(swigCPtr, this, Appearance.getCPtr(initValue), initValue);
  }

  public Appearance get_Appearance() {
    return new Appearance(opensimSimulationJNI.AbstractGeometryPath_get_Appearance__SWIG_1(swigCPtr, this), false);
  }

  public Appearance upd_Appearance() {
    return new Appearance(opensimSimulationJNI.AbstractGeometryPath_upd_Appearance__SWIG_1(swigCPtr, this), false);
  }

  public void set_Appearance(Appearance value) {
    opensimSimulationJNI.AbstractGeometryPath_set_Appearance__SWIG_1(swigCPtr, this, Appearance.getCPtr(value), value);
  }

  public double getLength(State s) {
    return opensimSimulationJNI.AbstractGeometryPath_getLength(swigCPtr, this, State.getCPtr(s), s);
  }

  public double getLengtheningSpeed(State s) {
    return opensimSimulationJNI.AbstractGeometryPath_getLengtheningSpeed(swigCPtr, this, State.getCPtr(s), s);
  }

  public void produceForces(State state, double tension, SWIGTYPE_p_OpenSim__ForceConsumer forceConsumer) {
    opensimSimulationJNI.AbstractGeometryPath_produceForces(swigCPtr, this, State.getCPtr(state), state, tension, SWIGTYPE_p_OpenSim__ForceConsumer.getCPtr(forceConsumer));
  }

  public void addInEquivalentForces(State state, double tension, VectorOfSpatialVec bodyForces, Vector mobilityForces) {
    opensimSimulationJNI.AbstractGeometryPath_addInEquivalentForces(swigCPtr, this, State.getCPtr(state), state, tension, VectorOfSpatialVec.getCPtr(bodyForces), bodyForces, Vector.getCPtr(mobilityForces), mobilityForces);
  }

  public double computeMomentArm(State s, Coordinate aCoord) {
    return opensimSimulationJNI.AbstractGeometryPath_computeMomentArm(swigCPtr, this, State.getCPtr(s), s, Coordinate.getCPtr(aCoord), aCoord);
  }

  public boolean isVisualPath() {
    return opensimSimulationJNI.AbstractGeometryPath_isVisualPath(swigCPtr, this);
  }

  public Vec3 getDefaultColor() {
    return new Vec3(opensimSimulationJNI.AbstractGeometryPath_getDefaultColor(swigCPtr, this), false);
  }

  public void setDefaultColor(Vec3 color) {
    opensimSimulationJNI.AbstractGeometryPath_setDefaultColor(swigCPtr, this, Vec3.getCPtr(color), color);
  }

  public Vec3 getColor(State s) {
    return new Vec3(opensimSimulationJNI.AbstractGeometryPath_getColor(swigCPtr, this, State.getCPtr(s), s), true);
  }

  public void setColor(State s, Vec3 color) {
    opensimSimulationJNI.AbstractGeometryPath_setColor(swigCPtr, this, State.getCPtr(s), s, Vec3.getCPtr(color), color);
  }

  public double getPreScaleLength(State s) {
    return opensimSimulationJNI.AbstractGeometryPath_getPreScaleLength(swigCPtr, this, State.getCPtr(s), s);
  }

  public void setPreScaleLength(State s, double preScaleLength) {
    opensimSimulationJNI.AbstractGeometryPath_setPreScaleLength(swigCPtr, this, State.getCPtr(s), s, preScaleLength);
  }

}
