/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class Blankevoort1991Ligament extends ForceProducer {
  private transient long swigCPtr;

  public Blankevoort1991Ligament(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.Blankevoort1991Ligament_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Blankevoort1991Ligament obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(Blankevoort1991Ligament obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_Blankevoort1991Ligament(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static Blankevoort1991Ligament safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.Blankevoort1991Ligament_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new Blankevoort1991Ligament(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.Blankevoort1991Ligament_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.Blankevoort1991Ligament_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.Blankevoort1991Ligament_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Blankevoort1991Ligament(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.Blankevoort1991Ligament_getConcreteClassName(swigCPtr, this);
  }

  public void copyProperty_path(Blankevoort1991Ligament source) {
    opensimSimulationJNI.Blankevoort1991Ligament_copyProperty_path(swigCPtr, this, Blankevoort1991Ligament.getCPtr(source), source);
  }

  public AbstractGeometryPath get_path(int i) {
    return new AbstractGeometryPath(opensimSimulationJNI.Blankevoort1991Ligament_get_path__SWIG_0(swigCPtr, this, i), false);
  }

  public AbstractGeometryPath upd_path(int i) {
    return new AbstractGeometryPath(opensimSimulationJNI.Blankevoort1991Ligament_upd_path__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_path(int i, AbstractGeometryPath value) {
    opensimSimulationJNI.Blankevoort1991Ligament_set_path__SWIG_0(swigCPtr, this, i, AbstractGeometryPath.getCPtr(value), value);
  }

  public int append_path(AbstractGeometryPath value) {
    return opensimSimulationJNI.Blankevoort1991Ligament_append_path(swigCPtr, this, AbstractGeometryPath.getCPtr(value), value);
  }

  public void constructProperty_path(AbstractGeometryPath initValue) {
    opensimSimulationJNI.Blankevoort1991Ligament_constructProperty_path(swigCPtr, this, AbstractGeometryPath.getCPtr(initValue), initValue);
  }

  public AbstractGeometryPath get_path() {
    return new AbstractGeometryPath(opensimSimulationJNI.Blankevoort1991Ligament_get_path__SWIG_1(swigCPtr, this), false);
  }

  public AbstractGeometryPath upd_path() {
    return new AbstractGeometryPath(opensimSimulationJNI.Blankevoort1991Ligament_upd_path__SWIG_1(swigCPtr, this), false);
  }

  public void set_path(AbstractGeometryPath value) {
    opensimSimulationJNI.Blankevoort1991Ligament_set_path__SWIG_1(swigCPtr, this, AbstractGeometryPath.getCPtr(value), value);
  }

  public void copyProperty_linear_stiffness(Blankevoort1991Ligament source) {
    opensimSimulationJNI.Blankevoort1991Ligament_copyProperty_linear_stiffness(swigCPtr, this, Blankevoort1991Ligament.getCPtr(source), source);
  }

  public double get_linear_stiffness(int i) {
    return opensimSimulationJNI.Blankevoort1991Ligament_get_linear_stiffness__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_linear_stiffness(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.Blankevoort1991Ligament_upd_linear_stiffness__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_linear_stiffness(int i, double value) {
    opensimSimulationJNI.Blankevoort1991Ligament_set_linear_stiffness__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_linear_stiffness(double value) {
    return opensimSimulationJNI.Blankevoort1991Ligament_append_linear_stiffness(swigCPtr, this, value);
  }

  public void constructProperty_linear_stiffness(double initValue) {
    opensimSimulationJNI.Blankevoort1991Ligament_constructProperty_linear_stiffness(swigCPtr, this, initValue);
  }

  public double get_linear_stiffness() {
    return opensimSimulationJNI.Blankevoort1991Ligament_get_linear_stiffness__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_linear_stiffness() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.Blankevoort1991Ligament_upd_linear_stiffness__SWIG_1(swigCPtr, this), false);
  }

  public void set_linear_stiffness(double value) {
    opensimSimulationJNI.Blankevoort1991Ligament_set_linear_stiffness__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_transition_strain(Blankevoort1991Ligament source) {
    opensimSimulationJNI.Blankevoort1991Ligament_copyProperty_transition_strain(swigCPtr, this, Blankevoort1991Ligament.getCPtr(source), source);
  }

  public double get_transition_strain(int i) {
    return opensimSimulationJNI.Blankevoort1991Ligament_get_transition_strain__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_transition_strain(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.Blankevoort1991Ligament_upd_transition_strain__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_transition_strain(int i, double value) {
    opensimSimulationJNI.Blankevoort1991Ligament_set_transition_strain__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_transition_strain(double value) {
    return opensimSimulationJNI.Blankevoort1991Ligament_append_transition_strain(swigCPtr, this, value);
  }

  public void constructProperty_transition_strain(double initValue) {
    opensimSimulationJNI.Blankevoort1991Ligament_constructProperty_transition_strain(swigCPtr, this, initValue);
  }

  public double get_transition_strain() {
    return opensimSimulationJNI.Blankevoort1991Ligament_get_transition_strain__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_transition_strain() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.Blankevoort1991Ligament_upd_transition_strain__SWIG_1(swigCPtr, this), false);
  }

  public void set_transition_strain(double value) {
    opensimSimulationJNI.Blankevoort1991Ligament_set_transition_strain__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_damping_coefficient(Blankevoort1991Ligament source) {
    opensimSimulationJNI.Blankevoort1991Ligament_copyProperty_damping_coefficient(swigCPtr, this, Blankevoort1991Ligament.getCPtr(source), source);
  }

  public double get_damping_coefficient(int i) {
    return opensimSimulationJNI.Blankevoort1991Ligament_get_damping_coefficient__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_damping_coefficient(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.Blankevoort1991Ligament_upd_damping_coefficient__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_damping_coefficient(int i, double value) {
    opensimSimulationJNI.Blankevoort1991Ligament_set_damping_coefficient__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_damping_coefficient(double value) {
    return opensimSimulationJNI.Blankevoort1991Ligament_append_damping_coefficient(swigCPtr, this, value);
  }

  public void constructProperty_damping_coefficient(double initValue) {
    opensimSimulationJNI.Blankevoort1991Ligament_constructProperty_damping_coefficient(swigCPtr, this, initValue);
  }

  public double get_damping_coefficient() {
    return opensimSimulationJNI.Blankevoort1991Ligament_get_damping_coefficient__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_damping_coefficient() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.Blankevoort1991Ligament_upd_damping_coefficient__SWIG_1(swigCPtr, this), false);
  }

  public void set_damping_coefficient(double value) {
    opensimSimulationJNI.Blankevoort1991Ligament_set_damping_coefficient__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_slack_length(Blankevoort1991Ligament source) {
    opensimSimulationJNI.Blankevoort1991Ligament_copyProperty_slack_length(swigCPtr, this, Blankevoort1991Ligament.getCPtr(source), source);
  }

  public double get_slack_length(int i) {
    return opensimSimulationJNI.Blankevoort1991Ligament_get_slack_length__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_slack_length(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.Blankevoort1991Ligament_upd_slack_length__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_slack_length(int i, double value) {
    opensimSimulationJNI.Blankevoort1991Ligament_set_slack_length__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_slack_length(double value) {
    return opensimSimulationJNI.Blankevoort1991Ligament_append_slack_length(swigCPtr, this, value);
  }

  public void constructProperty_slack_length(double initValue) {
    opensimSimulationJNI.Blankevoort1991Ligament_constructProperty_slack_length(swigCPtr, this, initValue);
  }

  public double get_slack_length() {
    return opensimSimulationJNI.Blankevoort1991Ligament_get_slack_length__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_slack_length() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.Blankevoort1991Ligament_upd_slack_length__SWIG_1(swigCPtr, this), false);
  }

  public void set_slack_length(double value) {
    opensimSimulationJNI.Blankevoort1991Ligament_set_slack_length__SWIG_1(swigCPtr, this, value);
  }

  public void set_has_output_spring_force(boolean value) {
    opensimSimulationJNI.Blankevoort1991Ligament__has_output_spring_force_set(swigCPtr, this, value);
  }

  public boolean get_has_output_spring_force() {
    return opensimSimulationJNI.Blankevoort1991Ligament__has_output_spring_force_get(swigCPtr, this);
  }

  public void set_has_output_damping_force(boolean value) {
    opensimSimulationJNI.Blankevoort1991Ligament__has_output_damping_force_set(swigCPtr, this, value);
  }

  public boolean get_has_output_damping_force() {
    return opensimSimulationJNI.Blankevoort1991Ligament__has_output_damping_force_get(swigCPtr, this);
  }

  public void set_has_output_total_force(boolean value) {
    opensimSimulationJNI.Blankevoort1991Ligament__has_output_total_force_set(swigCPtr, this, value);
  }

  public boolean get_has_output_total_force() {
    return opensimSimulationJNI.Blankevoort1991Ligament__has_output_total_force_get(swigCPtr, this);
  }

  public void set_has_output_strain(boolean value) {
    opensimSimulationJNI.Blankevoort1991Ligament__has_output_strain_set(swigCPtr, this, value);
  }

  public boolean get_has_output_strain() {
    return opensimSimulationJNI.Blankevoort1991Ligament__has_output_strain_get(swigCPtr, this);
  }

  public void set_has_output_strain_rate(boolean value) {
    opensimSimulationJNI.Blankevoort1991Ligament__has_output_strain_rate_set(swigCPtr, this, value);
  }

  public boolean get_has_output_strain_rate() {
    return opensimSimulationJNI.Blankevoort1991Ligament__has_output_strain_rate_get(swigCPtr, this);
  }

  public void set_has_output_length(boolean value) {
    opensimSimulationJNI.Blankevoort1991Ligament__has_output_length_set(swigCPtr, this, value);
  }

  public boolean get_has_output_length() {
    return opensimSimulationJNI.Blankevoort1991Ligament__has_output_length_get(swigCPtr, this);
  }

  public void set_has_output_lengthening_speed(boolean value) {
    opensimSimulationJNI.Blankevoort1991Ligament__has_output_lengthening_speed_set(swigCPtr, this, value);
  }

  public boolean get_has_output_lengthening_speed() {
    return opensimSimulationJNI.Blankevoort1991Ligament__has_output_lengthening_speed_get(swigCPtr, this);
  }

  public Blankevoort1991Ligament() {
    this(opensimSimulationJNI.new_Blankevoort1991Ligament__SWIG_0(), true);
  }

  public Blankevoort1991Ligament(String name, PhysicalFrame frame1, Vec3 point1, PhysicalFrame frame2, Vec3 point2) {
    this(opensimSimulationJNI.new_Blankevoort1991Ligament__SWIG_1(name, PhysicalFrame.getCPtr(frame1), frame1, Vec3.getCPtr(point1), point1, PhysicalFrame.getCPtr(frame2), frame2, Vec3.getCPtr(point2), point2), true);
  }

  public Blankevoort1991Ligament(String name, PhysicalFrame frame1, Vec3 point1, PhysicalFrame frame2, Vec3 point2, double linear_stiffness, double slack_length) {
    this(opensimSimulationJNI.new_Blankevoort1991Ligament__SWIG_2(name, PhysicalFrame.getCPtr(frame1), frame1, Vec3.getCPtr(point1), point1, PhysicalFrame.getCPtr(frame2), frame2, Vec3.getCPtr(point2), point2, linear_stiffness, slack_length), true);
  }

  public Blankevoort1991Ligament(String name, double linear_stiffness, double slack_length) {
    this(opensimSimulationJNI.new_Blankevoort1991Ligament__SWIG_3(name, linear_stiffness, slack_length), true);
  }

  public AbstractGeometryPath updPath() {
    return new AbstractGeometryPath(opensimSimulationJNI.Blankevoort1991Ligament_updPath(swigCPtr, this), false);
  }

  public AbstractGeometryPath getPath() {
    return new AbstractGeometryPath(opensimSimulationJNI.Blankevoort1991Ligament_getPath(swigCPtr, this), false);
  }

  public GeometryPath updGeometryPath() {
    return new GeometryPath(opensimSimulationJNI.Blankevoort1991Ligament_updGeometryPath(swigCPtr, this), false);
  }

  public GeometryPath getGeometryPath() {
    return new GeometryPath(opensimSimulationJNI.Blankevoort1991Ligament_getGeometryPath(swigCPtr, this), false);
  }

  public boolean hasVisualPath() {
    return opensimSimulationJNI.Blankevoort1991Ligament_hasVisualPath(swigCPtr, this);
  }

  public void setSlackLengthFromReferenceStrain(double strain, State reference_state) {
    opensimSimulationJNI.Blankevoort1991Ligament_setSlackLengthFromReferenceStrain(swigCPtr, this, strain, State.getCPtr(reference_state), reference_state);
  }

  public void setSlackLengthFromReferenceForce(double force, State reference_state) {
    opensimSimulationJNI.Blankevoort1991Ligament_setSlackLengthFromReferenceForce(swigCPtr, this, force, State.getCPtr(reference_state), reference_state);
  }

  public void setLinearStiffnessForcePerLength(double linear_stiffness) {
    opensimSimulationJNI.Blankevoort1991Ligament_setLinearStiffnessForcePerLength(swigCPtr, this, linear_stiffness);
  }

  public void setDampingCoefficientForceTimePerLength(double damping_coefficient) {
    opensimSimulationJNI.Blankevoort1991Ligament_setDampingCoefficientForceTimePerLength(swigCPtr, this, damping_coefficient);
  }

  public double getStrain(State state) {
    return opensimSimulationJNI.Blankevoort1991Ligament_getStrain(swigCPtr, this, State.getCPtr(state), state);
  }

  public double getStrainRate(State state) {
    return opensimSimulationJNI.Blankevoort1991Ligament_getStrainRate(swigCPtr, this, State.getCPtr(state), state);
  }

  public double getLength(State state) {
    return opensimSimulationJNI.Blankevoort1991Ligament_getLength(swigCPtr, this, State.getCPtr(state), state);
  }

  public double getLengtheningSpeed(State state) {
    return opensimSimulationJNI.Blankevoort1991Ligament_getLengtheningSpeed(swigCPtr, this, State.getCPtr(state), state);
  }

  public double getSpringForce(State state) {
    return opensimSimulationJNI.Blankevoort1991Ligament_getSpringForce(swigCPtr, this, State.getCPtr(state), state);
  }

  public double getDampingForce(State state) {
    return opensimSimulationJNI.Blankevoort1991Ligament_getDampingForce(swigCPtr, this, State.getCPtr(state), state);
  }

  public double getTotalForce(State state) {
    return opensimSimulationJNI.Blankevoort1991Ligament_getTotalForce(swigCPtr, this, State.getCPtr(state), state);
  }

  public double getLinearStiffnessForcePerLength() {
    return opensimSimulationJNI.Blankevoort1991Ligament_getLinearStiffnessForcePerLength(swigCPtr, this);
  }

  public double getTransitionLength() {
    return opensimSimulationJNI.Blankevoort1991Ligament_getTransitionLength(swigCPtr, this);
  }

  public double getDampingCoefficientForceTimePerLength() {
    return opensimSimulationJNI.Blankevoort1991Ligament_getDampingCoefficientForceTimePerLength(swigCPtr, this);
  }

  public double computeMomentArm(State s, Coordinate aCoord) {
    return opensimSimulationJNI.Blankevoort1991Ligament_computeMomentArm(swigCPtr, this, State.getCPtr(s), s, Coordinate.getCPtr(aCoord), aCoord);
  }

  public double computePotentialEnergy(State state) {
    return opensimSimulationJNI.Blankevoort1991Ligament_computePotentialEnergy(swigCPtr, this, State.getCPtr(state), state);
  }

  public void extendPostScale(State s, ScaleSet scaleSet) {
    opensimSimulationJNI.Blankevoort1991Ligament_extendPostScale(swigCPtr, this, State.getCPtr(s), s, ScaleSet.getCPtr(scaleSet), scaleSet);
  }

  public ArrayStr getRecordLabels() {
    return new ArrayStr(opensimSimulationJNI.Blankevoort1991Ligament_getRecordLabels(swigCPtr, this), true);
  }

  public ArrayDouble getRecordValues(State state) {
    return new ArrayDouble(opensimSimulationJNI.Blankevoort1991Ligament_getRecordValues(swigCPtr, this, State.getCPtr(state), state), true);
  }

}
