/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class BufferedOrientationsReference extends OrientationsReference {
  private transient long swigCPtr;

  public BufferedOrientationsReference(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.BufferedOrientationsReference_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(BufferedOrientationsReference obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(BufferedOrientationsReference obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_BufferedOrientationsReference(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static BufferedOrientationsReference safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.BufferedOrientationsReference_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new BufferedOrientationsReference(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.BufferedOrientationsReference_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.BufferedOrientationsReference_getClassName();
  }

  public OpenSimObject unused_clone() {
    long cPtr = opensimSimulationJNI.BufferedOrientationsReference_unused_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new BufferedOrientationsReference(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.BufferedOrientationsReference_getConcreteClassName(swigCPtr, this);
  }

  public BufferedOrientationsReference() {
    this(opensimSimulationJNI.new_BufferedOrientationsReference__SWIG_0(), true);
  }

  public BufferedOrientationsReference(BufferedOrientationsReference arg0) {
    this(opensimSimulationJNI.new_BufferedOrientationsReference__SWIG_1(BufferedOrientationsReference.getCPtr(arg0), arg0), true);
  }

  public BufferedOrientationsReference(String orientationFileName, Units modelUnits) {
    this(opensimSimulationJNI.new_BufferedOrientationsReference__SWIG_3(orientationFileName, Units.getCPtr(modelUnits), modelUnits), true);
  }

  public BufferedOrientationsReference(String orientationFileName) {
    this(opensimSimulationJNI.new_BufferedOrientationsReference__SWIG_4(orientationFileName), true);
  }

  public BufferedOrientationsReference(TimeSeriesTableRotation orientationData, SetOientationWeights orientationWeightSet) {
    this(opensimSimulationJNI.new_BufferedOrientationsReference__SWIG_5(TimeSeriesTableRotation.getCPtr(orientationData), orientationData, SetOientationWeights.getCPtr(orientationWeightSet), orientationWeightSet), true);
  }

  public BufferedOrientationsReference(TimeSeriesTableRotation orientationData) {
    this(opensimSimulationJNI.new_BufferedOrientationsReference__SWIG_6(TimeSeriesTableRotation.getCPtr(orientationData), orientationData), true);
  }

  public Vec2 getValidTimeRange() {
    return new Vec2(opensimSimulationJNI.BufferedOrientationsReference_getValidTimeRange(swigCPtr, this), true);
  }

  public void getValuesAtTime(double time, SimTKArrayRotation values) {
    opensimSimulationJNI.BufferedOrientationsReference_getValuesAtTime(swigCPtr, this, time, SimTKArrayRotation.getCPtr(values), values);
  }

  public void putValues(double time, RowVectorRotation dataRow) {
    opensimSimulationJNI.BufferedOrientationsReference_putValues(swigCPtr, this, time, RowVectorRotation.getCPtr(dataRow), dataRow);
  }

  public double getNextValuesAndTime(SimTKArrayRotation values) {
    return opensimSimulationJNI.BufferedOrientationsReference_getNextValuesAndTime(swigCPtr, this, SimTKArrayRotation.getCPtr(values), values);
  }

  public boolean hasNext() {
    return opensimSimulationJNI.BufferedOrientationsReference_hasNext(swigCPtr, this);
  }

  public void setFinished(boolean finished) {
    opensimSimulationJNI.BufferedOrientationsReference_setFinished(swigCPtr, this, finished);
  }

}
