/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class ComponentPath {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ComponentPath(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ComponentPath obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ComponentPath obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimCommonJNI.delete_ComponentPath(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static char separator() {
    return opensimCommonJNI.ComponentPath_separator();
  }

  public static ComponentPath root() {
    return new ComponentPath(opensimCommonJNI.ComponentPath_root(), true);
  }

  public ComponentPath() {
    this(opensimCommonJNI.new_ComponentPath__SWIG_0(), true);
  }

  public ComponentPath(String arg0) {
    this(opensimCommonJNI.new_ComponentPath__SWIG_1(arg0), true);
  }

  public ComponentPath(StdVectorString pathVec, boolean isAbsolute) {
    this(opensimCommonJNI.new_ComponentPath__SWIG_2(StdVectorString.getCPtr(pathVec), pathVec, isAbsolute), true);
  }

  public void clear() {
    opensimCommonJNI.ComponentPath_clear(swigCPtr, this);
  }

  public char getSeparator() {
    return opensimCommonJNI.ComponentPath_getSeparator(swigCPtr, this);
  }

  public String getInvalidChars() {
    return opensimCommonJNI.ComponentPath_getInvalidChars(swigCPtr, this);
  }

  public ComponentPath formAbsolutePath(ComponentPath otherPath) {
    return new ComponentPath(opensimCommonJNI.ComponentPath_formAbsolutePath(swigCPtr, this, ComponentPath.getCPtr(otherPath), otherPath), true);
  }

  public ComponentPath formRelativePath(ComponentPath otherPath) {
    return new ComponentPath(opensimCommonJNI.ComponentPath_formRelativePath(swigCPtr, this, ComponentPath.getCPtr(otherPath), otherPath), true);
  }

  public ComponentPath getParentPath() {
    return new ComponentPath(opensimCommonJNI.ComponentPath_getParentPath(swigCPtr, this), true);
  }

  public String getParentPathString() {
    return opensimCommonJNI.ComponentPath_getParentPathString(swigCPtr, this);
  }

  public String getSubcomponentNameAtLevel(long index) {
    return opensimCommonJNI.ComponentPath_getSubcomponentNameAtLevel(swigCPtr, this, index);
  }

  public String getComponentName() {
    return opensimCommonJNI.ComponentPath_getComponentName(swigCPtr, this);
  }

  public String toString() {
    return opensimCommonJNI.ComponentPath_toString(swigCPtr, this);
  }

  public boolean empty() {
    return opensimCommonJNI.ComponentPath_empty(swigCPtr, this);
  }

  public boolean isAbsolute() {
    return opensimCommonJNI.ComponentPath_isAbsolute(swigCPtr, this);
  }

  public long getNumPathLevels() {
    return opensimCommonJNI.ComponentPath_getNumPathLevels(swigCPtr, this);
  }

  public void pushBack(String pathElement) {
    opensimCommonJNI.ComponentPath_pushBack(swigCPtr, this, pathElement);
  }

  public boolean isLegalPathElement(String pathElement) {
    return opensimCommonJNI.ComponentPath_isLegalPathElement(swigCPtr, this, pathElement);
  }

  public void trimDotAndDotDotElements() {
    opensimCommonJNI.ComponentPath_trimDotAndDotDotElements(swigCPtr, this);
  }

}
