/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class ContactCylinder extends ContactGeometry {
  private transient long swigCPtr;

  public ContactCylinder(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.ContactCylinder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ContactCylinder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ContactCylinder obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_ContactCylinder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static ContactCylinder safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.ContactCylinder_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new ContactCylinder(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.ContactCylinder_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.ContactCylinder_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.ContactCylinder_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ContactCylinder(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.ContactCylinder_getConcreteClassName(swigCPtr, this);
  }

  public ContactCylinder() {
    this(opensimSimulationJNI.new_ContactCylinder__SWIG_0(), true);
  }

  public ContactCylinder(double radius, Vec3 location, Vec3 orientation, PhysicalFrame frame) {
    this(opensimSimulationJNI.new_ContactCylinder__SWIG_1(radius, Vec3.getCPtr(location), location, Vec3.getCPtr(orientation), orientation, PhysicalFrame.getCPtr(frame), frame), true);
  }

  public ContactCylinder(double radius, Vec3 location, Vec3 orientation, PhysicalFrame frame, String name) {
    this(opensimSimulationJNI.new_ContactCylinder__SWIG_2(radius, Vec3.getCPtr(location), location, Vec3.getCPtr(orientation), orientation, PhysicalFrame.getCPtr(frame), frame, name), true);
  }

  public double getRadius() {
    return opensimSimulationJNI.ContactCylinder_getRadius(swigCPtr, this);
  }

  public void setRadius(double radius) {
    opensimSimulationJNI.ContactCylinder_setRadius(swigCPtr, this, radius);
  }

  public void generateDecorations(boolean fixed, ModelDisplayHints hints, State s, ArrayDecorativeGeometry geometry) {
    opensimSimulationJNI.ContactCylinder_generateDecorations(swigCPtr, this, fixed, ModelDisplayHints.getCPtr(hints), hints, State.getCPtr(s), s, ArrayDecorativeGeometry.getCPtr(geometry), geometry);
  }

}
