/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class ContactSphere extends ContactGeometry {
  private transient long swigCPtr;

  public ContactSphere(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.ContactSphere_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ContactSphere obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ContactSphere obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_ContactSphere(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static ContactSphere safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.ContactSphere_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new ContactSphere(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.ContactSphere_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.ContactSphere_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.ContactSphere_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ContactSphere(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.ContactSphere_getConcreteClassName(swigCPtr, this);
  }

  public ContactSphere() {
    this(opensimSimulationJNI.new_ContactSphere__SWIG_0(), true);
  }

  public ContactSphere(double radius, Vec3 location, PhysicalFrame frame) {
    this(opensimSimulationJNI.new_ContactSphere__SWIG_1(radius, Vec3.getCPtr(location), location, PhysicalFrame.getCPtr(frame), frame), true);
  }

  public ContactSphere(double radius, Vec3 location, PhysicalFrame frame, String name) {
    this(opensimSimulationJNI.new_ContactSphere__SWIG_2(radius, Vec3.getCPtr(location), location, PhysicalFrame.getCPtr(frame), frame, name), true);
  }

  public double getRadius() {
    return opensimSimulationJNI.ContactSphere_getRadius(swigCPtr, this);
  }

  public void setRadius(double radius) {
    opensimSimulationJNI.ContactSphere_setRadius(swigCPtr, this, radius);
  }

  public void generateDecorations(boolean fixed, ModelDisplayHints hints, State s, ArrayDecorativeGeometry geometry) {
    opensimSimulationJNI.ContactSphere_generateDecorations(swigCPtr, this, fixed, ModelDisplayHints.getCPtr(hints), hints, State.getCPtr(s), s, ArrayDecorativeGeometry.getCPtr(geometry), geometry);
  }

}
