/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class ContactTorus extends ContactGeometry {
  private transient long swigCPtr;

  public ContactTorus(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.ContactTorus_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ContactTorus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ContactTorus obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_ContactTorus(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static ContactTorus safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.ContactTorus_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new ContactTorus(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.ContactTorus_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.ContactTorus_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.ContactTorus_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ContactTorus(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.ContactTorus_getConcreteClassName(swigCPtr, this);
  }

  public ContactTorus() {
    this(opensimSimulationJNI.new_ContactTorus__SWIG_0(), true);
  }

  public ContactTorus(double torus_radius, double tube_radius, Vec3 location, Vec3 orientation, PhysicalFrame frame) {
    this(opensimSimulationJNI.new_ContactTorus__SWIG_1(torus_radius, tube_radius, Vec3.getCPtr(location), location, Vec3.getCPtr(orientation), orientation, PhysicalFrame.getCPtr(frame), frame), true);
  }

  public ContactTorus(double torus_radius, double tube_radius, Vec3 location, Vec3 orientation, PhysicalFrame frame, String name) {
    this(opensimSimulationJNI.new_ContactTorus__SWIG_2(torus_radius, tube_radius, Vec3.getCPtr(location), location, Vec3.getCPtr(orientation), orientation, PhysicalFrame.getCPtr(frame), frame, name), true);
  }

  public double getTorusRadius() {
    return opensimSimulationJNI.ContactTorus_getTorusRadius(swigCPtr, this);
  }

  public void setTorusRadius(double radius) {
    opensimSimulationJNI.ContactTorus_setTorusRadius(swigCPtr, this, radius);
  }

  public double getTubeRadius() {
    return opensimSimulationJNI.ContactTorus_getTubeRadius(swigCPtr, this);
  }

  public void setTubeRadius(double radius) {
    opensimSimulationJNI.ContactTorus_setTubeRadius(swigCPtr, this, radius);
  }

  public void generateDecorations(boolean fixed, ModelDisplayHints hints, State s, ArrayDecorativeGeometry geometry) {
    opensimSimulationJNI.ContactTorus_generateDecorations(swigCPtr, this, fixed, ModelDisplayHints.getCPtr(hints), hints, State.getCPtr(s), s, ArrayDecorativeGeometry.getCPtr(geometry), geometry);
  }

}
