/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class ExpressionBasedFunction extends Function {
  private transient long swigCPtr;

  public ExpressionBasedFunction(long cPtr, boolean cMemoryOwn) {
    super(opensimCommonJNI.ExpressionBasedFunction_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ExpressionBasedFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ExpressionBasedFunction obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimCommonJNI.delete_ExpressionBasedFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static ExpressionBasedFunction safeDownCast(OpenSimObject obj) {
    long cPtr = opensimCommonJNI.ExpressionBasedFunction_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new ExpressionBasedFunction(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimCommonJNI.ExpressionBasedFunction_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimCommonJNI.ExpressionBasedFunction_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimCommonJNI.ExpressionBasedFunction_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ExpressionBasedFunction(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimCommonJNI.ExpressionBasedFunction_getConcreteClassName(swigCPtr, this);
  }

  public void copyProperty_expression(ExpressionBasedFunction source) {
    opensimCommonJNI.ExpressionBasedFunction_copyProperty_expression(swigCPtr, this, ExpressionBasedFunction.getCPtr(source), source);
  }

  public String get_expression(int i) {
    return opensimCommonJNI.ExpressionBasedFunction_get_expression__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_expression(int i) {
    return new SWIGTYPE_p_std__string(opensimCommonJNI.ExpressionBasedFunction_upd_expression__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_expression(int i, String value) {
    opensimCommonJNI.ExpressionBasedFunction_set_expression__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_expression(String value) {
    return opensimCommonJNI.ExpressionBasedFunction_append_expression(swigCPtr, this, value);
  }

  public void constructProperty_expression(String initValue) {
    opensimCommonJNI.ExpressionBasedFunction_constructProperty_expression(swigCPtr, this, initValue);
  }

  public String get_expression() {
    return opensimCommonJNI.ExpressionBasedFunction_get_expression__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_expression() {
    return new SWIGTYPE_p_std__string(opensimCommonJNI.ExpressionBasedFunction_upd_expression__SWIG_1(swigCPtr, this), false);
  }

  public void set_expression(String value) {
    opensimCommonJNI.ExpressionBasedFunction_set_expression__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_variables(ExpressionBasedFunction source) {
    opensimCommonJNI.ExpressionBasedFunction_copyProperty_variables(swigCPtr, this, ExpressionBasedFunction.getCPtr(source), source);
  }

  public String get_variables(int i) {
    return opensimCommonJNI.ExpressionBasedFunction_get_variables(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_variables(int i) {
    return new SWIGTYPE_p_std__string(opensimCommonJNI.ExpressionBasedFunction_upd_variables(swigCPtr, this, i), false);
  }

  public void set_variables(int i, String value) {
    opensimCommonJNI.ExpressionBasedFunction_set_variables(swigCPtr, this, i, value);
  }

  public int append_variables(String value) {
    return opensimCommonJNI.ExpressionBasedFunction_append_variables(swigCPtr, this, value);
  }

  public void constructProperty_variables() {
    opensimCommonJNI.ExpressionBasedFunction_constructProperty_variables(swigCPtr, this);
  }

  public ExpressionBasedFunction() {
    this(opensimCommonJNI.new_ExpressionBasedFunction__SWIG_0(), true);
  }

  public ExpressionBasedFunction(String expression, StdVectorString variables) {
    this(opensimCommonJNI.new_ExpressionBasedFunction__SWIG_1(expression, StdVectorString.getCPtr(variables), variables), true);
  }

  public void setExpression(String expression) {
    opensimCommonJNI.ExpressionBasedFunction_setExpression(swigCPtr, this, expression);
  }

  public String getExpression() {
    return opensimCommonJNI.ExpressionBasedFunction_getExpression(swigCPtr, this);
  }

  public void setVariables(StdVectorString variables) {
    opensimCommonJNI.ExpressionBasedFunction_setVariables(swigCPtr, this, StdVectorString.getCPtr(variables), variables);
  }

  public StdVectorString getVariables() {
    return new StdVectorString(opensimCommonJNI.ExpressionBasedFunction_getVariables(swigCPtr, this), true);
  }

  public SWIGTYPE_p_SimTK__Function createSimTKFunction() {
    long cPtr = opensimCommonJNI.ExpressionBasedFunction_createSimTKFunction(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SimTK__Function(cPtr, false);
  }

}
