/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class ExpressionBasedPathForce extends ForceProducer {
  private transient long swigCPtr;

  public ExpressionBasedPathForce(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.ExpressionBasedPathForce_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ExpressionBasedPathForce obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ExpressionBasedPathForce obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_ExpressionBasedPathForce(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static ExpressionBasedPathForce safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.ExpressionBasedPathForce_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new ExpressionBasedPathForce(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.ExpressionBasedPathForce_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.ExpressionBasedPathForce_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.ExpressionBasedPathForce_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ExpressionBasedPathForce(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.ExpressionBasedPathForce_getConcreteClassName(swigCPtr, this);
  }

  public void copyProperty_resting_length(ExpressionBasedPathForce source) {
    opensimSimulationJNI.ExpressionBasedPathForce_copyProperty_resting_length(swigCPtr, this, ExpressionBasedPathForce.getCPtr(source), source);
  }

  public double get_resting_length(int i) {
    return opensimSimulationJNI.ExpressionBasedPathForce_get_resting_length__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_resting_length(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.ExpressionBasedPathForce_upd_resting_length__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_resting_length(int i, double value) {
    opensimSimulationJNI.ExpressionBasedPathForce_set_resting_length__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_resting_length(double value) {
    return opensimSimulationJNI.ExpressionBasedPathForce_append_resting_length(swigCPtr, this, value);
  }

  public void constructProperty_resting_length(double initValue) {
    opensimSimulationJNI.ExpressionBasedPathForce_constructProperty_resting_length(swigCPtr, this, initValue);
  }

  public double get_resting_length() {
    return opensimSimulationJNI.ExpressionBasedPathForce_get_resting_length__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_resting_length() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.ExpressionBasedPathForce_upd_resting_length__SWIG_1(swigCPtr, this), false);
  }

  public void set_resting_length(double value) {
    opensimSimulationJNI.ExpressionBasedPathForce_set_resting_length__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_expression(ExpressionBasedPathForce source) {
    opensimSimulationJNI.ExpressionBasedPathForce_copyProperty_expression(swigCPtr, this, ExpressionBasedPathForce.getCPtr(source), source);
  }

  public String get_expression(int i) {
    return opensimSimulationJNI.ExpressionBasedPathForce_get_expression__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_expression(int i) {
    return new SWIGTYPE_p_std__string(opensimSimulationJNI.ExpressionBasedPathForce_upd_expression__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_expression(int i, String value) {
    opensimSimulationJNI.ExpressionBasedPathForce_set_expression__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_expression(String value) {
    return opensimSimulationJNI.ExpressionBasedPathForce_append_expression(swigCPtr, this, value);
  }

  public void constructProperty_expression(String initValue) {
    opensimSimulationJNI.ExpressionBasedPathForce_constructProperty_expression(swigCPtr, this, initValue);
  }

  public String get_expression() {
    return opensimSimulationJNI.ExpressionBasedPathForce_get_expression__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_expression() {
    return new SWIGTYPE_p_std__string(opensimSimulationJNI.ExpressionBasedPathForce_upd_expression__SWIG_1(swigCPtr, this), false);
  }

  public void set_expression(String value) {
    opensimSimulationJNI.ExpressionBasedPathForce_set_expression__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_path(ExpressionBasedPathForce source) {
    opensimSimulationJNI.ExpressionBasedPathForce_copyProperty_path(swigCPtr, this, ExpressionBasedPathForce.getCPtr(source), source);
  }

  public AbstractGeometryPath get_path(int i) {
    return new AbstractGeometryPath(opensimSimulationJNI.ExpressionBasedPathForce_get_path__SWIG_0(swigCPtr, this, i), false);
  }

  public AbstractGeometryPath upd_path(int i) {
    return new AbstractGeometryPath(opensimSimulationJNI.ExpressionBasedPathForce_upd_path__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_path(int i, AbstractGeometryPath value) {
    opensimSimulationJNI.ExpressionBasedPathForce_set_path__SWIG_0(swigCPtr, this, i, AbstractGeometryPath.getCPtr(value), value);
  }

  public int append_path(AbstractGeometryPath value) {
    return opensimSimulationJNI.ExpressionBasedPathForce_append_path(swigCPtr, this, AbstractGeometryPath.getCPtr(value), value);
  }

  public void constructProperty_path(AbstractGeometryPath initValue) {
    opensimSimulationJNI.ExpressionBasedPathForce_constructProperty_path(swigCPtr, this, AbstractGeometryPath.getCPtr(initValue), initValue);
  }

  public AbstractGeometryPath get_path() {
    return new AbstractGeometryPath(opensimSimulationJNI.ExpressionBasedPathForce_get_path__SWIG_1(swigCPtr, this), false);
  }

  public AbstractGeometryPath upd_path() {
    return new AbstractGeometryPath(opensimSimulationJNI.ExpressionBasedPathForce_upd_path__SWIG_1(swigCPtr, this), false);
  }

  public void set_path(AbstractGeometryPath value) {
    opensimSimulationJNI.ExpressionBasedPathForce_set_path__SWIG_1(swigCPtr, this, AbstractGeometryPath.getCPtr(value), value);
  }

  public void copyProperty_clamp_stretch(ExpressionBasedPathForce source) {
    opensimSimulationJNI.ExpressionBasedPathForce_copyProperty_clamp_stretch(swigCPtr, this, ExpressionBasedPathForce.getCPtr(source), source);
  }

  public boolean get_clamp_stretch(int i) {
    return opensimSimulationJNI.ExpressionBasedPathForce_get_clamp_stretch__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_clamp_stretch(int i) {
    return new SWIGTYPE_p_bool(opensimSimulationJNI.ExpressionBasedPathForce_upd_clamp_stretch__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_clamp_stretch(int i, boolean value) {
    opensimSimulationJNI.ExpressionBasedPathForce_set_clamp_stretch__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_clamp_stretch(boolean value) {
    return opensimSimulationJNI.ExpressionBasedPathForce_append_clamp_stretch(swigCPtr, this, value);
  }

  public void constructProperty_clamp_stretch(boolean initValue) {
    opensimSimulationJNI.ExpressionBasedPathForce_constructProperty_clamp_stretch(swigCPtr, this, initValue);
  }

  public boolean get_clamp_stretch() {
    return opensimSimulationJNI.ExpressionBasedPathForce_get_clamp_stretch__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_clamp_stretch() {
    return new SWIGTYPE_p_bool(opensimSimulationJNI.ExpressionBasedPathForce_upd_clamp_stretch__SWIG_1(swigCPtr, this), false);
  }

  public void set_clamp_stretch(boolean value) {
    opensimSimulationJNI.ExpressionBasedPathForce_set_clamp_stretch__SWIG_1(swigCPtr, this, value);
  }

  public void set_has_output_length(boolean value) {
    opensimSimulationJNI.ExpressionBasedPathForce__has_output_length_set(swigCPtr, this, value);
  }

  public boolean get_has_output_length() {
    return opensimSimulationJNI.ExpressionBasedPathForce__has_output_length_get(swigCPtr, this);
  }

  public void set_has_output_stretch(boolean value) {
    opensimSimulationJNI.ExpressionBasedPathForce__has_output_stretch_set(swigCPtr, this, value);
  }

  public boolean get_has_output_stretch() {
    return opensimSimulationJNI.ExpressionBasedPathForce__has_output_stretch_get(swigCPtr, this);
  }

  public void set_has_output_lengthening_speed(boolean value) {
    opensimSimulationJNI.ExpressionBasedPathForce__has_output_lengthening_speed_set(swigCPtr, this, value);
  }

  public boolean get_has_output_lengthening_speed() {
    return opensimSimulationJNI.ExpressionBasedPathForce__has_output_lengthening_speed_get(swigCPtr, this);
  }

  public void set_has_output_tension(boolean value) {
    opensimSimulationJNI.ExpressionBasedPathForce__has_output_tension_set(swigCPtr, this, value);
  }

  public boolean get_has_output_tension() {
    return opensimSimulationJNI.ExpressionBasedPathForce__has_output_tension_get(swigCPtr, this);
  }

  public ExpressionBasedPathForce() {
    this(opensimSimulationJNI.new_ExpressionBasedPathForce__SWIG_0(), true);
  }

  public ExpressionBasedPathForce(String name, double restLength, String expression, boolean clampStretch) {
    this(opensimSimulationJNI.new_ExpressionBasedPathForce__SWIG_1(name, restLength, expression, clampStretch), true);
  }

  public ExpressionBasedPathForce(String name, double restLength, String expression) {
    this(opensimSimulationJNI.new_ExpressionBasedPathForce__SWIG_2(name, restLength, expression), true);
  }

  public double getRestingLength() {
    return opensimSimulationJNI.ExpressionBasedPathForce_getRestingLength(swigCPtr, this);
  }

  public void setRestingLength(double restingLength) {
    opensimSimulationJNI.ExpressionBasedPathForce_setRestingLength(swigCPtr, this, restingLength);
  }

  public void setExpression(String expression) {
    opensimSimulationJNI.ExpressionBasedPathForce_setExpression(swigCPtr, this, expression);
  }

  public String getExpression() {
    return opensimSimulationJNI.ExpressionBasedPathForce_getExpression(swigCPtr, this);
  }

  public boolean getClampStretch() {
    return opensimSimulationJNI.ExpressionBasedPathForce_getClampStretch(swigCPtr, this);
  }

  public void setClampStretch(boolean clampStretch) {
    opensimSimulationJNI.ExpressionBasedPathForce_setClampStretch(swigCPtr, this, clampStretch);
  }

  public AbstractGeometryPath updPath() {
    return new AbstractGeometryPath(opensimSimulationJNI.ExpressionBasedPathForce_updPath(swigCPtr, this), false);
  }

  public AbstractGeometryPath getPath() {
    return new AbstractGeometryPath(opensimSimulationJNI.ExpressionBasedPathForce_getPath(swigCPtr, this), false);
  }

  public GeometryPath updGeometryPath() {
    return new GeometryPath(opensimSimulationJNI.ExpressionBasedPathForce_updGeometryPath(swigCPtr, this), false);
  }

  public GeometryPath getGeometryPath() {
    return new GeometryPath(opensimSimulationJNI.ExpressionBasedPathForce_getGeometryPath(swigCPtr, this), false);
  }

  public boolean hasVisualPath() {
    return opensimSimulationJNI.ExpressionBasedPathForce_hasVisualPath(swigCPtr, this);
  }

  public double getLength(State s) {
    return opensimSimulationJNI.ExpressionBasedPathForce_getLength(swigCPtr, this, State.getCPtr(s), s);
  }

  public double getStretch(State s) {
    return opensimSimulationJNI.ExpressionBasedPathForce_getStretch(swigCPtr, this, State.getCPtr(s), s);
  }

  public double getLengtheningSpeed(State s) {
    return opensimSimulationJNI.ExpressionBasedPathForce_getLengtheningSpeed(swigCPtr, this, State.getCPtr(s), s);
  }

  public double getTension(State s) {
    return opensimSimulationJNI.ExpressionBasedPathForce_getTension(swigCPtr, this, State.getCPtr(s), s);
  }

  public double computeMomentArm(State s, Coordinate aCoord) {
    return opensimSimulationJNI.ExpressionBasedPathForce_computeMomentArm(swigCPtr, this, State.getCPtr(s), s, Coordinate.getCPtr(aCoord), aCoord);
  }

  public void extendPostScale(State s, ScaleSet scaleSet) {
    opensimSimulationJNI.ExpressionBasedPathForce_extendPostScale(swigCPtr, this, State.getCPtr(s), s, ScaleSet.getCPtr(scaleSet), scaleSet);
  }

}
