/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class FileDeletionThrower {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public FileDeletionThrower(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(FileDeletionThrower obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(FileDeletionThrower obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_FileDeletionThrower(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FileDeletionThrower() {
    this(opensimMocoJNI.new_FileDeletionThrower__SWIG_0(), true);
  }

  public FileDeletionThrower(String filepath) {
    this(opensimMocoJNI.new_FileDeletionThrower__SWIG_1(filepath), true);
  }

  public void throwIfDeleted() {
    opensimMocoJNI.FileDeletionThrower_throwIfDeleted(swigCPtr, this);
  }

}
