/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class FunctionBasedPath extends AbstractGeometryPath {
  private transient long swigCPtr;

  public FunctionBasedPath(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.FunctionBasedPath_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(FunctionBasedPath obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(FunctionBasedPath obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_FunctionBasedPath(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static FunctionBasedPath safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.FunctionBasedPath_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new FunctionBasedPath(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.FunctionBasedPath_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.FunctionBasedPath_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.FunctionBasedPath_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new FunctionBasedPath(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.FunctionBasedPath_getConcreteClassName(swigCPtr, this);
  }

  public void copyProperty_coordinate_paths(FunctionBasedPath source) {
    opensimSimulationJNI.FunctionBasedPath_copyProperty_coordinate_paths(swigCPtr, this, FunctionBasedPath.getCPtr(source), source);
  }

  public String get_coordinate_paths(int i) {
    return opensimSimulationJNI.FunctionBasedPath_get_coordinate_paths(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_coordinate_paths(int i) {
    return new SWIGTYPE_p_std__string(opensimSimulationJNI.FunctionBasedPath_upd_coordinate_paths(swigCPtr, this, i), false);
  }

  public void set_coordinate_paths(int i, String value) {
    opensimSimulationJNI.FunctionBasedPath_set_coordinate_paths(swigCPtr, this, i, value);
  }

  public int append_coordinate_paths(String value) {
    return opensimSimulationJNI.FunctionBasedPath_append_coordinate_paths(swigCPtr, this, value);
  }

  public void constructProperty_coordinate_paths() {
    opensimSimulationJNI.FunctionBasedPath_constructProperty_coordinate_paths(swigCPtr, this);
  }

  public void copyProperty_length_function(FunctionBasedPath source) {
    opensimSimulationJNI.FunctionBasedPath_copyProperty_length_function(swigCPtr, this, FunctionBasedPath.getCPtr(source), source);
  }

  public Function get_length_function(int i) {
    return new Function(opensimSimulationJNI.FunctionBasedPath_get_length_function__SWIG_0(swigCPtr, this, i), false);
  }

  public Function upd_length_function(int i) {
    return new Function(opensimSimulationJNI.FunctionBasedPath_upd_length_function__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_length_function(int i, Function value) {
    opensimSimulationJNI.FunctionBasedPath_set_length_function__SWIG_0(swigCPtr, this, i, Function.getCPtr(value), value);
  }

  public int append_length_function(Function value) {
    return opensimSimulationJNI.FunctionBasedPath_append_length_function(swigCPtr, this, Function.getCPtr(value), value);
  }

  public void constructProperty_length_function() {
    opensimSimulationJNI.FunctionBasedPath_constructProperty_length_function__SWIG_0(swigCPtr, this);
  }

  public void constructProperty_length_function(Function initValue) {
    opensimSimulationJNI.FunctionBasedPath_constructProperty_length_function__SWIG_1(swigCPtr, this, Function.getCPtr(initValue), initValue);
  }

  public Function get_length_function() {
    return new Function(opensimSimulationJNI.FunctionBasedPath_get_length_function__SWIG_1(swigCPtr, this), false);
  }

  public Function upd_length_function() {
    return new Function(opensimSimulationJNI.FunctionBasedPath_upd_length_function__SWIG_1(swigCPtr, this), false);
  }

  public void set_length_function(Function value) {
    opensimSimulationJNI.FunctionBasedPath_set_length_function__SWIG_1(swigCPtr, this, Function.getCPtr(value), value);
  }

  public void copyProperty_moment_arm_functions(FunctionBasedPath source) {
    opensimSimulationJNI.FunctionBasedPath_copyProperty_moment_arm_functions(swigCPtr, this, FunctionBasedPath.getCPtr(source), source);
  }

  public Function get_moment_arm_functions(int i) {
    return new Function(opensimSimulationJNI.FunctionBasedPath_get_moment_arm_functions(swigCPtr, this, i), false);
  }

  public Function upd_moment_arm_functions(int i) {
    return new Function(opensimSimulationJNI.FunctionBasedPath_upd_moment_arm_functions(swigCPtr, this, i), false);
  }

  public void set_moment_arm_functions(int i, Function value) {
    opensimSimulationJNI.FunctionBasedPath_set_moment_arm_functions(swigCPtr, this, i, Function.getCPtr(value), value);
  }

  public int append_moment_arm_functions(Function value) {
    return opensimSimulationJNI.FunctionBasedPath_append_moment_arm_functions(swigCPtr, this, Function.getCPtr(value), value);
  }

  public void constructProperty_moment_arm_functions() {
    opensimSimulationJNI.FunctionBasedPath_constructProperty_moment_arm_functions(swigCPtr, this);
  }

  public void copyProperty_lengthening_speed_function(FunctionBasedPath source) {
    opensimSimulationJNI.FunctionBasedPath_copyProperty_lengthening_speed_function(swigCPtr, this, FunctionBasedPath.getCPtr(source), source);
  }

  public Function get_lengthening_speed_function(int i) {
    return new Function(opensimSimulationJNI.FunctionBasedPath_get_lengthening_speed_function__SWIG_0(swigCPtr, this, i), false);
  }

  public Function upd_lengthening_speed_function(int i) {
    return new Function(opensimSimulationJNI.FunctionBasedPath_upd_lengthening_speed_function__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_lengthening_speed_function(int i, Function value) {
    opensimSimulationJNI.FunctionBasedPath_set_lengthening_speed_function__SWIG_0(swigCPtr, this, i, Function.getCPtr(value), value);
  }

  public int append_lengthening_speed_function(Function value) {
    return opensimSimulationJNI.FunctionBasedPath_append_lengthening_speed_function(swigCPtr, this, Function.getCPtr(value), value);
  }

  public void constructProperty_lengthening_speed_function() {
    opensimSimulationJNI.FunctionBasedPath_constructProperty_lengthening_speed_function__SWIG_0(swigCPtr, this);
  }

  public void constructProperty_lengthening_speed_function(Function initValue) {
    opensimSimulationJNI.FunctionBasedPath_constructProperty_lengthening_speed_function__SWIG_1(swigCPtr, this, Function.getCPtr(initValue), initValue);
  }

  public Function get_lengthening_speed_function() {
    return new Function(opensimSimulationJNI.FunctionBasedPath_get_lengthening_speed_function__SWIG_1(swigCPtr, this), false);
  }

  public Function upd_lengthening_speed_function() {
    return new Function(opensimSimulationJNI.FunctionBasedPath_upd_lengthening_speed_function__SWIG_1(swigCPtr, this), false);
  }

  public void set_lengthening_speed_function(Function value) {
    opensimSimulationJNI.FunctionBasedPath_set_lengthening_speed_function__SWIG_1(swigCPtr, this, Function.getCPtr(value), value);
  }

  public FunctionBasedPath() {
    this(opensimSimulationJNI.new_FunctionBasedPath(), true);
  }

  public void setCoordinatePaths(StdVectorString coordinatePaths) {
    opensimSimulationJNI.FunctionBasedPath_setCoordinatePaths(swigCPtr, this, StdVectorString.getCPtr(coordinatePaths), coordinatePaths);
  }

  public void appendCoordinatePath(String coordinatePath) {
    opensimSimulationJNI.FunctionBasedPath_appendCoordinatePath(swigCPtr, this, coordinatePath);
  }

  public StdVectorString getCoordinatePaths() {
    return new StdVectorString(opensimSimulationJNI.FunctionBasedPath_getCoordinatePaths(swigCPtr, this), true);
  }

  public void setLengthFunction(Function lengthFunction) {
    opensimSimulationJNI.FunctionBasedPath_setLengthFunction(swigCPtr, this, Function.getCPtr(lengthFunction), lengthFunction);
  }

  public Function getLengthFunction() {
    return new Function(opensimSimulationJNI.FunctionBasedPath_getLengthFunction(swigCPtr, this), false);
  }

  public void setMomentArmFunctions(SWIGTYPE_p_std__vectorT_OpenSim__Function_t momentArmFunctions) {
    opensimSimulationJNI.FunctionBasedPath_setMomentArmFunctions(swigCPtr, this, SWIGTYPE_p_std__vectorT_OpenSim__Function_t.getCPtr(momentArmFunctions));
  }

  public void appendMomentArmFunction(Function momentArmFunction) {
    opensimSimulationJNI.FunctionBasedPath_appendMomentArmFunction(swigCPtr, this, Function.getCPtr(momentArmFunction), momentArmFunction);
  }

  public Function getMomentArmFunction(String coordinatePath) {
    return new Function(opensimSimulationJNI.FunctionBasedPath_getMomentArmFunction(swigCPtr, this, coordinatePath), false);
  }

  public Vector getMomentArms(State s) {
    return new Vector(opensimSimulationJNI.FunctionBasedPath_getMomentArms(swigCPtr, this, State.getCPtr(s), s), false);
  }

  public void setLengtheningSpeedFunction(Function speedFunction) {
    opensimSimulationJNI.FunctionBasedPath_setLengtheningSpeedFunction(swigCPtr, this, Function.getCPtr(speedFunction), speedFunction);
  }

  public Function getLengtheningSpeedFunction() {
    return new Function(opensimSimulationJNI.FunctionBasedPath_getLengtheningSpeedFunction(swigCPtr, this), false);
  }

  public double getLength(State s) {
    return opensimSimulationJNI.FunctionBasedPath_getLength(swigCPtr, this, State.getCPtr(s), s);
  }

  public double getLengtheningSpeed(State s) {
    return opensimSimulationJNI.FunctionBasedPath_getLengtheningSpeed(swigCPtr, this, State.getCPtr(s), s);
  }

  public double computeMomentArm(State s, Coordinate coord) {
    return opensimSimulationJNI.FunctionBasedPath_computeMomentArm(swigCPtr, this, State.getCPtr(s), s, Coordinate.getCPtr(coord), coord);
  }

  public void produceForces(State arg0, double tension, SWIGTYPE_p_OpenSim__ForceConsumer arg2) {
    opensimSimulationJNI.FunctionBasedPath_produceForces(swigCPtr, this, State.getCPtr(arg0), arg0, tension, SWIGTYPE_p_OpenSim__ForceConsumer.getCPtr(arg2));
  }

  public boolean isVisualPath() {
    return opensimSimulationJNI.FunctionBasedPath_isVisualPath(swigCPtr, this);
  }

}
