/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class InputController extends Controller {
  private transient long swigCPtr;

  public InputController(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.InputController_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(InputController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(InputController obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_InputController(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static InputController safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.InputController_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new InputController(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.InputController_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.InputController_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.InputController_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new InputController(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.InputController_getConcreteClassName(swigCPtr, this);
  }

  public void setPropertyIndex_input_controls(SWIGTYPE_p_OpenSim__PropertyIndex value) {
    opensimSimulationJNI.InputController_PropertyIndex_input_controls_set(swigCPtr, this, SWIGTYPE_p_OpenSim__PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_OpenSim__PropertyIndex getPropertyIndex_input_controls() {
    return new SWIGTYPE_p_OpenSim__PropertyIndex(opensimSimulationJNI.InputController_PropertyIndex_input_controls_get(swigCPtr, this), true);
  }

  public void connectInput_controls(AbstractOutput output, String alias) {
    opensimSimulationJNI.InputController_connectInput_controls__SWIG_0(swigCPtr, this, AbstractOutput.getCPtr(output), output, alias);
  }

  public void connectInput_controls(AbstractOutput output) {
    opensimSimulationJNI.InputController_connectInput_controls__SWIG_1(swigCPtr, this, AbstractOutput.getCPtr(output), output);
  }

  public void connectInput_controls(AbstractChannel channel, String alias) {
    opensimSimulationJNI.InputController_connectInput_controls__SWIG_2(swigCPtr, this, AbstractChannel.getCPtr(channel), channel, alias);
  }

  public void connectInput_controls(AbstractChannel channel) {
    opensimSimulationJNI.InputController_connectInput_controls__SWIG_3(swigCPtr, this, AbstractChannel.getCPtr(channel), channel);
  }

  public StdVectorString getInputControlLabels() {
    return new StdVectorString(opensimSimulationJNI.InputController_getInputControlLabels(swigCPtr, this), true);
  }

  public void computeControlsImpl(State state, Vector controls) {
    opensimSimulationJNI.InputController_computeControlsImpl(swigCPtr, this, State.getCPtr(state), state, Vector.getCPtr(controls), controls);
  }

  public void computeControls(State state, Vector controls) {
    opensimSimulationJNI.InputController_computeControls(swigCPtr, this, State.getCPtr(state), state, Vector.getCPtr(controls), controls);
  }

  public int getNumInputControls() {
    return opensimSimulationJNI.InputController_getNumInputControls(swigCPtr, this);
  }

  public StdVectorString getControlNames() {
    return new StdVectorString(opensimSimulationJNI.InputController_getControlNames(swigCPtr, this), false);
  }

  public StdVectorInt getControlIndexes() {
    return new StdVectorInt(opensimSimulationJNI.InputController_getControlIndexes(swigCPtr, this), false);
  }

}
