/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class InvalidColumnLabel extends OpenSimException {
  private transient long swigCPtr;

  public InvalidColumnLabel(long cPtr, boolean cMemoryOwn) {
    super(opensimCommonJNI.InvalidColumnLabel_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(InvalidColumnLabel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(InvalidColumnLabel obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimCommonJNI.delete_InvalidColumnLabel(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public InvalidColumnLabel(String aMsg, String aFile, int aLine) {
    this(opensimCommonJNI.new_InvalidColumnLabel__SWIG_0(aMsg, aFile, aLine), true);
  }

  public InvalidColumnLabel(String aMsg, String aFile) {
    this(opensimCommonJNI.new_InvalidColumnLabel__SWIG_1(aMsg, aFile), true);
  }

  public InvalidColumnLabel(String aMsg) {
    this(opensimCommonJNI.new_InvalidColumnLabel__SWIG_2(aMsg), true);
  }

  public InvalidColumnLabel() {
    this(opensimCommonJNI.new_InvalidColumnLabel__SWIG_3(), true);
  }

  public InvalidColumnLabel(String file, long line, String func) {
    this(opensimCommonJNI.new_InvalidColumnLabel__SWIG_4(file, line, func), true);
  }

  public InvalidColumnLabel(String file, long line, String func, String msg) {
    this(opensimCommonJNI.new_InvalidColumnLabel__SWIG_5(file, line, func, msg), true);
  }

  public InvalidColumnLabel(String file, long line, String func, OpenSimObject obj) {
    this(opensimCommonJNI.new_InvalidColumnLabel__SWIG_6(file, line, func, OpenSimObject.getCPtr(obj), obj), true);
  }

  public InvalidColumnLabel(String file, long line, String func, OpenSimObject obj, String msg) {
    this(opensimCommonJNI.new_InvalidColumnLabel__SWIG_7(file, line, func, OpenSimObject.getCPtr(obj), obj, msg), true);
  }

  public InvalidColumnLabel(String file, long line, String func, Component component) {
    this(opensimCommonJNI.new_InvalidColumnLabel__SWIG_8(file, line, func, Component.getCPtr(component), component), true);
  }

  public InvalidColumnLabel(String file, long line, String func, Component component, String msg) {
    this(opensimCommonJNI.new_InvalidColumnLabel__SWIG_9(file, line, func, Component.getCPtr(component), component, msg), true);
  }

}
