/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class Manager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Manager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Manager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(Manager obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_Manager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Manager(Model model) {
    this(opensimSimulationJNI.new_Manager__SWIG_0(Model.getCPtr(model), model), true);
  }

  public Manager(Model model, State state) {
    this(opensimSimulationJNI.new_Manager__SWIG_1(Model.getCPtr(model), model, State.getCPtr(state), state), true);
  }

  public void setSessionName(String name) {
    opensimSimulationJNI.Manager_setSessionName(swigCPtr, this, name);
  }

  public String getSessionName() {
    return opensimSimulationJNI.Manager_getSessionName(swigCPtr, this);
  }

  public void setPerformAnalyses(boolean performAnalyses) {
    opensimSimulationJNI.Manager_setPerformAnalyses(swigCPtr, this, performAnalyses);
  }

  public void setWriteToStorage(boolean writeToStorage) {
    opensimSimulationJNI.Manager_setWriteToStorage(swigCPtr, this, writeToStorage);
  }

  public void setRecordStatesTrajectory(boolean recordStatesTrajectory) {
    opensimSimulationJNI.Manager_setRecordStatesTrajectory(swigCPtr, this, recordStatesTrajectory);
  }

  public void setIntegratorMethod(Manager.IntegratorMethod integMethod) {
    opensimSimulationJNI.Manager_setIntegratorMethod__SWIG_0(swigCPtr, this, integMethod.swigValue());
  }

  public Manager.IntegratorMethod getIntegratorMethod() {
    return Manager.IntegratorMethod.swigToEnum(opensimSimulationJNI.Manager_getIntegratorMethod(swigCPtr, this));
  }

  public void setIntegratorAccuracy(double accuracy) {
    opensimSimulationJNI.Manager_setIntegratorAccuracy(swigCPtr, this, accuracy);
  }

  public void setIntegratorMinimumStepSize(double hmin) {
    opensimSimulationJNI.Manager_setIntegratorMinimumStepSize(swigCPtr, this, hmin);
  }

  public void setIntegratorMaximumStepSize(double hmax) {
    opensimSimulationJNI.Manager_setIntegratorMaximumStepSize(swigCPtr, this, hmax);
  }

  public void setIntegratorInternalStepLimit(int nSteps) {
    opensimSimulationJNI.Manager_setIntegratorInternalStepLimit(swigCPtr, this, nSteps);
  }

  public void setIntegratorFixedStepSize(double stepSize) {
    opensimSimulationJNI.Manager_setIntegratorFixedStepSize(swigCPtr, this, stepSize);
  }

  public void setIntegratorFinalTime(double finalTime) {
    opensimSimulationJNI.Manager_setIntegratorFinalTime(swigCPtr, this, finalTime);
  }

  public void setIntegratorUseInfinityNorm(boolean useInfinityNorm) {
    opensimSimulationJNI.Manager_setIntegratorUseInfinityNorm(swigCPtr, this, useInfinityNorm);
  }

  public void setIntegratorConstraintTolerance(double tol) {
    opensimSimulationJNI.Manager_setIntegratorConstraintTolerance(swigCPtr, this, tol);
  }

  public SWIGTYPE_p_SimTK__Integrator getIntegrator() {
    return new SWIGTYPE_p_SimTK__Integrator(opensimSimulationJNI.Manager_getIntegrator(swigCPtr, this), false);
  }

  public void initialize(State s) {
    opensimSimulationJNI.Manager_initialize(swigCPtr, this, State.getCPtr(s), s);
  }

  public State integrate(double finalTime) {
    return new State(opensimSimulationJNI.Manager_integrate(swigCPtr, this, finalTime), false);
  }

  public State getState() {
    return new State(opensimSimulationJNI.Manager_getState(swigCPtr, this), false);
  }

  public Storage getStateStorage() {
    return new Storage(opensimSimulationJNI.Manager_getStateStorage(swigCPtr, this), true);
  }

  public TimeSeriesTable getStatesTable() {
    return new TimeSeriesTable(opensimSimulationJNI.Manager_getStatesTable(swigCPtr, this), true);
  }

  public StatesTrajectory getStatesTrajectory() {
    return new StatesTrajectory(opensimSimulationJNI.Manager_getStatesTrajectory(swigCPtr, this), true);
  }

  public void setIntegratorMethod(int method) {
    opensimSimulationJNI.Manager_setIntegratorMethod__SWIG_1(swigCPtr, this, method);
  }

  public final static class IntegratorMethod {
    public final static Manager.IntegratorMethod ExplicitEuler = new Manager.IntegratorMethod("ExplicitEuler", opensimSimulationJNI.Manager_IntegratorMethod_ExplicitEuler_get());
    public final static Manager.IntegratorMethod RungeKutta2 = new Manager.IntegratorMethod("RungeKutta2", opensimSimulationJNI.Manager_IntegratorMethod_RungeKutta2_get());
    public final static Manager.IntegratorMethod RungeKutta3 = new Manager.IntegratorMethod("RungeKutta3", opensimSimulationJNI.Manager_IntegratorMethod_RungeKutta3_get());
    public final static Manager.IntegratorMethod RungeKuttaFeldberg = new Manager.IntegratorMethod("RungeKuttaFeldberg", opensimSimulationJNI.Manager_IntegratorMethod_RungeKuttaFeldberg_get());
    public final static Manager.IntegratorMethod RungeKuttaMerson = new Manager.IntegratorMethod("RungeKuttaMerson", opensimSimulationJNI.Manager_IntegratorMethod_RungeKuttaMerson_get());
    public final static Manager.IntegratorMethod SemiExplicitEuler2 = new Manager.IntegratorMethod("SemiExplicitEuler2", opensimSimulationJNI.Manager_IntegratorMethod_SemiExplicitEuler2_get());
    public final static Manager.IntegratorMethod Verlet = new Manager.IntegratorMethod("Verlet", opensimSimulationJNI.Manager_IntegratorMethod_Verlet_get());
    public final static Manager.IntegratorMethod CPodes = new Manager.IntegratorMethod("CPodes", opensimSimulationJNI.Manager_IntegratorMethod_CPodes_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static IntegratorMethod swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + IntegratorMethod.class + " with value " + swigValue);
    }

    private IntegratorMethod(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private IntegratorMethod(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private IntegratorMethod(String swigName, IntegratorMethod swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static IntegratorMethod[] swigValues = { ExplicitEuler, RungeKutta2, RungeKutta3, RungeKuttaFeldberg, RungeKuttaMerson, SemiExplicitEuler2, Verlet, CPodes };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
