/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class Mat33 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Mat33(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Mat33 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(Mat33 obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimbodyJNI.delete_Mat33(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static int size() {
    return opensimSimbodyJNI.Mat33_size();
  }

  public static int nrow() {
    return opensimSimbodyJNI.Mat33_nrow();
  }

  public static int ncol() {
    return opensimSimbodyJNI.Mat33_ncol();
  }

  public Mat33() {
    this(opensimSimbodyJNI.new_Mat33__SWIG_0(), true);
  }

  public Mat33(Mat33 src) {
    this(opensimSimbodyJNI.new_Mat33__SWIG_1(Mat33.getCPtr(src), src), true);
  }

  public Mat33(double e) {
    this(opensimSimbodyJNI.new_Mat33__SWIG_2(e), true);
  }

  public Mat33(int i) {
    this(opensimSimbodyJNI.new_Mat33__SWIG_3(i), true);
  }

  public Mat33(double e0, double e1, double e2, double e3, double e4, double e5, double e6, double e7, double e8) {
    this(opensimSimbodyJNI.new_Mat33__SWIG_4(e0, e1, e2, e3, e4, e5, e6, e7, e8), true);
  }

  public void setToNaN() {
    opensimSimbodyJNI.Mat33_setToNaN(swigCPtr, this);
  }

  public void setToZero() {
    opensimSimbodyJNI.Mat33_setToZero(swigCPtr, this);
  }

  public boolean isNaN() {
    return opensimSimbodyJNI.Mat33_isNaN(swigCPtr, this);
  }

  public boolean isInf() {
    return opensimSimbodyJNI.Mat33_isInf(swigCPtr, this);
  }

  public boolean isFinite() {
    return opensimSimbodyJNI.Mat33_isFinite(swigCPtr, this);
  }

  public static double getDefaultTolerance() {
    return opensimSimbodyJNI.Mat33_getDefaultTolerance();
  }

  public boolean isNumericallyEqual(double e, double tol) {
    return opensimSimbodyJNI.Mat33_isNumericallyEqual__SWIG_0(swigCPtr, this, e, tol);
  }

  public boolean isNumericallyEqual(double e) {
    return opensimSimbodyJNI.Mat33_isNumericallyEqual__SWIG_1(swigCPtr, this, e);
  }

  public boolean isNumericallySymmetric(double tol) {
    return opensimSimbodyJNI.Mat33_isNumericallySymmetric__SWIG_0(swigCPtr, this, tol);
  }

  public boolean isNumericallySymmetric() {
    return opensimSimbodyJNI.Mat33_isNumericallySymmetric__SWIG_1(swigCPtr, this);
  }

  public boolean isExactlySymmetric() {
    return opensimSimbodyJNI.Mat33_isExactlySymmetric(swigCPtr, this);
  }

  public String toString() {
    return opensimSimbodyJNI.Mat33_toString(swigCPtr, this);
  }

  public double get(int i, int j) {
    return opensimSimbodyJNI.Mat33_get(swigCPtr, this, i, j);
  }

  public void set(int i, int j, double value) {
    opensimSimbodyJNI.Mat33_set(swigCPtr, this, i, j, value);
  }

}
