/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MatrixViewVec3 extends MatrixBaseVec3 {
  private transient long swigCPtr;

  public MatrixViewVec3(long cPtr, boolean cMemoryOwn) {
    super(opensimSimbodyJNI.MatrixViewVec3_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MatrixViewVec3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MatrixViewVec3 obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimbodyJNI.delete_MatrixViewVec3(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MatrixViewVec3(MatrixViewVec3 m) {
    this(opensimSimbodyJNI.new_MatrixViewVec3(MatrixViewVec3.getCPtr(m), m), true);
  }

}
