/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MeyerFregly2016Muscle extends Muscle {
  private transient long swigCPtr;

  public MeyerFregly2016Muscle(long cPtr, boolean cMemoryOwn) {
    super(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MeyerFregly2016Muscle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MeyerFregly2016Muscle obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimActuatorsAnalysesToolsJNI.delete_MeyerFregly2016Muscle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MeyerFregly2016Muscle safeDownCast(OpenSimObject obj) {
    long cPtr = opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MeyerFregly2016Muscle(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MeyerFregly2016Muscle(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_getConcreteClassName(swigCPtr, this);
  }

  public void copyProperty_activation_time_constant(MeyerFregly2016Muscle source) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_copyProperty_activation_time_constant(swigCPtr, this, MeyerFregly2016Muscle.getCPtr(source), source);
  }

  public double get_activation_time_constant(int i) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_get_activation_time_constant__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_activation_time_constant(int i) {
    return new SWIGTYPE_p_double(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_upd_activation_time_constant__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_activation_time_constant(int i, double value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_set_activation_time_constant__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_activation_time_constant(double value) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_append_activation_time_constant(swigCPtr, this, value);
  }

  public void constructProperty_activation_time_constant(double initValue) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_constructProperty_activation_time_constant(swigCPtr, this, initValue);
  }

  public double get_activation_time_constant() {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_get_activation_time_constant__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_activation_time_constant() {
    return new SWIGTYPE_p_double(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_upd_activation_time_constant__SWIG_1(swigCPtr, this), false);
  }

  public void set_activation_time_constant(double value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_set_activation_time_constant__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_deactivation_time_constant(MeyerFregly2016Muscle source) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_copyProperty_deactivation_time_constant(swigCPtr, this, MeyerFregly2016Muscle.getCPtr(source), source);
  }

  public double get_deactivation_time_constant(int i) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_get_deactivation_time_constant__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_deactivation_time_constant(int i) {
    return new SWIGTYPE_p_double(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_upd_deactivation_time_constant__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_deactivation_time_constant(int i, double value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_set_deactivation_time_constant__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_deactivation_time_constant(double value) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_append_deactivation_time_constant(swigCPtr, this, value);
  }

  public void constructProperty_deactivation_time_constant(double initValue) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_constructProperty_deactivation_time_constant(swigCPtr, this, initValue);
  }

  public double get_deactivation_time_constant() {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_get_deactivation_time_constant__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_deactivation_time_constant() {
    return new SWIGTYPE_p_double(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_upd_deactivation_time_constant__SWIG_1(swigCPtr, this), false);
  }

  public void set_deactivation_time_constant(double value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_set_deactivation_time_constant__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_default_activation(MeyerFregly2016Muscle source) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_copyProperty_default_activation(swigCPtr, this, MeyerFregly2016Muscle.getCPtr(source), source);
  }

  public double get_default_activation(int i) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_get_default_activation__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_default_activation(int i) {
    return new SWIGTYPE_p_double(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_upd_default_activation__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_default_activation(int i, double value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_set_default_activation__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_default_activation(double value) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_append_default_activation(swigCPtr, this, value);
  }

  public void constructProperty_default_activation(double initValue) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_constructProperty_default_activation(swigCPtr, this, initValue);
  }

  public double get_default_activation() {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_get_default_activation__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_default_activation() {
    return new SWIGTYPE_p_double(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_upd_default_activation__SWIG_1(swigCPtr, this), false);
  }

  public void set_default_activation(double value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_set_default_activation__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_active_force_width_scale(MeyerFregly2016Muscle source) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_copyProperty_active_force_width_scale(swigCPtr, this, MeyerFregly2016Muscle.getCPtr(source), source);
  }

  public double get_active_force_width_scale(int i) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_get_active_force_width_scale__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_active_force_width_scale(int i) {
    return new SWIGTYPE_p_double(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_upd_active_force_width_scale__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_active_force_width_scale(int i, double value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_set_active_force_width_scale__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_active_force_width_scale(double value) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_append_active_force_width_scale(swigCPtr, this, value);
  }

  public void constructProperty_active_force_width_scale(double initValue) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_constructProperty_active_force_width_scale(swigCPtr, this, initValue);
  }

  public double get_active_force_width_scale() {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_get_active_force_width_scale__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_active_force_width_scale() {
    return new SWIGTYPE_p_double(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_upd_active_force_width_scale__SWIG_1(swigCPtr, this), false);
  }

  public void set_active_force_width_scale(double value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_set_active_force_width_scale__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_fiber_damping(MeyerFregly2016Muscle source) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_copyProperty_fiber_damping(swigCPtr, this, MeyerFregly2016Muscle.getCPtr(source), source);
  }

  public double get_fiber_damping(int i) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_get_fiber_damping__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_fiber_damping(int i) {
    return new SWIGTYPE_p_double(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_upd_fiber_damping__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_fiber_damping(int i, double value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_set_fiber_damping__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_fiber_damping(double value) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_append_fiber_damping(swigCPtr, this, value);
  }

  public void constructProperty_fiber_damping(double initValue) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_constructProperty_fiber_damping(swigCPtr, this, initValue);
  }

  public double get_fiber_damping() {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_get_fiber_damping__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_fiber_damping() {
    return new SWIGTYPE_p_double(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_upd_fiber_damping__SWIG_1(swigCPtr, this), false);
  }

  public void set_fiber_damping(double value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_set_fiber_damping__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_ignore_passive_fiber_force(MeyerFregly2016Muscle source) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_copyProperty_ignore_passive_fiber_force(swigCPtr, this, MeyerFregly2016Muscle.getCPtr(source), source);
  }

  public boolean get_ignore_passive_fiber_force(int i) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_get_ignore_passive_fiber_force__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_ignore_passive_fiber_force(int i) {
    return new SWIGTYPE_p_bool(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_upd_ignore_passive_fiber_force__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_ignore_passive_fiber_force(int i, boolean value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_set_ignore_passive_fiber_force__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_ignore_passive_fiber_force(boolean value) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_append_ignore_passive_fiber_force(swigCPtr, this, value);
  }

  public void constructProperty_ignore_passive_fiber_force(boolean initValue) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_constructProperty_ignore_passive_fiber_force(swigCPtr, this, initValue);
  }

  public boolean get_ignore_passive_fiber_force() {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_get_ignore_passive_fiber_force__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_ignore_passive_fiber_force() {
    return new SWIGTYPE_p_bool(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_upd_ignore_passive_fiber_force__SWIG_1(swigCPtr, this), false);
  }

  public void set_ignore_passive_fiber_force(boolean value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_set_ignore_passive_fiber_force__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_activation_dynamics_smoothing(MeyerFregly2016Muscle source) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_copyProperty_activation_dynamics_smoothing(swigCPtr, this, MeyerFregly2016Muscle.getCPtr(source), source);
  }

  public double get_activation_dynamics_smoothing(int i) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_get_activation_dynamics_smoothing__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_activation_dynamics_smoothing(int i) {
    return new SWIGTYPE_p_double(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_upd_activation_dynamics_smoothing__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_activation_dynamics_smoothing(int i, double value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_set_activation_dynamics_smoothing__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_activation_dynamics_smoothing(double value) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_append_activation_dynamics_smoothing(swigCPtr, this, value);
  }

  public void constructProperty_activation_dynamics_smoothing(double initValue) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_constructProperty_activation_dynamics_smoothing(swigCPtr, this, initValue);
  }

  public double get_activation_dynamics_smoothing() {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_get_activation_dynamics_smoothing__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_activation_dynamics_smoothing() {
    return new SWIGTYPE_p_double(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_upd_activation_dynamics_smoothing__SWIG_1(swigCPtr, this), false);
  }

  public void set_activation_dynamics_smoothing(double value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_set_activation_dynamics_smoothing__SWIG_1(swigCPtr, this, value);
  }

  public void set_has_output_passive_fiber_elastic_force(boolean value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle__has_output_passive_fiber_elastic_force_set(swigCPtr, this, value);
  }

  public boolean get_has_output_passive_fiber_elastic_force() {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle__has_output_passive_fiber_elastic_force_get(swigCPtr, this);
  }

  public void set_has_output_passive_fiber_elastic_force_along_tendon(boolean value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle__has_output_passive_fiber_elastic_force_along_tendon_set(swigCPtr, this, value);
  }

  public boolean get_has_output_passive_fiber_elastic_force_along_tendon() {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle__has_output_passive_fiber_elastic_force_along_tendon_get(swigCPtr, this);
  }

  public void set_has_output_passive_fiber_damping_force(boolean value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle__has_output_passive_fiber_damping_force_set(swigCPtr, this, value);
  }

  public boolean get_has_output_passive_fiber_damping_force() {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle__has_output_passive_fiber_damping_force_get(swigCPtr, this);
  }

  public void set_has_output_passive_fiber_damping_force_along_tendon(boolean value) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle__has_output_passive_fiber_damping_force_along_tendon_set(swigCPtr, this, value);
  }

  public boolean get_has_output_passive_fiber_damping_force_along_tendon() {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle__has_output_passive_fiber_damping_force_along_tendon_get(swigCPtr, this);
  }

  public MeyerFregly2016Muscle() {
    this(opensimActuatorsAnalysesToolsJNI.new_MeyerFregly2016Muscle(), true);
  }

  public double getActivation(State arg0) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_getActivation(swigCPtr, this, State.getCPtr(arg0), arg0);
  }

  public void setActivation(State arg0, double arg1) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_setActivation(swigCPtr, this, State.getCPtr(arg0), arg0, arg1);
  }

  public double calcMuscleStiffness(State arg0) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcMuscleStiffness__SWIG_0(swigCPtr, this, State.getCPtr(arg0), arg0);
  }

  public void computeInitialFiberEquilibrium(State arg0) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_computeInitialFiberEquilibrium(swigCPtr, this, State.getCPtr(arg0), arg0);
  }

  public double getPassiveFiberElasticForce(State arg0) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_getPassiveFiberElasticForce(swigCPtr, this, State.getCPtr(arg0), arg0);
  }

  public double getPassiveFiberElasticForceAlongTendon(State arg0) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_getPassiveFiberElasticForceAlongTendon(swigCPtr, this, State.getCPtr(arg0), arg0);
  }

  public double getPassiveFiberDampingForce(State arg0) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_getPassiveFiberDampingForce(swigCPtr, this, State.getCPtr(arg0), arg0);
  }

  public double getPassiveFiberDampingForceAlongTendon(State arg0) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_getPassiveFiberDampingForceAlongTendon(swigCPtr, this, State.getCPtr(arg0), arg0);
  }

  public Vec2 getBoundsNormalizedFiberLength() {
    return new Vec2(opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_getBoundsNormalizedFiberLength(swigCPtr, this), true);
  }

  public double calcActiveForceLengthMultiplier(double arg0) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcActiveForceLengthMultiplier(swigCPtr, this, arg0);
  }

  public double calcActiveForceLengthMultiplierDerivative(double arg0) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcActiveForceLengthMultiplierDerivative(swigCPtr, this, arg0);
  }

  public static double calcForceVelocityMultiplier(double arg0) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcForceVelocityMultiplier(arg0);
  }

  public static double calcForceVelocityInverseCurve(double arg0) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcForceVelocityInverseCurve(arg0);
  }

  public double calcPassiveForceMultiplier(double arg0) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcPassiveForceMultiplier(swigCPtr, this, arg0);
  }

  public double calcPassiveForceMultiplierDerivative(double arg0) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcPassiveForceMultiplierDerivative(swigCPtr, this, arg0);
  }

  public double calcPassiveForceMultiplierIntegral(double arg0) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcPassiveForceMultiplierIntegral(swigCPtr, this, arg0);
  }

  public void calcFiberForce(double activation, double activeForceLengthMultiplier, double forceVelocityMultiplier, double normPassiveFiberForce, double normFiberVelocity, SWIGTYPE_p_double activeFiberForce, SWIGTYPE_p_double conPassiveFiberForce, SWIGTYPE_p_double nonConPassiveFiberForce, SWIGTYPE_p_double totalFiberForce) {
    opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcFiberForce(swigCPtr, this, activation, activeForceLengthMultiplier, forceVelocityMultiplier, normPassiveFiberForce, normFiberVelocity, SWIGTYPE_p_double.getCPtr(activeFiberForce), SWIGTYPE_p_double.getCPtr(conPassiveFiberForce), SWIGTYPE_p_double.getCPtr(nonConPassiveFiberForce), SWIGTYPE_p_double.getCPtr(totalFiberForce));
  }

  public double calcFiberStiffness(double activation, double normFiberLength, double fiberVelocityMultiplier) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcFiberStiffness(swigCPtr, this, activation, normFiberLength, fiberVelocityMultiplier);
  }

  public double calcMuscleStiffness(double tendonStiffness, double fiberStiffnessAlongTendon) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcMuscleStiffness__SWIG_1(swigCPtr, this, tendonStiffness, fiberStiffnessAlongTendon);
  }

  public double calcPartialPennationAnglePartialFiberLength(double arg0) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcPartialPennationAnglePartialFiberLength(swigCPtr, this, arg0);
  }

  public double calcPartialFiberForceAlongTendonPartialFiberLength(double fiberForce, double fiberStiffness, double sinPennationAngle, double cosPennationAngle, double partialPennationAnglePartialFiberLength) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcPartialFiberForceAlongTendonPartialFiberLength(swigCPtr, this, fiberForce, fiberStiffness, sinPennationAngle, cosPennationAngle, partialPennationAnglePartialFiberLength);
  }

  public double calcFiberStiffnessAlongTendon(double fiberLength, double partialFiberForceAlongTendonPartialFiberLength, double sinPennationAngle, double cosPennationAngle, double partialPennationAnglePartialFiberLength) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcFiberStiffnessAlongTendon(swigCPtr, this, fiberLength, partialFiberForceAlongTendonPartialFiberLength, sinPennationAngle, cosPennationAngle, partialPennationAnglePartialFiberLength);
  }

  public double calcPartialTendonLengthPartialFiberLength(double fiberLength, double sinPennationAngle, double cosPennationAngle, double partialPennationAnglePartialFiberLength) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcPartialTendonLengthPartialFiberLength(swigCPtr, this, fiberLength, sinPennationAngle, cosPennationAngle, partialPennationAnglePartialFiberLength);
  }

  public double calcPartialTendonForcePartialFiberLength(double tendonStiffness, double fiberLength, double sinPennationAngle, double cosPennationAngle) {
    return opensimActuatorsAnalysesToolsJNI.MeyerFregly2016Muscle_calcPartialTendonForcePartialFiberLength(swigCPtr, this, tendonStiffness, fiberLength, sinPennationAngle, cosPennationAngle);
  }

}
