/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MeyerFregly2016Force extends ForceProducer {
  private transient long swigCPtr;

  public MeyerFregly2016Force(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.MeyerFregly2016Force_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MeyerFregly2016Force obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MeyerFregly2016Force obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_MeyerFregly2016Force(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MeyerFregly2016Force safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.MeyerFregly2016Force_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MeyerFregly2016Force(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.MeyerFregly2016Force_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.MeyerFregly2016Force_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.MeyerFregly2016Force_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MeyerFregly2016Force(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.MeyerFregly2016Force_getConcreteClassName(swigCPtr, this);
  }

  public void setPropertyIndex_socket_station(SWIGTYPE_p_OpenSim__PropertyIndex value) {
    opensimSimulationJNI.MeyerFregly2016Force_PropertyIndex_socket_station_set(swigCPtr, this, SWIGTYPE_p_OpenSim__PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_OpenSim__PropertyIndex getPropertyIndex_socket_station() {
    return new SWIGTYPE_p_OpenSim__PropertyIndex(opensimSimulationJNI.MeyerFregly2016Force_PropertyIndex_socket_station_get(swigCPtr, this), true);
  }

  public void connectSocket_station(OpenSimObject object) {
    opensimSimulationJNI.MeyerFregly2016Force_connectSocket_station(swigCPtr, this, OpenSimObject.getCPtr(object), object);
  }

  public void copyProperty_stiffness(MeyerFregly2016Force source) {
    opensimSimulationJNI.MeyerFregly2016Force_copyProperty_stiffness(swigCPtr, this, MeyerFregly2016Force.getCPtr(source), source);
  }

  public double get_stiffness(int i) {
    return opensimSimulationJNI.MeyerFregly2016Force_get_stiffness__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_stiffness(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.MeyerFregly2016Force_upd_stiffness__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_stiffness(int i, double value) {
    opensimSimulationJNI.MeyerFregly2016Force_set_stiffness__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_stiffness(double value) {
    return opensimSimulationJNI.MeyerFregly2016Force_append_stiffness(swigCPtr, this, value);
  }

  public void constructProperty_stiffness(double initValue) {
    opensimSimulationJNI.MeyerFregly2016Force_constructProperty_stiffness(swigCPtr, this, initValue);
  }

  public double get_stiffness() {
    return opensimSimulationJNI.MeyerFregly2016Force_get_stiffness__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_stiffness() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.MeyerFregly2016Force_upd_stiffness__SWIG_1(swigCPtr, this), false);
  }

  public void set_stiffness(double value) {
    opensimSimulationJNI.MeyerFregly2016Force_set_stiffness__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_dissipation(MeyerFregly2016Force source) {
    opensimSimulationJNI.MeyerFregly2016Force_copyProperty_dissipation(swigCPtr, this, MeyerFregly2016Force.getCPtr(source), source);
  }

  public double get_dissipation(int i) {
    return opensimSimulationJNI.MeyerFregly2016Force_get_dissipation__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_dissipation(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.MeyerFregly2016Force_upd_dissipation__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_dissipation(int i, double value) {
    opensimSimulationJNI.MeyerFregly2016Force_set_dissipation__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_dissipation(double value) {
    return opensimSimulationJNI.MeyerFregly2016Force_append_dissipation(swigCPtr, this, value);
  }

  public void constructProperty_dissipation(double initValue) {
    opensimSimulationJNI.MeyerFregly2016Force_constructProperty_dissipation(swigCPtr, this, initValue);
  }

  public double get_dissipation() {
    return opensimSimulationJNI.MeyerFregly2016Force_get_dissipation__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_dissipation() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.MeyerFregly2016Force_upd_dissipation__SWIG_1(swigCPtr, this), false);
  }

  public void set_dissipation(double value) {
    opensimSimulationJNI.MeyerFregly2016Force_set_dissipation__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_spring_resting_length(MeyerFregly2016Force source) {
    opensimSimulationJNI.MeyerFregly2016Force_copyProperty_spring_resting_length(swigCPtr, this, MeyerFregly2016Force.getCPtr(source), source);
  }

  public double get_spring_resting_length(int i) {
    return opensimSimulationJNI.MeyerFregly2016Force_get_spring_resting_length__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_spring_resting_length(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.MeyerFregly2016Force_upd_spring_resting_length__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_spring_resting_length(int i, double value) {
    opensimSimulationJNI.MeyerFregly2016Force_set_spring_resting_length__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_spring_resting_length(double value) {
    return opensimSimulationJNI.MeyerFregly2016Force_append_spring_resting_length(swigCPtr, this, value);
  }

  public void constructProperty_spring_resting_length(double initValue) {
    opensimSimulationJNI.MeyerFregly2016Force_constructProperty_spring_resting_length(swigCPtr, this, initValue);
  }

  public double get_spring_resting_length() {
    return opensimSimulationJNI.MeyerFregly2016Force_get_spring_resting_length__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_spring_resting_length() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.MeyerFregly2016Force_upd_spring_resting_length__SWIG_1(swigCPtr, this), false);
  }

  public void set_spring_resting_length(double value) {
    opensimSimulationJNI.MeyerFregly2016Force_set_spring_resting_length__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_dynamic_friction(MeyerFregly2016Force source) {
    opensimSimulationJNI.MeyerFregly2016Force_copyProperty_dynamic_friction(swigCPtr, this, MeyerFregly2016Force.getCPtr(source), source);
  }

  public double get_dynamic_friction(int i) {
    return opensimSimulationJNI.MeyerFregly2016Force_get_dynamic_friction__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_dynamic_friction(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.MeyerFregly2016Force_upd_dynamic_friction__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_dynamic_friction(int i, double value) {
    opensimSimulationJNI.MeyerFregly2016Force_set_dynamic_friction__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_dynamic_friction(double value) {
    return opensimSimulationJNI.MeyerFregly2016Force_append_dynamic_friction(swigCPtr, this, value);
  }

  public void constructProperty_dynamic_friction(double initValue) {
    opensimSimulationJNI.MeyerFregly2016Force_constructProperty_dynamic_friction(swigCPtr, this, initValue);
  }

  public double get_dynamic_friction() {
    return opensimSimulationJNI.MeyerFregly2016Force_get_dynamic_friction__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_dynamic_friction() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.MeyerFregly2016Force_upd_dynamic_friction__SWIG_1(swigCPtr, this), false);
  }

  public void set_dynamic_friction(double value) {
    opensimSimulationJNI.MeyerFregly2016Force_set_dynamic_friction__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_viscous_friction(MeyerFregly2016Force source) {
    opensimSimulationJNI.MeyerFregly2016Force_copyProperty_viscous_friction(swigCPtr, this, MeyerFregly2016Force.getCPtr(source), source);
  }

  public double get_viscous_friction(int i) {
    return opensimSimulationJNI.MeyerFregly2016Force_get_viscous_friction__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_viscous_friction(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.MeyerFregly2016Force_upd_viscous_friction__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_viscous_friction(int i, double value) {
    opensimSimulationJNI.MeyerFregly2016Force_set_viscous_friction__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_viscous_friction(double value) {
    return opensimSimulationJNI.MeyerFregly2016Force_append_viscous_friction(swigCPtr, this, value);
  }

  public void constructProperty_viscous_friction(double initValue) {
    opensimSimulationJNI.MeyerFregly2016Force_constructProperty_viscous_friction(swigCPtr, this, initValue);
  }

  public double get_viscous_friction() {
    return opensimSimulationJNI.MeyerFregly2016Force_get_viscous_friction__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_viscous_friction() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.MeyerFregly2016Force_upd_viscous_friction__SWIG_1(swigCPtr, this), false);
  }

  public void set_viscous_friction(double value) {
    opensimSimulationJNI.MeyerFregly2016Force_set_viscous_friction__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_latch_velocity(MeyerFregly2016Force source) {
    opensimSimulationJNI.MeyerFregly2016Force_copyProperty_latch_velocity(swigCPtr, this, MeyerFregly2016Force.getCPtr(source), source);
  }

  public double get_latch_velocity(int i) {
    return opensimSimulationJNI.MeyerFregly2016Force_get_latch_velocity__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_latch_velocity(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.MeyerFregly2016Force_upd_latch_velocity__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_latch_velocity(int i, double value) {
    opensimSimulationJNI.MeyerFregly2016Force_set_latch_velocity__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_latch_velocity(double value) {
    return opensimSimulationJNI.MeyerFregly2016Force_append_latch_velocity(swigCPtr, this, value);
  }

  public void constructProperty_latch_velocity(double initValue) {
    opensimSimulationJNI.MeyerFregly2016Force_constructProperty_latch_velocity(swigCPtr, this, initValue);
  }

  public double get_latch_velocity() {
    return opensimSimulationJNI.MeyerFregly2016Force_get_latch_velocity__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_latch_velocity() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.MeyerFregly2016Force_upd_latch_velocity__SWIG_1(swigCPtr, this), false);
  }

  public void set_latch_velocity(double value) {
    opensimSimulationJNI.MeyerFregly2016Force_set_latch_velocity__SWIG_1(swigCPtr, this, value);
  }

  public void set_has_output_force_on_station(boolean value) {
    opensimSimulationJNI.MeyerFregly2016Force__has_output_force_on_station_set(swigCPtr, this, value);
  }

  public boolean get_has_output_force_on_station() {
    return opensimSimulationJNI.MeyerFregly2016Force__has_output_force_on_station_get(swigCPtr, this);
  }

  public MeyerFregly2016Force() {
    this(opensimSimulationJNI.new_MeyerFregly2016Force(), true);
  }

  public Vec3 getContactForceOnStation(State s) {
    return new Vec3(opensimSimulationJNI.MeyerFregly2016Force_getContactForceOnStation(swigCPtr, this, State.getCPtr(s), s), true);
  }

  public void setContactForceOnStation(State s, Vec3 force) {
    opensimSimulationJNI.MeyerFregly2016Force_setContactForceOnStation(swigCPtr, this, State.getCPtr(s), s, Vec3.getCPtr(force), force);
  }

  public ArrayStr getRecordLabels() {
    return new ArrayStr(opensimSimulationJNI.MeyerFregly2016Force_getRecordLabels(swigCPtr, this), true);
  }

  public ArrayDouble getRecordValues(State s) {
    return new ArrayDouble(opensimSimulationJNI.MeyerFregly2016Force_getRecordValues(swigCPtr, this, State.getCPtr(s), s), true);
  }

}
