/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class Millard2012EquilibriumMuscleList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Millard2012EquilibriumMuscleList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Millard2012EquilibriumMuscleList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(Millard2012EquilibriumMuscleList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_Millard2012EquilibriumMuscleList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Millard2012EquilibriumMuscleList(Component root, ComponentFilter f) {
    this(opensimSimulationJNI.new_Millard2012EquilibriumMuscleList__SWIG_0(Component.getCPtr(root), root, ComponentFilter.getCPtr(f), f), true);
  }

  public Millard2012EquilibriumMuscleList(Component root) {
    this(opensimSimulationJNI.new_Millard2012EquilibriumMuscleList__SWIG_1(Component.getCPtr(root), root), true);
  }

  public Millard2012EquilibriumMuscleIterator begin() {
    return new Millard2012EquilibriumMuscleIterator(opensimSimulationJNI.Millard2012EquilibriumMuscleList_begin__SWIG_0(swigCPtr, this), true);
  }

  public SWIGTYPE_p_OpenSim__ComponentListIteratorT_std__add_constT_OpenSim__Millard2012EquilibriumMuscle_const_t__type_t cbegin() {
    return new SWIGTYPE_p_OpenSim__ComponentListIteratorT_std__add_constT_OpenSim__Millard2012EquilibriumMuscle_const_t__type_t(opensimSimulationJNI.Millard2012EquilibriumMuscleList_cbegin(swigCPtr, this), true);
  }

  public Millard2012EquilibriumMuscleIterator end() {
    return new Millard2012EquilibriumMuscleIterator(opensimSimulationJNI.Millard2012EquilibriumMuscleList_end__SWIG_0(swigCPtr, this), true);
  }

  public SWIGTYPE_p_OpenSim__ComponentListIteratorT_std__add_constT_OpenSim__Millard2012EquilibriumMuscle_const_t__type_t cend() {
    return new SWIGTYPE_p_OpenSim__ComponentListIteratorT_std__add_constT_OpenSim__Millard2012EquilibriumMuscle_const_t__type_t(opensimSimulationJNI.Millard2012EquilibriumMuscleList_cend(swigCPtr, this), true);
  }

  public void setFilter(ComponentFilter filter) {
    opensimSimulationJNI.Millard2012EquilibriumMuscleList_setFilter(swigCPtr, this, ComponentFilter.getCPtr(filter), filter);
  }

}
