/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoCasADiSolver extends MocoDirectCollocationSolver {
  private transient long swigCPtr;

  public MocoCasADiSolver(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoCasADiSolver_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoCasADiSolver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoCasADiSolver obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoCasADiSolver(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MocoCasADiSolver safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoCasADiSolver_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoCasADiSolver(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoCasADiSolver_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoCasADiSolver_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoCasADiSolver_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoCasADiSolver(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoCasADiSolver_getConcreteClassName(swigCPtr, this);
  }

  public void copyProperty_scale_variables_using_bounds(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_scale_variables_using_bounds(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public boolean get_scale_variables_using_bounds(int i) {
    return opensimMocoJNI.MocoCasADiSolver_get_scale_variables_using_bounds__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_scale_variables_using_bounds(int i) {
    return new SWIGTYPE_p_bool(opensimMocoJNI.MocoCasADiSolver_upd_scale_variables_using_bounds__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_scale_variables_using_bounds(int i, boolean value) {
    opensimMocoJNI.MocoCasADiSolver_set_scale_variables_using_bounds__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_scale_variables_using_bounds(boolean value) {
    return opensimMocoJNI.MocoCasADiSolver_append_scale_variables_using_bounds(swigCPtr, this, value);
  }

  public void constructProperty_scale_variables_using_bounds(boolean initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_scale_variables_using_bounds(swigCPtr, this, initValue);
  }

  public boolean get_scale_variables_using_bounds() {
    return opensimMocoJNI.MocoCasADiSolver_get_scale_variables_using_bounds__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_scale_variables_using_bounds() {
    return new SWIGTYPE_p_bool(opensimMocoJNI.MocoCasADiSolver_upd_scale_variables_using_bounds__SWIG_1(swigCPtr, this), false);
  }

  public void set_scale_variables_using_bounds(boolean value) {
    opensimMocoJNI.MocoCasADiSolver_set_scale_variables_using_bounds__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_parameters_require_initsystem(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_parameters_require_initsystem(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public boolean get_parameters_require_initsystem(int i) {
    return opensimMocoJNI.MocoCasADiSolver_get_parameters_require_initsystem__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_parameters_require_initsystem(int i) {
    return new SWIGTYPE_p_bool(opensimMocoJNI.MocoCasADiSolver_upd_parameters_require_initsystem__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_parameters_require_initsystem(int i, boolean value) {
    opensimMocoJNI.MocoCasADiSolver_set_parameters_require_initsystem__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_parameters_require_initsystem(boolean value) {
    return opensimMocoJNI.MocoCasADiSolver_append_parameters_require_initsystem(swigCPtr, this, value);
  }

  public void constructProperty_parameters_require_initsystem(boolean initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_parameters_require_initsystem(swigCPtr, this, initValue);
  }

  public boolean get_parameters_require_initsystem() {
    return opensimMocoJNI.MocoCasADiSolver_get_parameters_require_initsystem__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_parameters_require_initsystem() {
    return new SWIGTYPE_p_bool(opensimMocoJNI.MocoCasADiSolver_upd_parameters_require_initsystem__SWIG_1(swigCPtr, this), false);
  }

  public void set_parameters_require_initsystem(boolean value) {
    opensimMocoJNI.MocoCasADiSolver_set_parameters_require_initsystem__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_optim_sparsity_detection(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_optim_sparsity_detection(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public String get_optim_sparsity_detection(int i) {
    return opensimMocoJNI.MocoCasADiSolver_get_optim_sparsity_detection__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_optim_sparsity_detection(int i) {
    return new SWIGTYPE_p_std__string(opensimMocoJNI.MocoCasADiSolver_upd_optim_sparsity_detection__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_optim_sparsity_detection(int i, String value) {
    opensimMocoJNI.MocoCasADiSolver_set_optim_sparsity_detection__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_optim_sparsity_detection(String value) {
    return opensimMocoJNI.MocoCasADiSolver_append_optim_sparsity_detection(swigCPtr, this, value);
  }

  public void constructProperty_optim_sparsity_detection(String initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_optim_sparsity_detection(swigCPtr, this, initValue);
  }

  public String get_optim_sparsity_detection() {
    return opensimMocoJNI.MocoCasADiSolver_get_optim_sparsity_detection__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_optim_sparsity_detection() {
    return new SWIGTYPE_p_std__string(opensimMocoJNI.MocoCasADiSolver_upd_optim_sparsity_detection__SWIG_1(swigCPtr, this), false);
  }

  public void set_optim_sparsity_detection(String value) {
    opensimMocoJNI.MocoCasADiSolver_set_optim_sparsity_detection__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_optim_write_sparsity(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_optim_write_sparsity(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public String get_optim_write_sparsity(int i) {
    return opensimMocoJNI.MocoCasADiSolver_get_optim_write_sparsity__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_optim_write_sparsity(int i) {
    return new SWIGTYPE_p_std__string(opensimMocoJNI.MocoCasADiSolver_upd_optim_write_sparsity__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_optim_write_sparsity(int i, String value) {
    opensimMocoJNI.MocoCasADiSolver_set_optim_write_sparsity__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_optim_write_sparsity(String value) {
    return opensimMocoJNI.MocoCasADiSolver_append_optim_write_sparsity(swigCPtr, this, value);
  }

  public void constructProperty_optim_write_sparsity(String initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_optim_write_sparsity(swigCPtr, this, initValue);
  }

  public String get_optim_write_sparsity() {
    return opensimMocoJNI.MocoCasADiSolver_get_optim_write_sparsity__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_optim_write_sparsity() {
    return new SWIGTYPE_p_std__string(opensimMocoJNI.MocoCasADiSolver_upd_optim_write_sparsity__SWIG_1(swigCPtr, this), false);
  }

  public void set_optim_write_sparsity(String value) {
    opensimMocoJNI.MocoCasADiSolver_set_optim_write_sparsity__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_optim_finite_difference_scheme(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_optim_finite_difference_scheme(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public String get_optim_finite_difference_scheme(int i) {
    return opensimMocoJNI.MocoCasADiSolver_get_optim_finite_difference_scheme__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_optim_finite_difference_scheme(int i) {
    return new SWIGTYPE_p_std__string(opensimMocoJNI.MocoCasADiSolver_upd_optim_finite_difference_scheme__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_optim_finite_difference_scheme(int i, String value) {
    opensimMocoJNI.MocoCasADiSolver_set_optim_finite_difference_scheme__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_optim_finite_difference_scheme(String value) {
    return opensimMocoJNI.MocoCasADiSolver_append_optim_finite_difference_scheme(swigCPtr, this, value);
  }

  public void constructProperty_optim_finite_difference_scheme(String initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_optim_finite_difference_scheme(swigCPtr, this, initValue);
  }

  public String get_optim_finite_difference_scheme() {
    return opensimMocoJNI.MocoCasADiSolver_get_optim_finite_difference_scheme__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_optim_finite_difference_scheme() {
    return new SWIGTYPE_p_std__string(opensimMocoJNI.MocoCasADiSolver_upd_optim_finite_difference_scheme__SWIG_1(swigCPtr, this), false);
  }

  public void set_optim_finite_difference_scheme(String value) {
    opensimMocoJNI.MocoCasADiSolver_set_optim_finite_difference_scheme__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_parallel(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_parallel(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public int get_parallel(int i) {
    return opensimMocoJNI.MocoCasADiSolver_get_parallel__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_int upd_parallel(int i) {
    return new SWIGTYPE_p_int(opensimMocoJNI.MocoCasADiSolver_upd_parallel__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_parallel(int i, int value) {
    opensimMocoJNI.MocoCasADiSolver_set_parallel__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_parallel(int value) {
    return opensimMocoJNI.MocoCasADiSolver_append_parallel(swigCPtr, this, value);
  }

  public void constructProperty_parallel() {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_parallel__SWIG_0(swigCPtr, this);
  }

  public void constructProperty_parallel(int initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_parallel__SWIG_1(swigCPtr, this, initValue);
  }

  public int get_parallel() {
    return opensimMocoJNI.MocoCasADiSolver_get_parallel__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_int upd_parallel() {
    return new SWIGTYPE_p_int(opensimMocoJNI.MocoCasADiSolver_upd_parallel__SWIG_1(swigCPtr, this), false);
  }

  public void set_parallel(int value) {
    opensimMocoJNI.MocoCasADiSolver_set_parallel__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_output_interval(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_output_interval(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public int get_output_interval(int i) {
    return opensimMocoJNI.MocoCasADiSolver_get_output_interval__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_int upd_output_interval(int i) {
    return new SWIGTYPE_p_int(opensimMocoJNI.MocoCasADiSolver_upd_output_interval__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_output_interval(int i, int value) {
    opensimMocoJNI.MocoCasADiSolver_set_output_interval__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_output_interval(int value) {
    return opensimMocoJNI.MocoCasADiSolver_append_output_interval(swigCPtr, this, value);
  }

  public void constructProperty_output_interval(int initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_output_interval(swigCPtr, this, initValue);
  }

  public int get_output_interval() {
    return opensimMocoJNI.MocoCasADiSolver_get_output_interval__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_int upd_output_interval() {
    return new SWIGTYPE_p_int(opensimMocoJNI.MocoCasADiSolver_upd_output_interval__SWIG_1(swigCPtr, this), false);
  }

  public void set_output_interval(int value) {
    opensimMocoJNI.MocoCasADiSolver_set_output_interval__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_minimize_implicit_multibody_accelerations(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_minimize_implicit_multibody_accelerations(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public boolean get_minimize_implicit_multibody_accelerations(int i) {
    return opensimMocoJNI.MocoCasADiSolver_get_minimize_implicit_multibody_accelerations__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_minimize_implicit_multibody_accelerations(int i) {
    return new SWIGTYPE_p_bool(opensimMocoJNI.MocoCasADiSolver_upd_minimize_implicit_multibody_accelerations__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_minimize_implicit_multibody_accelerations(int i, boolean value) {
    opensimMocoJNI.MocoCasADiSolver_set_minimize_implicit_multibody_accelerations__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_minimize_implicit_multibody_accelerations(boolean value) {
    return opensimMocoJNI.MocoCasADiSolver_append_minimize_implicit_multibody_accelerations(swigCPtr, this, value);
  }

  public void constructProperty_minimize_implicit_multibody_accelerations(boolean initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_minimize_implicit_multibody_accelerations(swigCPtr, this, initValue);
  }

  public boolean get_minimize_implicit_multibody_accelerations() {
    return opensimMocoJNI.MocoCasADiSolver_get_minimize_implicit_multibody_accelerations__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_minimize_implicit_multibody_accelerations() {
    return new SWIGTYPE_p_bool(opensimMocoJNI.MocoCasADiSolver_upd_minimize_implicit_multibody_accelerations__SWIG_1(swigCPtr, this), false);
  }

  public void set_minimize_implicit_multibody_accelerations(boolean value) {
    opensimMocoJNI.MocoCasADiSolver_set_minimize_implicit_multibody_accelerations__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_implicit_multibody_accelerations_weight(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_implicit_multibody_accelerations_weight(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public double get_implicit_multibody_accelerations_weight(int i) {
    return opensimMocoJNI.MocoCasADiSolver_get_implicit_multibody_accelerations_weight__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_implicit_multibody_accelerations_weight(int i) {
    return new SWIGTYPE_p_double(opensimMocoJNI.MocoCasADiSolver_upd_implicit_multibody_accelerations_weight__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_implicit_multibody_accelerations_weight(int i, double value) {
    opensimMocoJNI.MocoCasADiSolver_set_implicit_multibody_accelerations_weight__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_implicit_multibody_accelerations_weight(double value) {
    return opensimMocoJNI.MocoCasADiSolver_append_implicit_multibody_accelerations_weight(swigCPtr, this, value);
  }

  public void constructProperty_implicit_multibody_accelerations_weight(double initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_implicit_multibody_accelerations_weight(swigCPtr, this, initValue);
  }

  public double get_implicit_multibody_accelerations_weight() {
    return opensimMocoJNI.MocoCasADiSolver_get_implicit_multibody_accelerations_weight__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_implicit_multibody_accelerations_weight() {
    return new SWIGTYPE_p_double(opensimMocoJNI.MocoCasADiSolver_upd_implicit_multibody_accelerations_weight__SWIG_1(swigCPtr, this), false);
  }

  public void set_implicit_multibody_accelerations_weight(double value) {
    opensimMocoJNI.MocoCasADiSolver_set_implicit_multibody_accelerations_weight__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_minimize_implicit_auxiliary_derivatives(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_minimize_implicit_auxiliary_derivatives(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public boolean get_minimize_implicit_auxiliary_derivatives(int i) {
    return opensimMocoJNI.MocoCasADiSolver_get_minimize_implicit_auxiliary_derivatives__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_minimize_implicit_auxiliary_derivatives(int i) {
    return new SWIGTYPE_p_bool(opensimMocoJNI.MocoCasADiSolver_upd_minimize_implicit_auxiliary_derivatives__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_minimize_implicit_auxiliary_derivatives(int i, boolean value) {
    opensimMocoJNI.MocoCasADiSolver_set_minimize_implicit_auxiliary_derivatives__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_minimize_implicit_auxiliary_derivatives(boolean value) {
    return opensimMocoJNI.MocoCasADiSolver_append_minimize_implicit_auxiliary_derivatives(swigCPtr, this, value);
  }

  public void constructProperty_minimize_implicit_auxiliary_derivatives(boolean initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_minimize_implicit_auxiliary_derivatives(swigCPtr, this, initValue);
  }

  public boolean get_minimize_implicit_auxiliary_derivatives() {
    return opensimMocoJNI.MocoCasADiSolver_get_minimize_implicit_auxiliary_derivatives__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_minimize_implicit_auxiliary_derivatives() {
    return new SWIGTYPE_p_bool(opensimMocoJNI.MocoCasADiSolver_upd_minimize_implicit_auxiliary_derivatives__SWIG_1(swigCPtr, this), false);
  }

  public void set_minimize_implicit_auxiliary_derivatives(boolean value) {
    opensimMocoJNI.MocoCasADiSolver_set_minimize_implicit_auxiliary_derivatives__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_implicit_auxiliary_derivatives_weight(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_implicit_auxiliary_derivatives_weight(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public double get_implicit_auxiliary_derivatives_weight(int i) {
    return opensimMocoJNI.MocoCasADiSolver_get_implicit_auxiliary_derivatives_weight__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_implicit_auxiliary_derivatives_weight(int i) {
    return new SWIGTYPE_p_double(opensimMocoJNI.MocoCasADiSolver_upd_implicit_auxiliary_derivatives_weight__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_implicit_auxiliary_derivatives_weight(int i, double value) {
    opensimMocoJNI.MocoCasADiSolver_set_implicit_auxiliary_derivatives_weight__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_implicit_auxiliary_derivatives_weight(double value) {
    return opensimMocoJNI.MocoCasADiSolver_append_implicit_auxiliary_derivatives_weight(swigCPtr, this, value);
  }

  public void constructProperty_implicit_auxiliary_derivatives_weight(double initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_implicit_auxiliary_derivatives_weight(swigCPtr, this, initValue);
  }

  public double get_implicit_auxiliary_derivatives_weight() {
    return opensimMocoJNI.MocoCasADiSolver_get_implicit_auxiliary_derivatives_weight__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_implicit_auxiliary_derivatives_weight() {
    return new SWIGTYPE_p_double(opensimMocoJNI.MocoCasADiSolver_upd_implicit_auxiliary_derivatives_weight__SWIG_1(swigCPtr, this), false);
  }

  public void set_implicit_auxiliary_derivatives_weight(double value) {
    opensimMocoJNI.MocoCasADiSolver_set_implicit_auxiliary_derivatives_weight__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_enforce_path_constraint_mesh_interior_points(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_enforce_path_constraint_mesh_interior_points(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public boolean get_enforce_path_constraint_mesh_interior_points(int i) {
    return opensimMocoJNI.MocoCasADiSolver_get_enforce_path_constraint_mesh_interior_points__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_enforce_path_constraint_mesh_interior_points(int i) {
    return new SWIGTYPE_p_bool(opensimMocoJNI.MocoCasADiSolver_upd_enforce_path_constraint_mesh_interior_points__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_enforce_path_constraint_mesh_interior_points(int i, boolean value) {
    opensimMocoJNI.MocoCasADiSolver_set_enforce_path_constraint_mesh_interior_points__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_enforce_path_constraint_mesh_interior_points(boolean value) {
    return opensimMocoJNI.MocoCasADiSolver_append_enforce_path_constraint_mesh_interior_points(swigCPtr, this, value);
  }

  public void constructProperty_enforce_path_constraint_mesh_interior_points(boolean initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_enforce_path_constraint_mesh_interior_points(swigCPtr, this, initValue);
  }

  public boolean get_enforce_path_constraint_mesh_interior_points() {
    return opensimMocoJNI.MocoCasADiSolver_get_enforce_path_constraint_mesh_interior_points__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_enforce_path_constraint_mesh_interior_points() {
    return new SWIGTYPE_p_bool(opensimMocoJNI.MocoCasADiSolver_upd_enforce_path_constraint_mesh_interior_points__SWIG_1(swigCPtr, this), false);
  }

  public void set_enforce_path_constraint_mesh_interior_points(boolean value) {
    opensimMocoJNI.MocoCasADiSolver_set_enforce_path_constraint_mesh_interior_points__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_minimize_state_projection_distance(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_minimize_state_projection_distance(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public boolean get_minimize_state_projection_distance(int i) {
    return opensimMocoJNI.MocoCasADiSolver_get_minimize_state_projection_distance__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_bool upd_minimize_state_projection_distance(int i) {
    return new SWIGTYPE_p_bool(opensimMocoJNI.MocoCasADiSolver_upd_minimize_state_projection_distance__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_minimize_state_projection_distance(int i, boolean value) {
    opensimMocoJNI.MocoCasADiSolver_set_minimize_state_projection_distance__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_minimize_state_projection_distance(boolean value) {
    return opensimMocoJNI.MocoCasADiSolver_append_minimize_state_projection_distance(swigCPtr, this, value);
  }

  public void constructProperty_minimize_state_projection_distance(boolean initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_minimize_state_projection_distance(swigCPtr, this, initValue);
  }

  public boolean get_minimize_state_projection_distance() {
    return opensimMocoJNI.MocoCasADiSolver_get_minimize_state_projection_distance__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool upd_minimize_state_projection_distance() {
    return new SWIGTYPE_p_bool(opensimMocoJNI.MocoCasADiSolver_upd_minimize_state_projection_distance__SWIG_1(swigCPtr, this), false);
  }

  public void set_minimize_state_projection_distance(boolean value) {
    opensimMocoJNI.MocoCasADiSolver_set_minimize_state_projection_distance__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_state_projection_distance_weight(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_state_projection_distance_weight(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public double get_state_projection_distance_weight(int i) {
    return opensimMocoJNI.MocoCasADiSolver_get_state_projection_distance_weight__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_state_projection_distance_weight(int i) {
    return new SWIGTYPE_p_double(opensimMocoJNI.MocoCasADiSolver_upd_state_projection_distance_weight__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_state_projection_distance_weight(int i, double value) {
    opensimMocoJNI.MocoCasADiSolver_set_state_projection_distance_weight__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_state_projection_distance_weight(double value) {
    return opensimMocoJNI.MocoCasADiSolver_append_state_projection_distance_weight(swigCPtr, this, value);
  }

  public void constructProperty_state_projection_distance_weight(double initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_state_projection_distance_weight(swigCPtr, this, initValue);
  }

  public double get_state_projection_distance_weight() {
    return opensimMocoJNI.MocoCasADiSolver_get_state_projection_distance_weight__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_state_projection_distance_weight() {
    return new SWIGTYPE_p_double(opensimMocoJNI.MocoCasADiSolver_upd_state_projection_distance_weight__SWIG_1(swigCPtr, this), false);
  }

  public void set_state_projection_distance_weight(double value) {
    opensimMocoJNI.MocoCasADiSolver_set_state_projection_distance_weight__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_projection_slack_variable_bounds(MocoCasADiSolver source) {
    opensimMocoJNI.MocoCasADiSolver_copyProperty_projection_slack_variable_bounds(swigCPtr, this, MocoCasADiSolver.getCPtr(source), source);
  }

  public MocoBounds get_projection_slack_variable_bounds(int i) {
    return new MocoBounds(opensimMocoJNI.MocoCasADiSolver_get_projection_slack_variable_bounds__SWIG_0(swigCPtr, this, i), false);
  }

  public MocoBounds upd_projection_slack_variable_bounds(int i) {
    return new MocoBounds(opensimMocoJNI.MocoCasADiSolver_upd_projection_slack_variable_bounds__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_projection_slack_variable_bounds(int i, MocoBounds value) {
    opensimMocoJNI.MocoCasADiSolver_set_projection_slack_variable_bounds__SWIG_0(swigCPtr, this, i, MocoBounds.getCPtr(value), value);
  }

  public int append_projection_slack_variable_bounds(MocoBounds value) {
    return opensimMocoJNI.MocoCasADiSolver_append_projection_slack_variable_bounds(swigCPtr, this, MocoBounds.getCPtr(value), value);
  }

  public void constructProperty_projection_slack_variable_bounds(MocoBounds initValue) {
    opensimMocoJNI.MocoCasADiSolver_constructProperty_projection_slack_variable_bounds(swigCPtr, this, MocoBounds.getCPtr(initValue), initValue);
  }

  public MocoBounds get_projection_slack_variable_bounds() {
    return new MocoBounds(opensimMocoJNI.MocoCasADiSolver_get_projection_slack_variable_bounds__SWIG_1(swigCPtr, this), false);
  }

  public MocoBounds upd_projection_slack_variable_bounds() {
    return new MocoBounds(opensimMocoJNI.MocoCasADiSolver_upd_projection_slack_variable_bounds__SWIG_1(swigCPtr, this), false);
  }

  public void set_projection_slack_variable_bounds(MocoBounds value) {
    opensimMocoJNI.MocoCasADiSolver_set_projection_slack_variable_bounds__SWIG_1(swigCPtr, this, MocoBounds.getCPtr(value), value);
  }

  public MocoCasADiSolver() {
    this(opensimMocoJNI.new_MocoCasADiSolver(), true);
  }

  public static boolean isAvailable() {
    return opensimMocoJNI.MocoCasADiSolver_isAvailable();
  }

  public MocoTrajectory createGuess(String type) {
    return new MocoTrajectory(opensimMocoJNI.MocoCasADiSolver_createGuess__SWIG_0(swigCPtr, this, type), true);
  }

  public MocoTrajectory createGuess() {
    return new MocoTrajectory(opensimMocoJNI.MocoCasADiSolver_createGuess__SWIG_1(swigCPtr, this), true);
  }

  public void setGuess(MocoTrajectory guess) {
    opensimMocoJNI.MocoCasADiSolver_setGuess__SWIG_0(swigCPtr, this, MocoTrajectory.getCPtr(guess), guess);
  }

  public void setGuess(String type) {
    opensimMocoJNI.MocoCasADiSolver_setGuess__SWIG_1(swigCPtr, this, type);
  }

  public void setGuessFile(String file) {
    opensimMocoJNI.MocoCasADiSolver_setGuessFile(swigCPtr, this, file);
  }

  public void clearGuess() {
    opensimMocoJNI.MocoCasADiSolver_clearGuess(swigCPtr, this);
  }

  public MocoTrajectory getGuess() {
    return new MocoTrajectory(opensimMocoJNI.MocoCasADiSolver_getGuess(swigCPtr, this), false);
  }

}
