/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoConstraintInfo extends OpenSimObject {
  private transient long swigCPtr;

  public MocoConstraintInfo(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoConstraintInfo_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoConstraintInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoConstraintInfo obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoConstraintInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MocoConstraintInfo safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoConstraintInfo_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoConstraintInfo(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoConstraintInfo_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoConstraintInfo_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoConstraintInfo_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoConstraintInfo(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoConstraintInfo_getConcreteClassName(swigCPtr, this);
  }

  public MocoConstraintInfo() {
    this(opensimMocoJNI.new_MocoConstraintInfo(), true);
  }

  public int getNumEquations() {
    return opensimMocoJNI.MocoConstraintInfo_getNumEquations(swigCPtr, this);
  }

  public StdVectorMocoBounds getBounds() {
    return new StdVectorMocoBounds(opensimMocoJNI.MocoConstraintInfo_getBounds(swigCPtr, this), true);
  }

  public StdVectorString getSuffixes() {
    return new StdVectorString(opensimMocoJNI.MocoConstraintInfo_getSuffixes(swigCPtr, this), true);
  }

  public void setBounds(StdVectorMocoBounds bounds) {
    opensimMocoJNI.MocoConstraintInfo_setBounds(swigCPtr, this, StdVectorMocoBounds.getCPtr(bounds), bounds);
  }

  public void setSuffixes(StdVectorString suffixes) {
    opensimMocoJNI.MocoConstraintInfo_setSuffixes(swigCPtr, this, StdVectorString.getCPtr(suffixes), suffixes);
  }

  public StdVectorString getConstraintLabels() {
    return new StdVectorString(opensimMocoJNI.MocoConstraintInfo_getConstraintLabels(swigCPtr, this), true);
  }

  public void printDescription() {
    opensimMocoJNI.MocoConstraintInfo_printDescription(swigCPtr, this);
  }

}
