/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoInitialOutputGoal extends MocoOutputBase {
  private transient long swigCPtr;

  public MocoInitialOutputGoal(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoInitialOutputGoal_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoInitialOutputGoal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoInitialOutputGoal obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoInitialOutputGoal(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MocoInitialOutputGoal safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoInitialOutputGoal_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoInitialOutputGoal(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoInitialOutputGoal_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoInitialOutputGoal_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoInitialOutputGoal_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoInitialOutputGoal(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoInitialOutputGoal_getConcreteClassName(swigCPtr, this);
  }

  public MocoInitialOutputGoal() {
    this(opensimMocoJNI.new_MocoInitialOutputGoal__SWIG_0(), true);
  }

  public MocoInitialOutputGoal(String name) {
    this(opensimMocoJNI.new_MocoInitialOutputGoal__SWIG_1(name), true);
  }

  public MocoInitialOutputGoal(String name, double weight) {
    this(opensimMocoJNI.new_MocoInitialOutputGoal__SWIG_2(name, weight), true);
  }

}
