/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoMarkerTrackingGoal extends MocoGoal {
  private transient long swigCPtr;

  public MocoMarkerTrackingGoal(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoMarkerTrackingGoal_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoMarkerTrackingGoal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoMarkerTrackingGoal obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoMarkerTrackingGoal(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

    public void addScaleFactor(String name, String marker, int index, double[] b)
            throws Exception {
            addScaleFactor(name, marker, index, MocoPhase.convertArrayToMB(b));
    }

  public static MocoMarkerTrackingGoal safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoMarkerTrackingGoal_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoMarkerTrackingGoal(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoMarkerTrackingGoal_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoMarkerTrackingGoal_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoMarkerTrackingGoal_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoMarkerTrackingGoal(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoMarkerTrackingGoal_getConcreteClassName(swigCPtr, this);
  }

  public MocoMarkerTrackingGoal() {
    this(opensimMocoJNI.new_MocoMarkerTrackingGoal__SWIG_0(), true);
  }

  public MocoMarkerTrackingGoal(String name) {
    this(opensimMocoJNI.new_MocoMarkerTrackingGoal__SWIG_1(name), true);
  }

  public MocoMarkerTrackingGoal(String name, double weight) {
    this(opensimMocoJNI.new_MocoMarkerTrackingGoal__SWIG_2(name, weight), true);
  }

  public void setMarkersReference(MarkersReference arg0) {
    opensimMocoJNI.MocoMarkerTrackingGoal_setMarkersReference(swigCPtr, this, MarkersReference.getCPtr(arg0), arg0);
  }

  public MarkersReference getMarkersReference() {
    return new MarkersReference(opensimMocoJNI.MocoMarkerTrackingGoal_getMarkersReference(swigCPtr, this), true);
  }

  public void setAllowUnusedReferences(boolean tf) {
    opensimMocoJNI.MocoMarkerTrackingGoal_setAllowUnusedReferences(swigCPtr, this, tf);
  }

  public void addScaleFactor(String name, String marker, int index, MocoBounds bounds) {
    opensimMocoJNI.MocoMarkerTrackingGoal_addScaleFactor(swigCPtr, this, name, marker, index, MocoBounds.getCPtr(bounds), bounds);
  }

}
