/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoOutputTrackingGoal extends MocoOutputBase {
  private transient long swigCPtr;

  public MocoOutputTrackingGoal(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoOutputTrackingGoal_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoOutputTrackingGoal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoOutputTrackingGoal obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoOutputTrackingGoal(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MocoOutputTrackingGoal safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoOutputTrackingGoal_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoOutputTrackingGoal(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoOutputTrackingGoal_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoOutputTrackingGoal_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoOutputTrackingGoal_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoOutputTrackingGoal(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoOutputTrackingGoal_getConcreteClassName(swigCPtr, this);
  }

  public MocoOutputTrackingGoal() {
    this(opensimMocoJNI.new_MocoOutputTrackingGoal__SWIG_0(), true);
  }

  public MocoOutputTrackingGoal(String name) {
    this(opensimMocoJNI.new_MocoOutputTrackingGoal__SWIG_1(name), true);
  }

  public MocoOutputTrackingGoal(String name, double weight) {
    this(opensimMocoJNI.new_MocoOutputTrackingGoal__SWIG_2(name, weight), true);
  }

  public void setTrackingFunction(Function f) {
    opensimMocoJNI.MocoOutputTrackingGoal_setTrackingFunction(swigCPtr, this, Function.getCPtr(f), f);
  }

  public Function getTrackingFunction() {
    return new Function(opensimMocoJNI.MocoOutputTrackingGoal_getTrackingFunction(swigCPtr, this), false);
  }

}
