/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoOutputBase extends MocoGoal {
  private transient long swigCPtr;

  public MocoOutputBase(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoOutputBase_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoOutputBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoOutputBase obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoOutputBase(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MocoOutputBase safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoOutputBase_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoOutputBase(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoOutputBase_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoOutputBase_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoOutputBase_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoOutputBase(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoOutputBase_getConcreteClassName(swigCPtr, this);
  }

  public void setOutputPath(String path) {
    opensimMocoJNI.MocoOutputBase_setOutputPath(swigCPtr, this, path);
  }

  public String getOutputPath() {
    return opensimMocoJNI.MocoOutputBase_getOutputPath(swigCPtr, this);
  }

  public void setSecondOutputPath(String path) {
    opensimMocoJNI.MocoOutputBase_setSecondOutputPath(swigCPtr, this, path);
  }

  public String getSecondOutputPath() {
    return opensimMocoJNI.MocoOutputBase_getSecondOutputPath(swigCPtr, this);
  }

  public void setOperation(String operation) {
    opensimMocoJNI.MocoOutputBase_setOperation(swigCPtr, this, operation);
  }

  public String getOperation() {
    return opensimMocoJNI.MocoOutputBase_getOperation(swigCPtr, this);
  }

  public void setExponent(int exponent) {
    opensimMocoJNI.MocoOutputBase_setExponent(swigCPtr, this, exponent);
  }

  public int getExponent() {
    return opensimMocoJNI.MocoOutputBase_getExponent(swigCPtr, this);
  }

  public void setOutputIndex(int index) {
    opensimMocoJNI.MocoOutputBase_setOutputIndex(swigCPtr, this, index);
  }

  public int getOutputIndex() {
    return opensimMocoJNI.MocoOutputBase_getOutputIndex(swigCPtr, this);
  }

}
