/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoGoal extends OpenSimObject {
  private transient long swigCPtr;

  public MocoGoal(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoGoal_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoGoal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoGoal obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoGoal(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MocoGoal safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoGoal_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoGoal(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoGoal_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoGoal_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoGoal_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoGoal(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoGoal_getConcreteClassName(swigCPtr, this);
  }

  public void setEnabled(boolean enabled) {
    opensimMocoJNI.MocoGoal_setEnabled(swigCPtr, this, enabled);
  }

  public boolean getEnabled() {
    return opensimMocoJNI.MocoGoal_getEnabled(swigCPtr, this);
  }

  public void setWeight(double weight) {
    opensimMocoJNI.MocoGoal_setWeight(swigCPtr, this, weight);
  }

  public double getWeight() {
    return opensimMocoJNI.MocoGoal_getWeight(swigCPtr, this);
  }

  public void setMode(String mode) {
    opensimMocoJNI.MocoGoal_setMode(swigCPtr, this, mode);
  }

  public String getModeAsString() {
    return opensimMocoJNI.MocoGoal_getModeAsString(swigCPtr, this);
  }

  public MocoGoal.Mode getMode() {
    return MocoGoal.Mode.swigToEnum(opensimMocoJNI.MocoGoal_getMode(swigCPtr, this));
  }

  public boolean getModeIsCost() {
    return opensimMocoJNI.MocoGoal_getModeIsCost(swigCPtr, this);
  }

  public boolean getModeIsEndpointConstraint() {
    return opensimMocoJNI.MocoGoal_getModeIsEndpointConstraint(swigCPtr, this);
  }

  public MocoGoal.Mode getDefaultMode() {
    return MocoGoal.Mode.swigToEnum(opensimMocoJNI.MocoGoal_getDefaultMode(swigCPtr, this));
  }

  public boolean getSupportsEndpointConstraint() {
    return opensimMocoJNI.MocoGoal_getSupportsEndpointConstraint(swigCPtr, this);
  }

  public SWIGTYPE_p_MocoConstraintInfo getConstraintInfo() {
    return new SWIGTYPE_p_MocoConstraintInfo(opensimMocoJNI.MocoGoal_getConstraintInfo(swigCPtr, this), false);
  }

  public SWIGTYPE_p_MocoConstraintInfo updConstraintInfo() {
    return new SWIGTYPE_p_MocoConstraintInfo(opensimMocoJNI.MocoGoal_updConstraintInfo(swigCPtr, this), false);
  }

  public void setEndpointConstraintBounds(StdVectorMocoBounds bounds) {
    opensimMocoJNI.MocoGoal_setEndpointConstraintBounds(swigCPtr, this, StdVectorMocoBounds.getCPtr(bounds), bounds);
  }

  public StdVectorMocoBounds getEndpointConstraintBounds() {
    return new StdVectorMocoBounds(opensimMocoJNI.MocoGoal_getEndpointConstraintBounds(swigCPtr, this), true);
  }

  public int getNumOutputs() {
    return opensimMocoJNI.MocoGoal_getNumOutputs(swigCPtr, this);
  }

  public int getNumIntegrals() {
    return opensimMocoJNI.MocoGoal_getNumIntegrals(swigCPtr, this);
  }

  public Stage getStageDependency() {
    return new Stage(opensimMocoJNI.MocoGoal_getStageDependency(swigCPtr, this), true);
  }

  public void initializeOnModel(Model model) {
    opensimMocoJNI.MocoGoal_initializeOnModel(swigCPtr, this, Model.getCPtr(model), model);
  }

  public SWIGTYPE_p_std__vectorT_OpenSim__MocoScaleFactor_t getScaleFactors() {
    return new SWIGTYPE_p_std__vectorT_OpenSim__MocoScaleFactor_t(opensimMocoJNI.MocoGoal_getScaleFactors(swigCPtr, this), true);
  }

  public void printDescription() {
    opensimMocoJNI.MocoGoal_printDescription(swigCPtr, this);
  }

  public void setDivideByDisplacement(boolean tf) {
    opensimMocoJNI.MocoGoal_setDivideByDisplacement(swigCPtr, this, tf);
  }

  public boolean getDivideByDisplacement() {
    return opensimMocoJNI.MocoGoal_getDivideByDisplacement(swigCPtr, this);
  }

  public void setDivideByDuration(boolean tf) {
    opensimMocoJNI.MocoGoal_setDivideByDuration(swigCPtr, this, tf);
  }

  public boolean getDivideByDuration() {
    return opensimMocoJNI.MocoGoal_getDivideByDuration(swigCPtr, this);
  }

  public void setDivideByMass(boolean tf) {
    opensimMocoJNI.MocoGoal_setDivideByMass(swigCPtr, this, tf);
  }

  public boolean getDivideByMass() {
    return opensimMocoJNI.MocoGoal_getDivideByMass(swigCPtr, this);
  }

  public SWIGTYPE_p_std__unordered_mapT_std__string_int_t getInputControlIndexMap() {
    return new SWIGTYPE_p_std__unordered_mapT_std__string_int_t(opensimMocoJNI.MocoGoal_getInputControlIndexMap(swigCPtr, this), true);
  }

  public Vector getInputControls(State state) {
    return new Vector(opensimMocoJNI.MocoGoal_getInputControls(swigCPtr, this, State.getCPtr(state), state), false);
  }

  public final static class Mode {
    public final static MocoGoal.Mode Cost = new MocoGoal.Mode("Cost");
    public final static MocoGoal.Mode EndpointConstraint = new MocoGoal.Mode("EndpointConstraint");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static Mode swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + Mode.class + " with value " + swigValue);
    }

    private Mode(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private Mode(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private Mode(String swigName, Mode swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static Mode[] swigValues = { Cost, EndpointConstraint };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
