/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoControlGoal extends MocoGoal {
  private transient long swigCPtr;

  public MocoControlGoal(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoControlGoal_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoControlGoal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoControlGoal obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoControlGoal(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MocoControlGoal safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoControlGoal_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoControlGoal(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoControlGoal_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoControlGoal_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoControlGoal_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoControlGoal(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoControlGoal_getConcreteClassName(swigCPtr, this);
  }

  public MocoControlGoal() {
    this(opensimMocoJNI.new_MocoControlGoal__SWIG_0(), true);
  }

  public MocoControlGoal(String name) {
    this(opensimMocoJNI.new_MocoControlGoal__SWIG_1(name), true);
  }

  public MocoControlGoal(String name, double weight) {
    this(opensimMocoJNI.new_MocoControlGoal__SWIG_2(name, weight), true);
  }

  public void setWeightForControl(String controlName, double weight) {
    opensimMocoJNI.MocoControlGoal_setWeightForControl(swigCPtr, this, controlName, weight);
  }

  public void setWeightForControlPattern(String pattern, double weight) {
    opensimMocoJNI.MocoControlGoal_setWeightForControlPattern(swigCPtr, this, pattern, weight);
  }

  public void setExponent(int exponent) {
    opensimMocoJNI.MocoControlGoal_setExponent(swigCPtr, this, exponent);
  }

  public double getExponent() {
    return opensimMocoJNI.MocoControlGoal_getExponent(swigCPtr, this);
  }

  public void setIgnoreControlledActuators(boolean v) {
    opensimMocoJNI.MocoControlGoal_setIgnoreControlledActuators(swigCPtr, this, v);
  }

  public boolean getIgnoreControlledActuators() {
    return opensimMocoJNI.MocoControlGoal_getIgnoreControlledActuators(swigCPtr, this);
  }

  public void setIgnoreInputControls(boolean v) {
    opensimMocoJNI.MocoControlGoal_setIgnoreInputControls(swigCPtr, this, v);
  }

  public boolean getIgnoreInputControls() {
    return opensimMocoJNI.MocoControlGoal_getIgnoreInputControls(swigCPtr, this);
  }

}
