/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoPathConstraint extends OpenSimObject {
  private transient long swigCPtr;

  public MocoPathConstraint(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoPathConstraint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoPathConstraint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoPathConstraint obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoPathConstraint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MocoPathConstraint safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoPathConstraint_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoPathConstraint(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoPathConstraint_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoPathConstraint_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoPathConstraint_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoPathConstraint(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoPathConstraint_getConcreteClassName(swigCPtr, this);
  }

  public MocoConstraintInfo getConstraintInfo() {
    return new MocoConstraintInfo(opensimMocoJNI.MocoPathConstraint_getConstraintInfo(swigCPtr, this), false);
  }

  public MocoConstraintInfo updConstraintInfo() {
    return new MocoConstraintInfo(opensimMocoJNI.MocoPathConstraint_updConstraintInfo(swigCPtr, this), false);
  }

  public void setConstraintInfo(MocoConstraintInfo cInfo) {
    opensimMocoJNI.MocoPathConstraint_setConstraintInfo(swigCPtr, this, MocoConstraintInfo.getCPtr(cInfo), cInfo);
  }

  public int getPathConstraintIndex() {
    return opensimMocoJNI.MocoPathConstraint_getPathConstraintIndex(swigCPtr, this);
  }

  public void calcPathConstraintErrors(State state, Vector errors) {
    opensimMocoJNI.MocoPathConstraint_calcPathConstraintErrors(swigCPtr, this, State.getCPtr(state), state, Vector.getCPtr(errors), errors);
  }

  public void calcPathConstraintErrorsView(State state, Vector errors) {
    opensimMocoJNI.MocoPathConstraint_calcPathConstraintErrorsView(swigCPtr, this, State.getCPtr(state), state, Vector.getCPtr(errors), errors);
  }

  public SWIGTYPE_p_std__unordered_mapT_std__string_int_t getInputControlIndexMap() {
    return new SWIGTYPE_p_std__unordered_mapT_std__string_int_t(opensimMocoJNI.MocoPathConstraint_getInputControlIndexMap(swigCPtr, this), true);
  }

  public Vector getInputControls(State state) {
    return new Vector(opensimMocoJNI.MocoPathConstraint_getInputControls(swigCPtr, this, State.getCPtr(state), state), false);
  }

  public void initializeOnModel(Model model, SWIGTYPE_p_OpenSim__MocoProblemInfo arg1, int pathConstraintIndex) {
    opensimMocoJNI.MocoPathConstraint_initializeOnModel(swigCPtr, this, Model.getCPtr(model), model, SWIGTYPE_p_OpenSim__MocoProblemInfo.getCPtr(arg1), pathConstraintIndex);
  }

  public void printDescription() {
    opensimMocoJNI.MocoPathConstraint_printDescription(swigCPtr, this);
  }

}
