/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoStepTimeAsymmetryGoal extends MocoGoal {
  private transient long swigCPtr;

  public MocoStepTimeAsymmetryGoal(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoStepTimeAsymmetryGoal_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoStepTimeAsymmetryGoal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoStepTimeAsymmetryGoal obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoStepTimeAsymmetryGoal(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MocoStepTimeAsymmetryGoal safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoStepTimeAsymmetryGoal_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoStepTimeAsymmetryGoal(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoStepTimeAsymmetryGoal_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoStepTimeAsymmetryGoal_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoStepTimeAsymmetryGoal_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoStepTimeAsymmetryGoal(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoStepTimeAsymmetryGoal_getConcreteClassName(swigCPtr, this);
  }

  public MocoStepTimeAsymmetryGoal() {
    this(opensimMocoJNI.new_MocoStepTimeAsymmetryGoal__SWIG_0(), true);
  }

  public MocoStepTimeAsymmetryGoal(String name) {
    this(opensimMocoJNI.new_MocoStepTimeAsymmetryGoal__SWIG_1(name), true);
  }

  public MocoStepTimeAsymmetryGoal(String name, double weight) {
    this(opensimMocoJNI.new_MocoStepTimeAsymmetryGoal__SWIG_2(name, weight), true);
  }

  public void setLeftContactGroup(StdVectorString contactForcePaths, String footPositionForcePath) {
    opensimMocoJNI.MocoStepTimeAsymmetryGoal_setLeftContactGroup(swigCPtr, this, StdVectorString.getCPtr(contactForcePaths), contactForcePaths, footPositionForcePath);
  }

  public void setRightContactGroup(StdVectorString contactForcePaths, String footPositionForcePath) {
    opensimMocoJNI.MocoStepTimeAsymmetryGoal_setRightContactGroup(swigCPtr, this, StdVectorString.getCPtr(contactForcePaths), contactForcePaths, footPositionForcePath);
  }

  public void setTargetAsymmetry(double asymmetry) {
    opensimMocoJNI.MocoStepTimeAsymmetryGoal_setTargetAsymmetry(swigCPtr, this, asymmetry);
  }

  public double getTargetAsymmetry() {
    return opensimMocoJNI.MocoStepTimeAsymmetryGoal_getTargetAsymmetry(swigCPtr, this);
  }

  public void setContactForceThreshold(double threshold) {
    opensimMocoJNI.MocoStepTimeAsymmetryGoal_setContactForceThreshold(swigCPtr, this, threshold);
  }

  public double getContactForceThreshold() {
    return opensimMocoJNI.MocoStepTimeAsymmetryGoal_getContactForceThreshold(swigCPtr, this);
  }

  public void setContactForceDirection(String direction) {
    opensimMocoJNI.MocoStepTimeAsymmetryGoal_setContactForceDirection(swigCPtr, this, direction);
  }

  public String getContactForceDirection() {
    return opensimMocoJNI.MocoStepTimeAsymmetryGoal_getContactForceDirection(swigCPtr, this);
  }

  public void setWalkingDirection(String direction) {
    opensimMocoJNI.MocoStepTimeAsymmetryGoal_setWalkingDirection(swigCPtr, this, direction);
  }

  public String getWalkingDirection() {
    return opensimMocoJNI.MocoStepTimeAsymmetryGoal_getWalkingDirection(swigCPtr, this);
  }

  public void setAsymmetrySmoothing(double smoothing) {
    opensimMocoJNI.MocoStepTimeAsymmetryGoal_setAsymmetrySmoothing(swigCPtr, this, smoothing);
  }

  public double getAsymmetrySmoothing() {
    return opensimMocoJNI.MocoStepTimeAsymmetryGoal_getAsymmetrySmoothing(swigCPtr, this);
  }

  public void setContactDetectionSmoothing(double smoothing) {
    opensimMocoJNI.MocoStepTimeAsymmetryGoal_setContactDetectionSmoothing(swigCPtr, this, smoothing);
  }

  public double getContactDetectionSmoothing() {
    return opensimMocoJNI.MocoStepTimeAsymmetryGoal_getContactDetectionSmoothing(swigCPtr, this);
  }

}
