/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoOutputConstraint extends MocoPathConstraint {
  private transient long swigCPtr;

  public MocoOutputConstraint(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoOutputConstraint_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoOutputConstraint obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoOutputConstraint obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoOutputConstraint(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MocoOutputConstraint safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoOutputConstraint_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoOutputConstraint(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoOutputConstraint_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoOutputConstraint_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoOutputConstraint_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoOutputConstraint(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoOutputConstraint_getConcreteClassName(swigCPtr, this);
  }

  public MocoOutputConstraint() {
    this(opensimMocoJNI.new_MocoOutputConstraint(), true);
  }

  public void setOutputPath(String path) {
    opensimMocoJNI.MocoOutputConstraint_setOutputPath(swigCPtr, this, path);
  }

  public String getOutputPath() {
    return opensimMocoJNI.MocoOutputConstraint_getOutputPath(swigCPtr, this);
  }

  public void setSecondOutputPath(String path) {
    opensimMocoJNI.MocoOutputConstraint_setSecondOutputPath(swigCPtr, this, path);
  }

  public String getSecondOutputPath() {
    return opensimMocoJNI.MocoOutputConstraint_getSecondOutputPath(swigCPtr, this);
  }

  public void setOperation(String operation) {
    opensimMocoJNI.MocoOutputConstraint_setOperation(swigCPtr, this, operation);
  }

  public String getOperation() {
    return opensimMocoJNI.MocoOutputConstraint_getOperation(swigCPtr, this);
  }

  public void setExponent(int exponent) {
    opensimMocoJNI.MocoOutputConstraint_setExponent(swigCPtr, this, exponent);
  }

  public int getExponent() {
    return opensimMocoJNI.MocoOutputConstraint_getExponent(swigCPtr, this);
  }

  public void setOutputIndex(int index) {
    opensimMocoJNI.MocoOutputConstraint_setOutputIndex(swigCPtr, this, index);
  }

  public int getOutputIndex() {
    return opensimMocoJNI.MocoOutputConstraint_getOutputIndex(swigCPtr, this);
  }

}
