/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoContactImpulseTrackingGoal extends MocoGoal {
  private transient long swigCPtr;

  public MocoContactImpulseTrackingGoal(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoContactImpulseTrackingGoal_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoContactImpulseTrackingGoal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoContactImpulseTrackingGoal obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoContactImpulseTrackingGoal(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MocoContactImpulseTrackingGoal safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoContactImpulseTrackingGoal_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoContactImpulseTrackingGoal(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoContactImpulseTrackingGoal_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoContactImpulseTrackingGoal_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoContactImpulseTrackingGoal_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoContactImpulseTrackingGoal(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoContactImpulseTrackingGoal_getConcreteClassName(swigCPtr, this);
  }

  public MocoContactImpulseTrackingGoal() {
    this(opensimMocoJNI.new_MocoContactImpulseTrackingGoal__SWIG_0(), true);
  }

  public MocoContactImpulseTrackingGoal(String name) {
    this(opensimMocoJNI.new_MocoContactImpulseTrackingGoal__SWIG_1(name), true);
  }

  public MocoContactImpulseTrackingGoal(String name, double weight) {
    this(opensimMocoJNI.new_MocoContactImpulseTrackingGoal__SWIG_2(name, weight), true);
  }

  public void setExternalLoadsFile(String extLoadsFile) {
    opensimMocoJNI.MocoContactImpulseTrackingGoal_setExternalLoadsFile(swigCPtr, this, extLoadsFile);
  }

  public void setExternalLoads(ExternalLoads extLoads) {
    opensimMocoJNI.MocoContactImpulseTrackingGoal_setExternalLoads(swigCPtr, this, ExternalLoads.getCPtr(extLoads), extLoads);
  }

  public void addContactGroup(StdVectorString contactForcePaths, String externalForceName) {
    opensimMocoJNI.MocoContactImpulseTrackingGoal_addContactGroup__SWIG_0(swigCPtr, this, StdVectorString.getCPtr(contactForcePaths), contactForcePaths, externalForceName);
  }

  public void addContactGroup(MocoContactImpulseTrackingGoalGroup group) {
    opensimMocoJNI.MocoContactImpulseTrackingGoal_addContactGroup__SWIG_1(swigCPtr, this, MocoContactImpulseTrackingGoalGroup.getCPtr(group), group);
  }

  public void setImpulseAxis(int impulseAxis) {
    opensimMocoJNI.MocoContactImpulseTrackingGoal_setImpulseAxis(swigCPtr, this, impulseAxis);
  }

  public int getImpulseAxis() {
    return opensimMocoJNI.MocoContactImpulseTrackingGoal_getImpulseAxis(swigCPtr, this);
  }

  public void addScaleFactor(String name, String externalForceName, MocoBounds bounds) {
    opensimMocoJNI.MocoContactImpulseTrackingGoal_addScaleFactor(swigCPtr, this, name, externalForceName, MocoBounds.getCPtr(bounds), bounds);
  }

}
