/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoAngularVelocityTrackingGoal extends MocoGoal {
  private transient long swigCPtr;

  public MocoAngularVelocityTrackingGoal(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoAngularVelocityTrackingGoal_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoAngularVelocityTrackingGoal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoAngularVelocityTrackingGoal obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoAngularVelocityTrackingGoal(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MocoAngularVelocityTrackingGoal safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoAngularVelocityTrackingGoal_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoAngularVelocityTrackingGoal(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoAngularVelocityTrackingGoal_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoAngularVelocityTrackingGoal_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoAngularVelocityTrackingGoal_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoAngularVelocityTrackingGoal(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoAngularVelocityTrackingGoal_getConcreteClassName(swigCPtr, this);
  }

  public MocoAngularVelocityTrackingGoal() {
    this(opensimMocoJNI.new_MocoAngularVelocityTrackingGoal__SWIG_0(), true);
  }

  public MocoAngularVelocityTrackingGoal(String name) {
    this(opensimMocoJNI.new_MocoAngularVelocityTrackingGoal__SWIG_1(name), true);
  }

  public MocoAngularVelocityTrackingGoal(String name, double weight) {
    this(opensimMocoJNI.new_MocoAngularVelocityTrackingGoal__SWIG_2(name, weight), true);
  }

  public void setAngularVelocityReferenceFile(String filepath) {
    opensimMocoJNI.MocoAngularVelocityTrackingGoal_setAngularVelocityReferenceFile(swigCPtr, this, filepath);
  }

  public void setAngularVelocityReference(TimeSeriesTableVec3 ref) {
    opensimMocoJNI.MocoAngularVelocityTrackingGoal_setAngularVelocityReference(swigCPtr, this, TimeSeriesTableVec3.getCPtr(ref), ref);
  }

  public void setStatesReference(TableProcessor ref) {
    opensimMocoJNI.MocoAngularVelocityTrackingGoal_setStatesReference(swigCPtr, this, TableProcessor.getCPtr(ref), ref);
  }

  public void setFramePaths(StdVectorString paths) {
    opensimMocoJNI.MocoAngularVelocityTrackingGoal_setFramePaths(swigCPtr, this, StdVectorString.getCPtr(paths), paths);
  }

  public void setWeightForFrame(String frameName, double weight) {
    opensimMocoJNI.MocoAngularVelocityTrackingGoal_setWeightForFrame(swigCPtr, this, frameName, weight);
  }

  public void setWeightSet(MocoWeightSet weightSet) {
    opensimMocoJNI.MocoAngularVelocityTrackingGoal_setWeightSet(swigCPtr, this, MocoWeightSet.getCPtr(weightSet), weightSet);
  }

  public TableProcessor getStatesReference() {
    return new TableProcessor(opensimMocoJNI.MocoAngularVelocityTrackingGoal_getStatesReference(swigCPtr, this), false);
  }

  public String getAngularVelocityReferenceFile() {
    return opensimMocoJNI.MocoAngularVelocityTrackingGoal_getAngularVelocityReferenceFile(swigCPtr, this);
  }

}
