/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoJointReactionGoal extends MocoGoal {
  private transient long swigCPtr;

  public MocoJointReactionGoal(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoJointReactionGoal_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoJointReactionGoal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoJointReactionGoal obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoJointReactionGoal(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MocoJointReactionGoal safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoJointReactionGoal_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoJointReactionGoal(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoJointReactionGoal_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoJointReactionGoal_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoJointReactionGoal_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoJointReactionGoal(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoJointReactionGoal_getConcreteClassName(swigCPtr, this);
  }

  public MocoJointReactionGoal() {
    this(opensimMocoJNI.new_MocoJointReactionGoal__SWIG_0(), true);
  }

  public MocoJointReactionGoal(String name) {
    this(opensimMocoJNI.new_MocoJointReactionGoal__SWIG_1(name), true);
  }

  public MocoJointReactionGoal(String name, double weight) {
    this(opensimMocoJNI.new_MocoJointReactionGoal__SWIG_2(name, weight), true);
  }

  public void setJointPath(String jointPath) {
    opensimMocoJNI.MocoJointReactionGoal_setJointPath(swigCPtr, this, jointPath);
  }

  public void setLoadsFrame(String frame) {
    opensimMocoJNI.MocoJointReactionGoal_setLoadsFrame(swigCPtr, this, frame);
  }

  public void setExpressedInFramePath(String framePath) {
    opensimMocoJNI.MocoJointReactionGoal_setExpressedInFramePath(swigCPtr, this, framePath);
  }

  public void setReactionMeasures(StdVectorString measures) {
    opensimMocoJNI.MocoJointReactionGoal_setReactionMeasures(swigCPtr, this, StdVectorString.getCPtr(measures), measures);
  }

  public void setReactionWeight(String measure, double weight) {
    opensimMocoJNI.MocoJointReactionGoal_setReactionWeight(swigCPtr, this, measure, weight);
  }

  public void setReactionWeightSet(MocoWeightSet weightSet) {
    opensimMocoJNI.MocoJointReactionGoal_setReactionWeightSet(swigCPtr, this, MocoWeightSet.getCPtr(weightSet), weightSet);
  }

}
