/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class MocoStepLengthAsymmetryGoal extends MocoGoal {
  private transient long swigCPtr;

  public MocoStepLengthAsymmetryGoal(long cPtr, boolean cMemoryOwn) {
    super(opensimMocoJNI.MocoStepLengthAsymmetryGoal_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(MocoStepLengthAsymmetryGoal obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(MocoStepLengthAsymmetryGoal obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimMocoJNI.delete_MocoStepLengthAsymmetryGoal(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static MocoStepLengthAsymmetryGoal safeDownCast(OpenSimObject obj) {
    long cPtr = opensimMocoJNI.MocoStepLengthAsymmetryGoal_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new MocoStepLengthAsymmetryGoal(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimMocoJNI.MocoStepLengthAsymmetryGoal_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimMocoJNI.MocoStepLengthAsymmetryGoal_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimMocoJNI.MocoStepLengthAsymmetryGoal_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new MocoStepLengthAsymmetryGoal(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimMocoJNI.MocoStepLengthAsymmetryGoal_getConcreteClassName(swigCPtr, this);
  }

  public MocoStepLengthAsymmetryGoal() {
    this(opensimMocoJNI.new_MocoStepLengthAsymmetryGoal__SWIG_0(), true);
  }

  public MocoStepLengthAsymmetryGoal(String name) {
    this(opensimMocoJNI.new_MocoStepLengthAsymmetryGoal__SWIG_1(name), true);
  }

  public MocoStepLengthAsymmetryGoal(String name, double weight) {
    this(opensimMocoJNI.new_MocoStepLengthAsymmetryGoal__SWIG_2(name, weight), true);
  }

  public void setLeftFootFrame(String frame) {
    opensimMocoJNI.MocoStepLengthAsymmetryGoal_setLeftFootFrame(swigCPtr, this, frame);
  }

  public String getLeftFootFrame() {
    return opensimMocoJNI.MocoStepLengthAsymmetryGoal_getLeftFootFrame(swigCPtr, this);
  }

  public void setRightFootFrame(String frame) {
    opensimMocoJNI.MocoStepLengthAsymmetryGoal_setRightFootFrame(swigCPtr, this, frame);
  }

  public String getRightFootFrame() {
    return opensimMocoJNI.MocoStepLengthAsymmetryGoal_getRightFootFrame(swigCPtr, this);
  }

  public void setTargetAsymmetry(double asymmetry) {
    opensimMocoJNI.MocoStepLengthAsymmetryGoal_setTargetAsymmetry(swigCPtr, this, asymmetry);
  }

  public double getTargetAsymmetry() {
    return opensimMocoJNI.MocoStepLengthAsymmetryGoal_getTargetAsymmetry(swigCPtr, this);
  }

  public void setStrideLength(double length) {
    opensimMocoJNI.MocoStepLengthAsymmetryGoal_setStrideLength(swigCPtr, this, length);
  }

  public double getStrideLength() {
    return opensimMocoJNI.MocoStepLengthAsymmetryGoal_getStrideLength(swigCPtr, this);
  }

  public void setWalkingDirection(String direction) {
    opensimMocoJNI.MocoStepLengthAsymmetryGoal_setWalkingDirection(swigCPtr, this, direction);
  }

  public String getWalkingDirection() {
    return opensimMocoJNI.MocoStepLengthAsymmetryGoal_getWalkingDirection(swigCPtr, this);
  }

  public void setAsymmetrySmoothing(double smoothing) {
    opensimMocoJNI.MocoStepLengthAsymmetryGoal_setAsymmetrySmoothing(swigCPtr, this, smoothing);
  }

  public double getAsymmetrySmoothing() {
    return opensimMocoJNI.MocoStepLengthAsymmetryGoal_getAsymmetrySmoothing(swigCPtr, this);
  }

}
