/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public interface opensimSimbodyConstants {
  public final static SWIGTYPE_p_long_double SimTK_PI = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_PI_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_E = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_E_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_LN2 = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_LN2_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_LN10 = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_LN10_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_LOG2E = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_LOG2E_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_LOG10E = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_LOG10E_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_SQRT2 = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_SQRT2_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_OOSQRT2 = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_OOSQRT2_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_CBRT2 = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_CBRT2_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_OOCBRT2 = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_OOCBRT2_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_SIXRT2 = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_SIXRT2_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_OOSIXRT2 = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_OOSIXRT2_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_SQRT3 = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_SQRT3_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_CBRT3 = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_CBRT3_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_AVOGADROS_NUMBER = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_AVOGADROS_NUMBER_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_MASS_OF_PROTON_IN_MD = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_MASS_OF_PROTON_IN_MD_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_MASS_OF_NEUTRON_IN_MD = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_MASS_OF_NEUTRON_IN_MD_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_MASS_OF_ELECTRON_IN_MD = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_MASS_OF_ELECTRON_IN_MD_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_CHARGE_OF_PROTON_IN_SI = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_CHARGE_OF_PROTON_IN_SI_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_CHARGE_OF_PROTON_IN_MD = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_CHARGE_OF_PROTON_IN_MD_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_MOLAR_CHARGE_IN_SI = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_MOLAR_CHARGE_IN_SI_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_MOLAR_CHARGE_IN_MD = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_MOLAR_CHARGE_IN_MD_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_LIGHTSPEED_IN_SI = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_LIGHTSPEED_IN_SI_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_LIGHTSPEED_IN_MD = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_LIGHTSPEED_IN_MD_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_GRAVITATIONAL_CONSTANT_IN_SI = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_GRAVITATIONAL_CONSTANT_IN_SI_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_GRAVITATIONAL_CONSTANT_IN_MD = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_GRAVITATIONAL_CONSTANT_IN_MD_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_MAGNETIC_PERMEABILITY_IN_SI = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_MAGNETIC_PERMEABILITY_IN_SI_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_MAGNETIC_PERMEABILITY_IN_MD = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_MAGNETIC_PERMEABILITY_IN_MD_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_ELECTRIC_PERMITTIVITY_IN_SI = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_ELECTRIC_PERMITTIVITY_IN_SI_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_ELECTRIC_PERMITTIVITY_IN_MD = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_ELECTRIC_PERMITTIVITY_IN_MD_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_COULOMB_CONSTANT_IN_SI = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_COULOMB_CONSTANT_IN_SI_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_COULOMB_CONSTANT_IN_MD = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_COULOMB_CONSTANT_IN_MD_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_COULOMB_CONSTANT_IN_KCAL_ANGSTROM = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_COULOMB_CONSTANT_IN_KCAL_ANGSTROM_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_MOLAR_GAS_CONSTANT_SI = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_MOLAR_GAS_CONSTANT_SI_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_MOLAR_GAS_CONSTANT_MD = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_MOLAR_GAS_CONSTANT_MD_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_MOLAR_GAS_CONSTANT_KCAL_ANGSTROM = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_MOLAR_GAS_CONSTANT_KCAL_ANGSTROM_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_BOLTZMANN_CONSTANT_SI = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_BOLTZMANN_CONSTANT_SI_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_BOLTZMANN_CONSTANT_MD = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_BOLTZMANN_CONSTANT_MD_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_BOLTZMANN_CONSTANT_KCAL_ANGSTROM = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_BOLTZMANN_CONSTANT_KCAL_ANGSTROM_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_RADIAN_TO_DEGREE = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_RADIAN_TO_DEGREE_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_DEGREE_TO_RADIAN = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_DEGREE_TO_RADIAN_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_NS_TO_S = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_NS_TO_S_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_S_TO_NS = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_S_TO_NS_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_KCAL_TO_KJOULE = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_KCAL_TO_KJOULE_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_KJOULE_TO_KCAL = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_KJOULE_TO_KCAL_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_DALTON_TO_GRAM = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_DALTON_TO_GRAM_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_E_TO_COULOMB = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_E_TO_COULOMB_get(), false);
  public final static SWIGTYPE_p_long_double SimTK_EV_TO_JOULE = new SWIGTYPE_p_long_double(opensimSimbodyJNI.SimTK_EV_TO_JOULE_get(), false);
  public final static int SimTK_DEFAULT_PRECISION = opensimSimbodyJNI.SimTK_DEFAULT_PRECISION_get();
}
