/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class OpenSenseUtilities {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public OpenSenseUtilities(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OpenSenseUtilities obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(OpenSenseUtilities obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_OpenSenseUtilities(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void rotateOrientationTable(TimeSeriesTableQuaternion quaternionsTable, Rotation rotationMatrix) {
    opensimSimulationJNI.OpenSenseUtilities_rotateOrientationTable(TimeSeriesTableQuaternion.getCPtr(quaternionsTable), quaternionsTable, Rotation.getCPtr(rotationMatrix), rotationMatrix);
  }

  public static TimeSeriesTableRotation convertQuaternionsToRotations(TimeSeriesTableQuaternion qauternionsTable) {
    return new TimeSeriesTableRotation(opensimSimulationJNI.OpenSenseUtilities_convertQuaternionsToRotations(TimeSeriesTableQuaternion.getCPtr(qauternionsTable), qauternionsTable), true);
  }

  public static Vec3 computeHeadingCorrection(Model model, State state, TimeSeriesTableQuaternion quatTimeSeries, String baseIMU, CoordinateDirection arg4) {
    return new Vec3(opensimSimulationJNI.OpenSenseUtilities_computeHeadingCorrection(Model.getCPtr(model), model, State.getCPtr(state), state, TimeSeriesTableQuaternion.getCPtr(quatTimeSeries), quatTimeSeries, baseIMU, CoordinateDirection.getCPtr(arg4), arg4), true);
  }

  public static TimeSeriesTableQuaternion createOrientationsFileFromMarkers(String markersFile) {
    return new TimeSeriesTableQuaternion(opensimSimulationJNI.OpenSenseUtilities_createOrientationsFileFromMarkers(markersFile), true);
  }

  public static Transform formTransformFromPoints(Vec3 op, Vec3 xp, Vec3 yp) {
    return new Transform(opensimSimulationJNI.OpenSenseUtilities_formTransformFromPoints(Vec3.getCPtr(op), op, Vec3.getCPtr(xp), xp, Vec3.getCPtr(yp), yp), true);
  }

  public static StdVectorIMUs addModelIMUs(Model model, StdVectorString paths) {
    return new StdVectorIMUs(opensimSimulationJNI.OpenSenseUtilities_addModelIMUs(Model.getCPtr(model), model, StdVectorString.getCPtr(paths), paths), true);
  }

  public OpenSenseUtilities() {
    this(opensimSimulationJNI.new_OpenSenseUtilities(), true);
  }

}
