/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class opensimSimulation {
  public static State simulate(Model model, State initialState, double finalTime, boolean saveStatesFile) {
    return new State(opensimSimulationJNI.simulate__SWIG_0(Model.getCPtr(model), model, State.getCPtr(initialState), initialState, finalTime, saveStatesFile), true);
  }

  public static State simulate(Model model, State initialState, double finalTime) {
    return new State(opensimSimulationJNI.simulate__SWIG_1(Model.getCPtr(model), model, State.getCPtr(initialState), initialState, finalTime), true);
  }

  public static void updateStateLabels40(Model model, StdVectorString labels) {
    opensimSimulationJNI.updateStateLabels40(Model.getCPtr(model), model, StdVectorString.getCPtr(labels), labels);
  }

  public static void updatePre40KinematicsFilesFor40MotionType(Model model, StdVectorString filePaths, String suffix) {
    opensimSimulationJNI.updatePre40KinematicsFilesFor40MotionType__SWIG_0(Model.getCPtr(model), model, StdVectorString.getCPtr(filePaths), filePaths, suffix);
  }

  public static void updatePre40KinematicsFilesFor40MotionType(Model model, StdVectorString filePaths) {
    opensimSimulationJNI.updatePre40KinematicsFilesFor40MotionType__SWIG_1(Model.getCPtr(model), model, StdVectorString.getCPtr(filePaths), filePaths);
  }

  public static void updateSocketConnecteesBySearch(Model model) {
    opensimSimulationJNI.updateSocketConnecteesBySearch(Model.getCPtr(model), model);
  }

  public static StdVectorString createStateVariableNamesInSystemOrder(Model model) {
    return new StdVectorString(opensimSimulationJNI.createStateVariableNamesInSystemOrder(Model.getCPtr(model), model), true);
  }

  public static StdVectorString createControlNamesFromModel(Model model, StdVectorInt modelControlIndices) {
    return new StdVectorString(opensimSimulationJNI.createControlNamesFromModel__SWIG_0(Model.getCPtr(model), model, StdVectorInt.getCPtr(modelControlIndices), modelControlIndices), true);
  }

  public static StdVectorString createControlNamesFromModel(Model model) {
    return new StdVectorString(opensimSimulationJNI.createControlNamesFromModel__SWIG_1(Model.getCPtr(model), model), true);
  }

  public static SWIGTYPE_p_std__unordered_mapT_std__string_int_t createSystemControlIndexMap(Model model) {
    return new SWIGTYPE_p_std__unordered_mapT_std__string_int_t(opensimSimulationJNI.createSystemControlIndexMap(Model.getCPtr(model), model), true);
  }

  public static void checkOrderSystemControls(Model model) {
    opensimSimulationJNI.checkOrderSystemControls(Model.getCPtr(model), model);
  }

  public static void checkLabelsMatchModelStates(Model model, StdVectorString labels) {
    opensimSimulationJNI.checkLabelsMatchModelStates(Model.getCPtr(model), model, StdVectorString.getCPtr(labels), labels);
  }

  public static TimeSeriesTableVec3 createSyntheticIMUAccelerationSignals(Model model, TimeSeriesTable statesTable, TimeSeriesTable controlsTable, StdVectorString framePaths) {
    return new TimeSeriesTableVec3(opensimSimulationJNI.createSyntheticIMUAccelerationSignals(Model.getCPtr(model), model, TimeSeriesTable.getCPtr(statesTable), statesTable, TimeSeriesTable.getCPtr(controlsTable), controlsTable, StdVectorString.getCPtr(framePaths), framePaths), true);
  }

  public static void appendCoupledCoordinateValues(TimeSeriesTable table, Model model, boolean overwriteExistingColumns) {
    opensimSimulationJNI.appendCoupledCoordinateValues__SWIG_0(TimeSeriesTable.getCPtr(table), table, Model.getCPtr(model), model, overwriteExistingColumns);
  }

  public static void appendCoupledCoordinateValues(TimeSeriesTable table, Model model) {
    opensimSimulationJNI.appendCoupledCoordinateValues__SWIG_1(TimeSeriesTable.getCPtr(table), table, Model.getCPtr(model), model);
  }

  public static void appendCoordinateValueDerivativesAsSpeeds(TimeSeriesTable table, Model model, boolean overwriteExistingColumns) {
    opensimSimulationJNI.appendCoordinateValueDerivativesAsSpeeds__SWIG_0(TimeSeriesTable.getCPtr(table), table, Model.getCPtr(model), model, overwriteExistingColumns);
  }

  public static void appendCoordinateValueDerivativesAsSpeeds(TimeSeriesTable table, Model model) {
    opensimSimulationJNI.appendCoordinateValueDerivativesAsSpeeds__SWIG_1(TimeSeriesTable.getCPtr(table), table, Model.getCPtr(model), model);
  }

  public static TimeSeriesTable analyze(Model model, TimeSeriesTable statesTable, TimeSeriesTable controlsTable, StdVectorString outputPaths, TimeSeriesTable discreteVariablesTable) {
    return new TimeSeriesTable(opensimSimulationJNI.analyze__SWIG_0(Model.getCPtr(model), model, TimeSeriesTable.getCPtr(statesTable), statesTable, TimeSeriesTable.getCPtr(controlsTable), controlsTable, StdVectorString.getCPtr(outputPaths), outputPaths, TimeSeriesTable.getCPtr(discreteVariablesTable), discreteVariablesTable), true);
  }

  public static TimeSeriesTable analyze(Model model, TimeSeriesTable statesTable, TimeSeriesTable controlsTable, StdVectorString outputPaths) {
    return new TimeSeriesTable(opensimSimulationJNI.analyze__SWIG_1(Model.getCPtr(model), model, TimeSeriesTable.getCPtr(statesTable), statesTable, TimeSeriesTable.getCPtr(controlsTable), controlsTable, StdVectorString.getCPtr(outputPaths), outputPaths), true);
  }

  public static TimeSeriesTableVec3 analyzeVec3(Model model, TimeSeriesTable statesTable, TimeSeriesTable controlsTable, StdVectorString outputPaths, TimeSeriesTable discreteVariablesTable) {
    return new TimeSeriesTableVec3(opensimSimulationJNI.analyzeVec3__SWIG_0(Model.getCPtr(model), model, TimeSeriesTable.getCPtr(statesTable), statesTable, TimeSeriesTable.getCPtr(controlsTable), controlsTable, StdVectorString.getCPtr(outputPaths), outputPaths, TimeSeriesTable.getCPtr(discreteVariablesTable), discreteVariablesTable), true);
  }

  public static TimeSeriesTableVec3 analyzeVec3(Model model, TimeSeriesTable statesTable, TimeSeriesTable controlsTable, StdVectorString outputPaths) {
    return new TimeSeriesTableVec3(opensimSimulationJNI.analyzeVec3__SWIG_1(Model.getCPtr(model), model, TimeSeriesTable.getCPtr(statesTable), statesTable, TimeSeriesTable.getCPtr(controlsTable), controlsTable, StdVectorString.getCPtr(outputPaths), outputPaths), true);
  }

  public static TimeSeriesTableSpatialVec analyzeSpatialVec(Model model, TimeSeriesTable statesTable, TimeSeriesTable controlsTable, StdVectorString outputPaths, TimeSeriesTable discreteVariablesTable) {
    return new TimeSeriesTableSpatialVec(opensimSimulationJNI.analyzeSpatialVec__SWIG_0(Model.getCPtr(model), model, TimeSeriesTable.getCPtr(statesTable), statesTable, TimeSeriesTable.getCPtr(controlsTable), controlsTable, StdVectorString.getCPtr(outputPaths), outputPaths, TimeSeriesTable.getCPtr(discreteVariablesTable), discreteVariablesTable), true);
  }

  public static TimeSeriesTableSpatialVec analyzeSpatialVec(Model model, TimeSeriesTable statesTable, TimeSeriesTable controlsTable, StdVectorString outputPaths) {
    return new TimeSeriesTableSpatialVec(opensimSimulationJNI.analyzeSpatialVec__SWIG_1(Model.getCPtr(model), model, TimeSeriesTable.getCPtr(statesTable), statesTable, TimeSeriesTable.getCPtr(controlsTable), controlsTable, StdVectorString.getCPtr(outputPaths), outputPaths), true);
  }

  public static TimeSeriesTableRotation analyzeRotation(Model model, TimeSeriesTable statesTable, TimeSeriesTable controlsTable, StdVectorString outputPaths, TimeSeriesTable discreteVariablesTable) {
    return new TimeSeriesTableRotation(opensimSimulationJNI.analyzeRotation__SWIG_0(Model.getCPtr(model), model, TimeSeriesTable.getCPtr(statesTable), statesTable, TimeSeriesTable.getCPtr(controlsTable), controlsTable, StdVectorString.getCPtr(outputPaths), outputPaths, TimeSeriesTable.getCPtr(discreteVariablesTable), discreteVariablesTable), true);
  }

  public static TimeSeriesTableRotation analyzeRotation(Model model, TimeSeriesTable statesTable, TimeSeriesTable controlsTable, StdVectorString outputPaths) {
    return new TimeSeriesTableRotation(opensimSimulationJNI.analyzeRotation__SWIG_1(Model.getCPtr(model), model, TimeSeriesTable.getCPtr(statesTable), statesTable, TimeSeriesTable.getCPtr(controlsTable), controlsTable, StdVectorString.getCPtr(outputPaths), outputPaths), true);
  }

}
