/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class PathSpring extends ForceProducer {
  private transient long swigCPtr;

  public PathSpring(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.PathSpring_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(PathSpring obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(PathSpring obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_PathSpring(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static PathSpring safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.PathSpring_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new PathSpring(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.PathSpring_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.PathSpring_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.PathSpring_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new PathSpring(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.PathSpring_getConcreteClassName(swigCPtr, this);
  }

  public void copyProperty_resting_length(PathSpring source) {
    opensimSimulationJNI.PathSpring_copyProperty_resting_length(swigCPtr, this, PathSpring.getCPtr(source), source);
  }

  public double get_resting_length(int i) {
    return opensimSimulationJNI.PathSpring_get_resting_length__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_resting_length(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.PathSpring_upd_resting_length__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_resting_length(int i, double value) {
    opensimSimulationJNI.PathSpring_set_resting_length__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_resting_length(double value) {
    return opensimSimulationJNI.PathSpring_append_resting_length(swigCPtr, this, value);
  }

  public void constructProperty_resting_length(double initValue) {
    opensimSimulationJNI.PathSpring_constructProperty_resting_length(swigCPtr, this, initValue);
  }

  public double get_resting_length() {
    return opensimSimulationJNI.PathSpring_get_resting_length__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_resting_length() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.PathSpring_upd_resting_length__SWIG_1(swigCPtr, this), false);
  }

  public void set_resting_length(double value) {
    opensimSimulationJNI.PathSpring_set_resting_length__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_stiffness(PathSpring source) {
    opensimSimulationJNI.PathSpring_copyProperty_stiffness(swigCPtr, this, PathSpring.getCPtr(source), source);
  }

  public double get_stiffness(int i) {
    return opensimSimulationJNI.PathSpring_get_stiffness__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_stiffness(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.PathSpring_upd_stiffness__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_stiffness(int i, double value) {
    opensimSimulationJNI.PathSpring_set_stiffness__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_stiffness(double value) {
    return opensimSimulationJNI.PathSpring_append_stiffness(swigCPtr, this, value);
  }

  public void constructProperty_stiffness(double initValue) {
    opensimSimulationJNI.PathSpring_constructProperty_stiffness(swigCPtr, this, initValue);
  }

  public double get_stiffness() {
    return opensimSimulationJNI.PathSpring_get_stiffness__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_stiffness() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.PathSpring_upd_stiffness__SWIG_1(swigCPtr, this), false);
  }

  public void set_stiffness(double value) {
    opensimSimulationJNI.PathSpring_set_stiffness__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_dissipation(PathSpring source) {
    opensimSimulationJNI.PathSpring_copyProperty_dissipation(swigCPtr, this, PathSpring.getCPtr(source), source);
  }

  public double get_dissipation(int i) {
    return opensimSimulationJNI.PathSpring_get_dissipation__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_double upd_dissipation(int i) {
    return new SWIGTYPE_p_double(opensimSimulationJNI.PathSpring_upd_dissipation__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_dissipation(int i, double value) {
    opensimSimulationJNI.PathSpring_set_dissipation__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_dissipation(double value) {
    return opensimSimulationJNI.PathSpring_append_dissipation(swigCPtr, this, value);
  }

  public void constructProperty_dissipation(double initValue) {
    opensimSimulationJNI.PathSpring_constructProperty_dissipation(swigCPtr, this, initValue);
  }

  public double get_dissipation() {
    return opensimSimulationJNI.PathSpring_get_dissipation__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double upd_dissipation() {
    return new SWIGTYPE_p_double(opensimSimulationJNI.PathSpring_upd_dissipation__SWIG_1(swigCPtr, this), false);
  }

  public void set_dissipation(double value) {
    opensimSimulationJNI.PathSpring_set_dissipation__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_path(PathSpring source) {
    opensimSimulationJNI.PathSpring_copyProperty_path(swigCPtr, this, PathSpring.getCPtr(source), source);
  }

  public AbstractGeometryPath get_path(int i) {
    return new AbstractGeometryPath(opensimSimulationJNI.PathSpring_get_path__SWIG_0(swigCPtr, this, i), false);
  }

  public AbstractGeometryPath upd_path(int i) {
    return new AbstractGeometryPath(opensimSimulationJNI.PathSpring_upd_path__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_path(int i, AbstractGeometryPath value) {
    opensimSimulationJNI.PathSpring_set_path__SWIG_0(swigCPtr, this, i, AbstractGeometryPath.getCPtr(value), value);
  }

  public int append_path(AbstractGeometryPath value) {
    return opensimSimulationJNI.PathSpring_append_path(swigCPtr, this, AbstractGeometryPath.getCPtr(value), value);
  }

  public void constructProperty_path(AbstractGeometryPath initValue) {
    opensimSimulationJNI.PathSpring_constructProperty_path(swigCPtr, this, AbstractGeometryPath.getCPtr(initValue), initValue);
  }

  public AbstractGeometryPath get_path() {
    return new AbstractGeometryPath(opensimSimulationJNI.PathSpring_get_path__SWIG_1(swigCPtr, this), false);
  }

  public AbstractGeometryPath upd_path() {
    return new AbstractGeometryPath(opensimSimulationJNI.PathSpring_upd_path__SWIG_1(swigCPtr, this), false);
  }

  public void set_path(AbstractGeometryPath value) {
    opensimSimulationJNI.PathSpring_set_path__SWIG_1(swigCPtr, this, AbstractGeometryPath.getCPtr(value), value);
  }

  public void set_has_output_length(boolean value) {
    opensimSimulationJNI.PathSpring__has_output_length_set(swigCPtr, this, value);
  }

  public boolean get_has_output_length() {
    return opensimSimulationJNI.PathSpring__has_output_length_get(swigCPtr, this);
  }

  public void set_has_output_stretch(boolean value) {
    opensimSimulationJNI.PathSpring__has_output_stretch_set(swigCPtr, this, value);
  }

  public boolean get_has_output_stretch() {
    return opensimSimulationJNI.PathSpring__has_output_stretch_get(swigCPtr, this);
  }

  public void set_has_output_lengthening_speed(boolean value) {
    opensimSimulationJNI.PathSpring__has_output_lengthening_speed_set(swigCPtr, this, value);
  }

  public boolean get_has_output_lengthening_speed() {
    return opensimSimulationJNI.PathSpring__has_output_lengthening_speed_get(swigCPtr, this);
  }

  public void set_has_output_tension(boolean value) {
    opensimSimulationJNI.PathSpring__has_output_tension_set(swigCPtr, this, value);
  }

  public boolean get_has_output_tension() {
    return opensimSimulationJNI.PathSpring__has_output_tension_get(swigCPtr, this);
  }

  public PathSpring() {
    this(opensimSimulationJNI.new_PathSpring__SWIG_0(), true);
  }

  public PathSpring(String name, double restLength, double stiffness, double dissipation) {
    this(opensimSimulationJNI.new_PathSpring__SWIG_1(name, restLength, stiffness, dissipation), true);
  }

  public double getRestingLength() {
    return opensimSimulationJNI.PathSpring_getRestingLength(swigCPtr, this);
  }

  public void setRestingLength(double restingLength) {
    opensimSimulationJNI.PathSpring_setRestingLength(swigCPtr, this, restingLength);
  }

  public double getStiffness() {
    return opensimSimulationJNI.PathSpring_getStiffness(swigCPtr, this);
  }

  public void setStiffness(double stiffness) {
    opensimSimulationJNI.PathSpring_setStiffness(swigCPtr, this, stiffness);
  }

  public double getDissipation() {
    return opensimSimulationJNI.PathSpring_getDissipation(swigCPtr, this);
  }

  public void setDissipation(double dissipation) {
    opensimSimulationJNI.PathSpring_setDissipation(swigCPtr, this, dissipation);
  }

  public AbstractGeometryPath updPath() {
    return new AbstractGeometryPath(opensimSimulationJNI.PathSpring_updPath(swigCPtr, this), false);
  }

  public AbstractGeometryPath getPath() {
    return new AbstractGeometryPath(opensimSimulationJNI.PathSpring_getPath(swigCPtr, this), false);
  }

  public GeometryPath updGeometryPath() {
    return new GeometryPath(opensimSimulationJNI.PathSpring_updGeometryPath(swigCPtr, this), false);
  }

  public GeometryPath getGeometryPath() {
    return new GeometryPath(opensimSimulationJNI.PathSpring_getGeometryPath(swigCPtr, this), false);
  }

  public boolean hasVisualPath() {
    return opensimSimulationJNI.PathSpring_hasVisualPath(swigCPtr, this);
  }

  public double getLength(State s) {
    return opensimSimulationJNI.PathSpring_getLength(swigCPtr, this, State.getCPtr(s), s);
  }

  public double getStretch(State s) {
    return opensimSimulationJNI.PathSpring_getStretch(swigCPtr, this, State.getCPtr(s), s);
  }

  public double getLengtheningSpeed(State s) {
    return opensimSimulationJNI.PathSpring_getLengtheningSpeed(swigCPtr, this, State.getCPtr(s), s);
  }

  public double getTension(State s) {
    return opensimSimulationJNI.PathSpring_getTension(swigCPtr, this, State.getCPtr(s), s);
  }

  public double computeMomentArm(State s, Coordinate aCoord) {
    return opensimSimulationJNI.PathSpring_computeMomentArm(swigCPtr, this, State.getCPtr(s), s, Coordinate.getCPtr(aCoord), aCoord);
  }

  public void extendPostScale(State s, ScaleSet scaleSet) {
    opensimSimulationJNI.PathSpring_extendPostScale(swigCPtr, this, State.getCPtr(s), s, ScaleSet.getCPtr(scaleSet), scaleSet);
  }

}
