/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class PolygonalMesh {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public PolygonalMesh(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PolygonalMesh obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(PolygonalMesh obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimbodyJNI.delete_PolygonalMesh(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public PolygonalMesh() {
    this(opensimSimbodyJNI.new_PolygonalMesh(), true);
  }

  public static PolygonalMesh createSphereMesh(double radius, int resolution) {
    return new PolygonalMesh(opensimSimbodyJNI.PolygonalMesh_createSphereMesh__SWIG_0(radius, resolution), true);
  }

  public static PolygonalMesh createSphereMesh(double radius) {
    return new PolygonalMesh(opensimSimbodyJNI.PolygonalMesh_createSphereMesh__SWIG_1(radius), true);
  }

  public static PolygonalMesh createBrickMesh(Vec3 halfDims, int resolution) {
    return new PolygonalMesh(opensimSimbodyJNI.PolygonalMesh_createBrickMesh__SWIG_0(Vec3.getCPtr(halfDims), halfDims, resolution), true);
  }

  public static PolygonalMesh createBrickMesh(Vec3 halfDims) {
    return new PolygonalMesh(opensimSimbodyJNI.PolygonalMesh_createBrickMesh__SWIG_1(Vec3.getCPtr(halfDims), halfDims), true);
  }

  public static PolygonalMesh createCylinderMesh(UnitVec3 axis, double radius, double halfLength, int resolution) {
    return new PolygonalMesh(opensimSimbodyJNI.PolygonalMesh_createCylinderMesh__SWIG_0(UnitVec3.getCPtr(axis), axis, radius, halfLength, resolution), true);
  }

  public static PolygonalMesh createCylinderMesh(UnitVec3 axis, double radius, double halfLength) {
    return new PolygonalMesh(opensimSimbodyJNI.PolygonalMesh_createCylinderMesh__SWIG_1(UnitVec3.getCPtr(axis), axis, radius, halfLength), true);
  }

  public void clear() {
    opensimSimbodyJNI.PolygonalMesh_clear(swigCPtr, this);
  }

  public int getNumFaces() {
    return opensimSimbodyJNI.PolygonalMesh_getNumFaces(swigCPtr, this);
  }

  public int getNumVertices() {
    return opensimSimbodyJNI.PolygonalMesh_getNumVertices(swigCPtr, this);
  }

  public boolean hasNormals() {
    return opensimSimbodyJNI.PolygonalMesh_hasNormals(swigCPtr, this);
  }

  public boolean hasNormalsAtVertices() {
    return opensimSimbodyJNI.PolygonalMesh_hasNormalsAtVertices(swigCPtr, this);
  }

  public boolean hasNormalsAtFaces() {
    return opensimSimbodyJNI.PolygonalMesh_hasNormalsAtFaces(swigCPtr, this);
  }

  public boolean hasTextureCoordinates() {
    return opensimSimbodyJNI.PolygonalMesh_hasTextureCoordinates(swigCPtr, this);
  }

  public boolean hasTextureCoordinatesAtFaces() {
    return opensimSimbodyJNI.PolygonalMesh_hasTextureCoordinatesAtFaces(swigCPtr, this);
  }

  public boolean hasTextureCoordinatesAtVertices() {
    return opensimSimbodyJNI.PolygonalMesh_hasTextureCoordinatesAtVertices(swigCPtr, this);
  }

  public Vec3 getVertexPosition(int vertex) {
    return new Vec3(opensimSimbodyJNI.PolygonalMesh_getVertexPosition(swigCPtr, this, vertex), false);
  }

  public UnitVec3 getVertexNormal(int faceIndex, int vertexIndex) {
    return new UnitVec3(opensimSimbodyJNI.PolygonalMesh_getVertexNormal__SWIG_0(swigCPtr, this, faceIndex, vertexIndex), true);
  }

  public UnitVec3 getVertexNormal(int vertex) {
    return new UnitVec3(opensimSimbodyJNI.PolygonalMesh_getVertexNormal__SWIG_1(swigCPtr, this, vertex), false);
  }

  public Vec2 getVertexTextureCoordinate(int faceIndex, int vertexIndex) {
    return new Vec2(opensimSimbodyJNI.PolygonalMesh_getVertexTextureCoordinate(swigCPtr, this, faceIndex, vertexIndex), true);
  }

  public int getNumVerticesForFace(int face) {
    return opensimSimbodyJNI.PolygonalMesh_getNumVerticesForFace(swigCPtr, this, face);
  }

  public int getFaceVertex(int face, int vertex) {
    return opensimSimbodyJNI.PolygonalMesh_getFaceVertex(swigCPtr, this, face, vertex);
  }

  public int addVertex(Vec3 position) {
    return opensimSimbodyJNI.PolygonalMesh_addVertex(swigCPtr, this, Vec3.getCPtr(position), position);
  }

  public int addNormal(UnitVec3 normal) {
    return opensimSimbodyJNI.PolygonalMesh_addNormal(swigCPtr, this, UnitVec3.getCPtr(normal), normal);
  }

  public int addTextureCoordinate(Vec2 textureCoord) {
    return opensimSimbodyJNI.PolygonalMesh_addTextureCoordinate(swigCPtr, this, Vec2.getCPtr(textureCoord), textureCoord);
  }

  public int addFace(SimTKArrayInt vertices) {
    return opensimSimbodyJNI.PolygonalMesh_addFace(swigCPtr, this, SimTKArrayInt.getCPtr(vertices), vertices);
  }

  public int addFaceWithNormals(SimTKArrayInt vertices, SimTKArrayInt normalIndices) {
    return opensimSimbodyJNI.PolygonalMesh_addFaceWithNormals(swigCPtr, this, SimTKArrayInt.getCPtr(vertices), vertices, SimTKArrayInt.getCPtr(normalIndices), normalIndices);
  }

  public void addFaceTextureCoordinates(SimTKArrayInt textureIndices) {
    opensimSimbodyJNI.PolygonalMesh_addFaceTextureCoordinates(swigCPtr, this, SimTKArrayInt.getCPtr(textureIndices), textureIndices);
  }

  public PolygonalMesh scaleMesh(double scale) {
    return new PolygonalMesh(opensimSimbodyJNI.PolygonalMesh_scaleMesh(swigCPtr, this, scale), false);
  }

  public PolygonalMesh transformMesh(Transform X_AM) {
    return new PolygonalMesh(opensimSimbodyJNI.PolygonalMesh_transformMesh(swigCPtr, this, Transform.getCPtr(X_AM), X_AM), false);
  }

  public void loadFile(SWIGTYPE_p_String pathname) {
    opensimSimbodyJNI.PolygonalMesh_loadFile__SWIG_0(swigCPtr, this, SWIGTYPE_p_String.getCPtr(pathname));
  }

  public void loadObjFile(SWIGTYPE_p_String pathname) {
    opensimSimbodyJNI.PolygonalMesh_loadObjFile__SWIG_0(swigCPtr, this, SWIGTYPE_p_String.getCPtr(pathname));
  }

  public void loadObjFile(SWIGTYPE_p_std__istream file) {
    opensimSimbodyJNI.PolygonalMesh_loadObjFile__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(file));
  }

  public void loadVtpFile(SWIGTYPE_p_String pathname) {
    opensimSimbodyJNI.PolygonalMesh_loadVtpFile(swigCPtr, this, SWIGTYPE_p_String.getCPtr(pathname));
  }

  public void loadStlFile(SWIGTYPE_p_String pathname) {
    opensimSimbodyJNI.PolygonalMesh_loadStlFile(swigCPtr, this, SWIGTYPE_p_String.getCPtr(pathname));
  }

  public void loadFile(String pathname) {
    opensimSimbodyJNI.PolygonalMesh_loadFile__SWIG_1(swigCPtr, this, pathname);
  }

}
