/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class PropertyObjectList extends AbstractProperty {
  private transient long swigCPtr;

  public PropertyObjectList(long cPtr, boolean cMemoryOwn) {
    super(opensimCommonJNI.PropertyObjectList_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(PropertyObjectList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(PropertyObjectList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AbstractProperty clone() {
    long cPtr = opensimCommonJNI.PropertyObjectList_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new PropertyObjectList(cPtr, true);
  }

  public String getTypeName() {
    return opensimCommonJNI.PropertyObjectList_getTypeName(swigCPtr, this);
  }

  public void setValue(int i, OpenSimObject value) {
    opensimCommonJNI.PropertyObjectList_setValue__SWIG_0(swigCPtr, this, i, OpenSimObject.getCPtr(value), value);
  }

  public void setValue(OpenSimObject value) {
    opensimCommonJNI.PropertyObjectList_setValue__SWIG_1(swigCPtr, this, OpenSimObject.getCPtr(value), value);
  }

  public OpenSimObject getValue(int index) {
    return new OpenSimObject(opensimCommonJNI.PropertyObjectList_getValue__SWIG_0(swigCPtr, this, index), false);
  }

  public OpenSimObject getValue() {
    return new OpenSimObject(opensimCommonJNI.PropertyObjectList_getValue__SWIG_1(swigCPtr, this), false);
  }

  public OpenSimObject updValue(int index) {
    return new OpenSimObject(opensimCommonJNI.PropertyObjectList_updValue__SWIG_0(swigCPtr, this, index), false);
  }

  public OpenSimObject updValue() {
    return new OpenSimObject(opensimCommonJNI.PropertyObjectList_updValue__SWIG_1(swigCPtr, this), false);
  }

  public int appendValue(OpenSimObject value) {
    return opensimCommonJNI.PropertyObjectList_appendValue__SWIG_0(swigCPtr, this, OpenSimObject.getCPtr(value), value);
  }

  public int adoptAndAppendValue(OpenSimObject value) {
    return opensimCommonJNI.PropertyObjectList_adoptAndAppendValue(swigCPtr, this, OpenSimObject.getCPtr(value), value);
  }

  public void removeValueAtIndex(int index) {
    opensimCommonJNI.PropertyObjectList_removeValueAtIndex(swigCPtr, this, index);
  }

  public int findIndex(OpenSimObject value) {
    return opensimCommonJNI.PropertyObjectList_findIndex(swigCPtr, this, OpenSimObject.getCPtr(value), value);
  }

  public int findIndexForName(SWIGTYPE_p_SimTK__String name) {
    return opensimCommonJNI.PropertyObjectList_findIndexForName(swigCPtr, this, SWIGTYPE_p_SimTK__String.getCPtr(name));
  }

  public static boolean isA(AbstractProperty prop) {
    return opensimCommonJNI.PropertyObjectList_isA(AbstractProperty.getCPtr(prop), prop);
  }

  public static PropertyObjectList getAs(AbstractProperty prop) {
    return new PropertyObjectList(opensimCommonJNI.PropertyObjectList_getAs(AbstractProperty.getCPtr(prop), prop), false);
  }

  public static PropertyObjectList updAs(AbstractProperty prop) {
    return new PropertyObjectList(opensimCommonJNI.PropertyObjectList_updAs(AbstractProperty.getCPtr(prop), prop), false);
  }

}
