/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class PropertyBoolList extends AbstractProperty {
  private transient long swigCPtr;

  public PropertyBoolList(long cPtr, boolean cMemoryOwn) {
    super(opensimCommonJNI.PropertyBoolList_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(PropertyBoolList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(PropertyBoolList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AbstractProperty clone() {
    long cPtr = opensimCommonJNI.PropertyBoolList_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new PropertyBoolList(cPtr, true);
  }

  public String getTypeName() {
    return opensimCommonJNI.PropertyBoolList_getTypeName(swigCPtr, this);
  }

  public void setValue(int i, boolean value) {
    opensimCommonJNI.PropertyBoolList_setValue__SWIG_0(swigCPtr, this, i, value);
  }

  public void setValue(boolean value) {
    opensimCommonJNI.PropertyBoolList_setValue__SWIG_1(swigCPtr, this, value);
  }

  public boolean getValue(int index) {
    return opensimCommonJNI.PropertyBoolList_getValue__SWIG_0(swigCPtr, this, index);
  }

  public boolean getValue() {
    return opensimCommonJNI.PropertyBoolList_getValue__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_bool updValue(int index) {
    return new SWIGTYPE_p_bool(opensimCommonJNI.PropertyBoolList_updValue__SWIG_0(swigCPtr, this, index), false);
  }

  public SWIGTYPE_p_bool updValue() {
    return new SWIGTYPE_p_bool(opensimCommonJNI.PropertyBoolList_updValue__SWIG_1(swigCPtr, this), false);
  }

  public int appendValue(boolean value) {
    return opensimCommonJNI.PropertyBoolList_appendValue__SWIG_0(swigCPtr, this, value);
  }

  public int appendValue(SWIGTYPE_p_bool value) {
    return opensimCommonJNI.PropertyBoolList_appendValue__SWIG_1(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(value));
  }

  public int adoptAndAppendValue(SWIGTYPE_p_bool value) {
    return opensimCommonJNI.PropertyBoolList_adoptAndAppendValue(swigCPtr, this, SWIGTYPE_p_bool.getCPtr(value));
  }

  public void removeValueAtIndex(int index) {
    opensimCommonJNI.PropertyBoolList_removeValueAtIndex(swigCPtr, this, index);
  }

  public int findIndex(boolean value) {
    return opensimCommonJNI.PropertyBoolList_findIndex(swigCPtr, this, value);
  }

  public int findIndexForName(SWIGTYPE_p_SimTK__String name) {
    return opensimCommonJNI.PropertyBoolList_findIndexForName(swigCPtr, this, SWIGTYPE_p_SimTK__String.getCPtr(name));
  }

  public static boolean isA(AbstractProperty prop) {
    return opensimCommonJNI.PropertyBoolList_isA(AbstractProperty.getCPtr(prop), prop);
  }

  public static PropertyBoolList getAs(AbstractProperty prop) {
    return new PropertyBoolList(opensimCommonJNI.PropertyBoolList_getAs(AbstractProperty.getCPtr(prop), prop), false);
  }

  public static PropertyBoolList updAs(AbstractProperty prop) {
    return new PropertyBoolList(opensimCommonJNI.PropertyBoolList_updAs(AbstractProperty.getCPtr(prop), prop), false);
  }

}
