/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class PropertyDoubleList extends AbstractProperty {
  private transient long swigCPtr;

  public PropertyDoubleList(long cPtr, boolean cMemoryOwn) {
    super(opensimCommonJNI.PropertyDoubleList_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(PropertyDoubleList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(PropertyDoubleList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AbstractProperty clone() {
    long cPtr = opensimCommonJNI.PropertyDoubleList_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new PropertyDoubleList(cPtr, true);
  }

  public String getTypeName() {
    return opensimCommonJNI.PropertyDoubleList_getTypeName(swigCPtr, this);
  }

  public void setValue(int i, double value) {
    opensimCommonJNI.PropertyDoubleList_setValue__SWIG_0(swigCPtr, this, i, value);
  }

  public void setValue(double value) {
    opensimCommonJNI.PropertyDoubleList_setValue__SWIG_1(swigCPtr, this, value);
  }

  public double getValue(int index) {
    return opensimCommonJNI.PropertyDoubleList_getValue__SWIG_0(swigCPtr, this, index);
  }

  public double getValue() {
    return opensimCommonJNI.PropertyDoubleList_getValue__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_double updValue(int index) {
    return new SWIGTYPE_p_double(opensimCommonJNI.PropertyDoubleList_updValue__SWIG_0(swigCPtr, this, index), false);
  }

  public SWIGTYPE_p_double updValue() {
    return new SWIGTYPE_p_double(opensimCommonJNI.PropertyDoubleList_updValue__SWIG_1(swigCPtr, this), false);
  }

  public int appendValue(double value) {
    return opensimCommonJNI.PropertyDoubleList_appendValue__SWIG_0(swigCPtr, this, value);
  }

  public int appendValue(SWIGTYPE_p_double value) {
    return opensimCommonJNI.PropertyDoubleList_appendValue__SWIG_1(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public int adoptAndAppendValue(SWIGTYPE_p_double value) {
    return opensimCommonJNI.PropertyDoubleList_adoptAndAppendValue(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public void removeValueAtIndex(int index) {
    opensimCommonJNI.PropertyDoubleList_removeValueAtIndex(swigCPtr, this, index);
  }

  public int findIndex(double value) {
    return opensimCommonJNI.PropertyDoubleList_findIndex(swigCPtr, this, value);
  }

  public int findIndexForName(SWIGTYPE_p_SimTK__String name) {
    return opensimCommonJNI.PropertyDoubleList_findIndexForName(swigCPtr, this, SWIGTYPE_p_SimTK__String.getCPtr(name));
  }

  public static boolean isA(AbstractProperty prop) {
    return opensimCommonJNI.PropertyDoubleList_isA(AbstractProperty.getCPtr(prop), prop);
  }

  public static PropertyDoubleList getAs(AbstractProperty prop) {
    return new PropertyDoubleList(opensimCommonJNI.PropertyDoubleList_getAs(AbstractProperty.getCPtr(prop), prop), false);
  }

  public static PropertyDoubleList updAs(AbstractProperty prop) {
    return new PropertyDoubleList(opensimCommonJNI.PropertyDoubleList_updAs(AbstractProperty.getCPtr(prop), prop), false);
  }

}
