/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class PropertyStringList extends AbstractProperty {
  private transient long swigCPtr;

  public PropertyStringList(long cPtr, boolean cMemoryOwn) {
    super(opensimCommonJNI.PropertyStringList_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(PropertyStringList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(PropertyStringList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AbstractProperty clone() {
    long cPtr = opensimCommonJNI.PropertyStringList_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new PropertyStringList(cPtr, true);
  }

  public String getTypeName() {
    return opensimCommonJNI.PropertyStringList_getTypeName(swigCPtr, this);
  }

  public void setValue(int i, String value) {
    opensimCommonJNI.PropertyStringList_setValue__SWIG_0(swigCPtr, this, i, value);
  }

  public void setValue(String value) {
    opensimCommonJNI.PropertyStringList_setValue__SWIG_1(swigCPtr, this, value);
  }

  public String getValue(int index) {
    return opensimCommonJNI.PropertyStringList_getValue__SWIG_0(swigCPtr, this, index);
  }

  public String getValue() {
    return opensimCommonJNI.PropertyStringList_getValue__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string updValue(int index) {
    return new SWIGTYPE_p_std__string(opensimCommonJNI.PropertyStringList_updValue__SWIG_0(swigCPtr, this, index), false);
  }

  public SWIGTYPE_p_std__string updValue() {
    return new SWIGTYPE_p_std__string(opensimCommonJNI.PropertyStringList_updValue__SWIG_1(swigCPtr, this), false);
  }

  public int appendValue(String value) {
    return opensimCommonJNI.PropertyStringList_appendValue(swigCPtr, this, value);
  }

  public int adoptAndAppendValue(SWIGTYPE_p_std__string value) {
    return opensimCommonJNI.PropertyStringList_adoptAndAppendValue(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(value));
  }

  public void removeValueAtIndex(int index) {
    opensimCommonJNI.PropertyStringList_removeValueAtIndex(swigCPtr, this, index);
  }

  public int findIndex(String value) {
    return opensimCommonJNI.PropertyStringList_findIndex(swigCPtr, this, value);
  }

  public int findIndexForName(SWIGTYPE_p_SimTK__String name) {
    return opensimCommonJNI.PropertyStringList_findIndexForName(swigCPtr, this, SWIGTYPE_p_SimTK__String.getCPtr(name));
  }

  public static boolean isA(AbstractProperty prop) {
    return opensimCommonJNI.PropertyStringList_isA(AbstractProperty.getCPtr(prop), prop);
  }

  public static PropertyStringList getAs(AbstractProperty prop) {
    return new PropertyStringList(opensimCommonJNI.PropertyStringList_getAs(AbstractProperty.getCPtr(prop), prop), false);
  }

  public static PropertyStringList updAs(AbstractProperty prop) {
    return new PropertyStringList(opensimCommonJNI.PropertyStringList_updAs(AbstractProperty.getCPtr(prop), prop), false);
  }

}
