/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class PropertyIntList extends AbstractProperty {
  private transient long swigCPtr;

  public PropertyIntList(long cPtr, boolean cMemoryOwn) {
    super(opensimCommonJNI.PropertyIntList_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(PropertyIntList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(PropertyIntList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public AbstractProperty clone() {
    long cPtr = opensimCommonJNI.PropertyIntList_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new PropertyIntList(cPtr, true);
  }

  public String getTypeName() {
    return opensimCommonJNI.PropertyIntList_getTypeName(swigCPtr, this);
  }

  public void setValue(int i, int value) {
    opensimCommonJNI.PropertyIntList_setValue__SWIG_0(swigCPtr, this, i, value);
  }

  public void setValue(int value) {
    opensimCommonJNI.PropertyIntList_setValue__SWIG_1(swigCPtr, this, value);
  }

  public int getValue(int index) {
    return opensimCommonJNI.PropertyIntList_getValue__SWIG_0(swigCPtr, this, index);
  }

  public int getValue() {
    return opensimCommonJNI.PropertyIntList_getValue__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_int updValue(int index) {
    return new SWIGTYPE_p_int(opensimCommonJNI.PropertyIntList_updValue__SWIG_0(swigCPtr, this, index), false);
  }

  public SWIGTYPE_p_int updValue() {
    return new SWIGTYPE_p_int(opensimCommonJNI.PropertyIntList_updValue__SWIG_1(swigCPtr, this), false);
  }

  public int appendValue(int value) {
    return opensimCommonJNI.PropertyIntList_appendValue__SWIG_0(swigCPtr, this, value);
  }

  public int appendValue(SWIGTYPE_p_int value) {
    return opensimCommonJNI.PropertyIntList_appendValue__SWIG_1(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public int adoptAndAppendValue(SWIGTYPE_p_int value) {
    return opensimCommonJNI.PropertyIntList_adoptAndAppendValue(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public void removeValueAtIndex(int index) {
    opensimCommonJNI.PropertyIntList_removeValueAtIndex(swigCPtr, this, index);
  }

  public int findIndex(int value) {
    return opensimCommonJNI.PropertyIntList_findIndex(swigCPtr, this, value);
  }

  public int findIndexForName(SWIGTYPE_p_SimTK__String name) {
    return opensimCommonJNI.PropertyIntList_findIndexForName(swigCPtr, this, SWIGTYPE_p_SimTK__String.getCPtr(name));
  }

  public static boolean isA(AbstractProperty prop) {
    return opensimCommonJNI.PropertyIntList_isA(AbstractProperty.getCPtr(prop), prop);
  }

  public static PropertyIntList getAs(AbstractProperty prop) {
    return new PropertyIntList(opensimCommonJNI.PropertyIntList_getAs(AbstractProperty.getCPtr(prop), prop), false);
  }

  public static PropertyIntList updAs(AbstractProperty prop) {
    return new PropertyIntList(opensimCommonJNI.PropertyIntList_updAs(AbstractProperty.getCPtr(prop), prop), false);
  }

}
