/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class ReporterDouble extends AbstractReporter {
  private transient long swigCPtr;

  public ReporterDouble(long cPtr, boolean cMemoryOwn) {
    super(opensimCommonJNI.ReporterDouble_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(ReporterDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ReporterDouble obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static ReporterDouble safeDownCast(OpenSimObject obj) {
    long cPtr = opensimCommonJNI.ReporterDouble_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new ReporterDouble(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimCommonJNI.ReporterDouble_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimCommonJNI.ReporterDouble_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimCommonJNI.ReporterDouble_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ReporterDouble(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimCommonJNI.ReporterDouble_getConcreteClassName(swigCPtr, this);
  }

  public void setPropertyIndex_input_inputs(SWIGTYPE_p_OpenSim__PropertyIndex value) {
    opensimCommonJNI.ReporterDouble_PropertyIndex_input_inputs_set(swigCPtr, this, SWIGTYPE_p_OpenSim__PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_OpenSim__PropertyIndex getPropertyIndex_input_inputs() {
    return new SWIGTYPE_p_OpenSim__PropertyIndex(opensimCommonJNI.ReporterDouble_PropertyIndex_input_inputs_get(swigCPtr, this), true);
  }

  public void connectInput_inputs(AbstractOutput output, String alias) {
    opensimCommonJNI.ReporterDouble_connectInput_inputs__SWIG_0(swigCPtr, this, AbstractOutput.getCPtr(output), output, alias);
  }

  public void connectInput_inputs(AbstractOutput output) {
    opensimCommonJNI.ReporterDouble_connectInput_inputs__SWIG_1(swigCPtr, this, AbstractOutput.getCPtr(output), output);
  }

  public void connectInput_inputs(AbstractChannel channel, String alias) {
    opensimCommonJNI.ReporterDouble_connectInput_inputs__SWIG_2(swigCPtr, this, AbstractChannel.getCPtr(channel), channel, alias);
  }

  public void connectInput_inputs(AbstractChannel channel) {
    opensimCommonJNI.ReporterDouble_connectInput_inputs__SWIG_3(swigCPtr, this, AbstractChannel.getCPtr(channel), channel);
  }

  public void addToReport(AbstractOutput output, String alias) {
    opensimCommonJNI.ReporterDouble_addToReport__SWIG_0(swigCPtr, this, AbstractOutput.getCPtr(output), output, alias);
  }

  public void addToReport(AbstractOutput output) {
    opensimCommonJNI.ReporterDouble_addToReport__SWIG_1(swigCPtr, this, AbstractOutput.getCPtr(output), output);
  }

  public void addToReport(AbstractChannel channel, String alias) {
    opensimCommonJNI.ReporterDouble_addToReport__SWIG_2(swigCPtr, this, AbstractChannel.getCPtr(channel), channel, alias);
  }

  public void addToReport(AbstractChannel channel) {
    opensimCommonJNI.ReporterDouble_addToReport__SWIG_3(swigCPtr, this, AbstractChannel.getCPtr(channel), channel);
  }

}
