/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class RowVectorQuaternion extends RowVectorBaseQuaternion {
  private transient long swigCPtr;

  public RowVectorQuaternion(long cPtr, boolean cMemoryOwn) {
    super(opensimSimbodyJNI.RowVectorQuaternion_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(RowVectorQuaternion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(RowVectorQuaternion obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimbodyJNI.delete_RowVectorQuaternion(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public RowVectorQuaternion() {
    this(opensimSimbodyJNI.new_RowVectorQuaternion__SWIG_0(), true);
  }

  public RowVectorQuaternion(RowVectorQuaternion src) {
    this(opensimSimbodyJNI.new_RowVectorQuaternion__SWIG_1(RowVectorQuaternion.getCPtr(src), src), true);
  }

  public RowVectorQuaternion(RowVectorBaseQuaternion src) {
    this(opensimSimbodyJNI.new_RowVectorQuaternion__SWIG_2(RowVectorBaseQuaternion.getCPtr(src), src), true);
  }

  public RowVectorQuaternion(int n) {
    this(opensimSimbodyJNI.new_RowVectorQuaternion__SWIG_3(n), true);
  }

  public RowVectorQuaternion(int n, Quaternion cppInitialValues) {
    this(opensimSimbodyJNI.new_RowVectorQuaternion__SWIG_4(n, Quaternion.getCPtr(cppInitialValues), cppInitialValues), true);
  }

}
