/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class Scholz2015GeometryPathObstacle extends Scholz2015GeometryPathElement {
  private transient long swigCPtr;

  public Scholz2015GeometryPathObstacle(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.Scholz2015GeometryPathObstacle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Scholz2015GeometryPathObstacle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(Scholz2015GeometryPathObstacle obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_Scholz2015GeometryPathObstacle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static Scholz2015GeometryPathObstacle safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.Scholz2015GeometryPathObstacle_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new Scholz2015GeometryPathObstacle(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.Scholz2015GeometryPathObstacle_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.Scholz2015GeometryPathObstacle_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.Scholz2015GeometryPathObstacle_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Scholz2015GeometryPathObstacle(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.Scholz2015GeometryPathObstacle_getConcreteClassName(swigCPtr, this);
  }

  public void setPropertyIndex_socket_contact_geometry(SWIGTYPE_p_OpenSim__PropertyIndex value) {
    opensimSimulationJNI.Scholz2015GeometryPathObstacle_PropertyIndex_socket_contact_geometry_set(swigCPtr, this, SWIGTYPE_p_OpenSim__PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_OpenSim__PropertyIndex getPropertyIndex_socket_contact_geometry() {
    return new SWIGTYPE_p_OpenSim__PropertyIndex(opensimSimulationJNI.Scholz2015GeometryPathObstacle_PropertyIndex_socket_contact_geometry_get(swigCPtr, this), true);
  }

  public void connectSocket_contact_geometry(OpenSimObject object) {
    opensimSimulationJNI.Scholz2015GeometryPathObstacle_connectSocket_contact_geometry(swigCPtr, this, OpenSimObject.getCPtr(object), object);
  }

  public void copyProperty_contact_hint(Scholz2015GeometryPathObstacle source) {
    opensimSimulationJNI.Scholz2015GeometryPathObstacle_copyProperty_contact_hint(swigCPtr, this, Scholz2015GeometryPathObstacle.getCPtr(source), source);
  }

  public Vec3 get_contact_hint(int i) {
    return new Vec3(opensimSimulationJNI.Scholz2015GeometryPathObstacle_get_contact_hint__SWIG_0(swigCPtr, this, i), false);
  }

  public Vec3 upd_contact_hint(int i) {
    return new Vec3(opensimSimulationJNI.Scholz2015GeometryPathObstacle_upd_contact_hint__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_contact_hint(int i, Vec3 value) {
    opensimSimulationJNI.Scholz2015GeometryPathObstacle_set_contact_hint__SWIG_0(swigCPtr, this, i, Vec3.getCPtr(value), value);
  }

  public int append_contact_hint(Vec3 value) {
    return opensimSimulationJNI.Scholz2015GeometryPathObstacle_append_contact_hint(swigCPtr, this, Vec3.getCPtr(value), value);
  }

  public void constructProperty_contact_hint(Vec3 initValue) {
    opensimSimulationJNI.Scholz2015GeometryPathObstacle_constructProperty_contact_hint(swigCPtr, this, Vec3.getCPtr(initValue), initValue);
  }

  public Vec3 get_contact_hint() {
    return new Vec3(opensimSimulationJNI.Scholz2015GeometryPathObstacle_get_contact_hint__SWIG_1(swigCPtr, this), false);
  }

  public Vec3 upd_contact_hint() {
    return new Vec3(opensimSimulationJNI.Scholz2015GeometryPathObstacle_upd_contact_hint__SWIG_1(swigCPtr, this), false);
  }

  public void set_contact_hint(Vec3 value) {
    opensimSimulationJNI.Scholz2015GeometryPathObstacle_set_contact_hint__SWIG_1(swigCPtr, this, Vec3.getCPtr(value), value);
  }

  public Scholz2015GeometryPathObstacle() {
    this(opensimSimulationJNI.new_Scholz2015GeometryPathObstacle(), true);
  }

  public ContactGeometry getContactGeometry() {
    return new ContactGeometry(opensimSimulationJNI.Scholz2015GeometryPathObstacle_getContactGeometry(swigCPtr, this), false);
  }

  public Vec3 getContactHint() {
    return new Vec3(opensimSimulationJNI.Scholz2015GeometryPathObstacle_getContactHint(swigCPtr, this), false);
  }

}
