/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class Scholz2015GeometryPath extends AbstractGeometryPath {
  private transient long swigCPtr;

  public Scholz2015GeometryPath(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.Scholz2015GeometryPath_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(Scholz2015GeometryPath obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(Scholz2015GeometryPath obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_Scholz2015GeometryPath(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static Scholz2015GeometryPath safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.Scholz2015GeometryPath_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new Scholz2015GeometryPath(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.Scholz2015GeometryPath_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.Scholz2015GeometryPath_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.Scholz2015GeometryPath_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Scholz2015GeometryPath(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.Scholz2015GeometryPath_getConcreteClassName(swigCPtr, this);
  }

  public Scholz2015GeometryPath() {
    this(opensimSimulationJNI.new_Scholz2015GeometryPath(), true);
  }

  public void appendPathPoint(PhysicalFrame frame, Vec3 location) {
    opensimSimulationJNI.Scholz2015GeometryPath_appendPathPoint(swigCPtr, this, PhysicalFrame.getCPtr(frame), frame, Vec3.getCPtr(location), location);
  }

  public PathPoint getOrigin() {
    return new PathPoint(opensimSimulationJNI.Scholz2015GeometryPath_getOrigin(swigCPtr, this), false);
  }

  public PathPoint getInsertion() {
    return new PathPoint(opensimSimulationJNI.Scholz2015GeometryPath_getInsertion(swigCPtr, this), false);
  }

  public PathPoint getPathPoint(int pathPointIndex) {
    return new PathPoint(opensimSimulationJNI.Scholz2015GeometryPath_getPathPoint(swigCPtr, this, pathPointIndex), false);
  }

  public void appendObstacle(ContactGeometry contactGeometry, Vec3 contactHint) {
    opensimSimulationJNI.Scholz2015GeometryPath_appendObstacle(swigCPtr, this, ContactGeometry.getCPtr(contactGeometry), contactGeometry, Vec3.getCPtr(contactHint), contactHint);
  }

  public ContactGeometry getContactGeometry(int obstacleIndex) {
    return new ContactGeometry(opensimSimulationJNI.Scholz2015GeometryPath_getContactGeometry(swigCPtr, this, obstacleIndex), false);
  }

  public Vec3 getContactHint(int obstacleIndex) {
    return new Vec3(opensimSimulationJNI.Scholz2015GeometryPath_getContactHint(swigCPtr, this, obstacleIndex), false);
  }

  public int getNumPathPoints() {
    return opensimSimulationJNI.Scholz2015GeometryPath_getNumPathPoints(swigCPtr, this);
  }

  public int getNumObstacles() {
    return opensimSimulationJNI.Scholz2015GeometryPath_getNumObstacles(swigCPtr, this);
  }

  public int getNumPathElements() {
    return opensimSimulationJNI.Scholz2015GeometryPath_getNumPathElements(swigCPtr, this);
  }

  public double getLength(State s) {
    return opensimSimulationJNI.Scholz2015GeometryPath_getLength(swigCPtr, this, State.getCPtr(s), s);
  }

  public double getLengtheningSpeed(State s) {
    return opensimSimulationJNI.Scholz2015GeometryPath_getLengtheningSpeed(swigCPtr, this, State.getCPtr(s), s);
  }

  public double computeMomentArm(State s, Coordinate coord) {
    return opensimSimulationJNI.Scholz2015GeometryPath_computeMomentArm(swigCPtr, this, State.getCPtr(s), s, Coordinate.getCPtr(coord), coord);
  }

  public boolean isVisualPath() {
    return opensimSimulationJNI.Scholz2015GeometryPath_isVisualPath(swigCPtr, this);
  }

  public void produceForces(State s, double tension, SWIGTYPE_p_OpenSim__ForceConsumer consumer) {
    opensimSimulationJNI.Scholz2015GeometryPath_produceForces(swigCPtr, this, State.getCPtr(s), s, tension, SWIGTYPE_p_OpenSim__ForceConsumer.getCPtr(consumer));
  }

}
