/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class SmoothSegmentedFunction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public SmoothSegmentedFunction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(SmoothSegmentedFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(SmoothSegmentedFunction obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimCommonJNI.delete_SmoothSegmentedFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SmoothSegmentedFunction() {
    this(opensimCommonJNI.new_SmoothSegmentedFunction__SWIG_0(), true);
  }

  public SmoothSegmentedFunction(SmoothSegmentedFunction arg0) {
    this(opensimCommonJNI.new_SmoothSegmentedFunction__SWIG_1(SmoothSegmentedFunction.getCPtr(arg0), arg0), true);
  }

  public double calcValue(double x) {
    return opensimCommonJNI.SmoothSegmentedFunction_calcValue(swigCPtr, this, x);
  }

  public double calcDerivative(double x, int order) {
    return opensimCommonJNI.SmoothSegmentedFunction_calcDerivative(swigCPtr, this, x, order);
  }

  static public class ValueAndDerivative {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    public ValueAndDerivative(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    public static long getCPtr(ValueAndDerivative obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    public static long swigRelease(ValueAndDerivative obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings({"deprecation", "removal"})
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          opensimCommonJNI.delete_SmoothSegmentedFunction_ValueAndDerivative(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setValue(double value) {
      opensimCommonJNI.SmoothSegmentedFunction_ValueAndDerivative_value_set(swigCPtr, this, value);
    }
  
    public double getValue() {
      return opensimCommonJNI.SmoothSegmentedFunction_ValueAndDerivative_value_get(swigCPtr, this);
    }
  
    public void setDerivative(double value) {
      opensimCommonJNI.SmoothSegmentedFunction_ValueAndDerivative_derivative_set(swigCPtr, this, value);
    }
  
    public double getDerivative() {
      return opensimCommonJNI.SmoothSegmentedFunction_ValueAndDerivative_derivative_get(swigCPtr, this);
    }
  
    public ValueAndDerivative() {
      this(opensimCommonJNI.new_SmoothSegmentedFunction_ValueAndDerivative(), true);
    }
  
  }

  public SmoothSegmentedFunction.ValueAndDerivative calcValueAndFirstDerivative(double x) {
    return new SmoothSegmentedFunction.ValueAndDerivative(opensimCommonJNI.SmoothSegmentedFunction_calcValueAndFirstDerivative(swigCPtr, this, x), true);
  }

  public double calcIntegral(double x) {
    return opensimCommonJNI.SmoothSegmentedFunction_calcIntegral(swigCPtr, this, x);
  }

  public boolean isIntegralAvailable() {
    return opensimCommonJNI.SmoothSegmentedFunction_isIntegralAvailable(swigCPtr, this);
  }

  public boolean isIntegralComputedLeftToRight() {
    return opensimCommonJNI.SmoothSegmentedFunction_isIntegralComputedLeftToRight(swigCPtr, this);
  }

  public String getName() {
    return opensimCommonJNI.SmoothSegmentedFunction_getName(swigCPtr, this);
  }

  public void setName(SWIGTYPE_p_std__string name) {
    opensimCommonJNI.SmoothSegmentedFunction_setName(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(name));
  }

  public Vec2 getCurveDomain() {
    return new Vec2(opensimCommonJNI.SmoothSegmentedFunction_getCurveDomain(swigCPtr, this), true);
  }

  public void printMuscleCurveToCSVFile(String path, double domainMin, double domainMax) {
    opensimCommonJNI.SmoothSegmentedFunction_printMuscleCurveToCSVFile(swigCPtr, this, path, domainMin, domainMax);
  }

  public Matrix calcSampledMuscleCurve(int maxOrder, double domainMin, double domainMax) {
    return new Matrix(opensimCommonJNI.SmoothSegmentedFunction_calcSampledMuscleCurve(swigCPtr, this, maxOrder, domainMin, domainMax), true);
  }

}
