/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class StationDefinedFrame extends PhysicalFrame {
  private transient long swigCPtr;

  public StationDefinedFrame(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.StationDefinedFrame_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(StationDefinedFrame obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(StationDefinedFrame obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_StationDefinedFrame(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static StationDefinedFrame safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.StationDefinedFrame_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new StationDefinedFrame(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.StationDefinedFrame_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.StationDefinedFrame_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.StationDefinedFrame_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new StationDefinedFrame(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.StationDefinedFrame_getConcreteClassName(swigCPtr, this);
  }

  public void copyProperty_ab_axis(StationDefinedFrame source) {
    opensimSimulationJNI.StationDefinedFrame_copyProperty_ab_axis(swigCPtr, this, StationDefinedFrame.getCPtr(source), source);
  }

  public String get_ab_axis(int i) {
    return opensimSimulationJNI.StationDefinedFrame_get_ab_axis__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_ab_axis(int i) {
    return new SWIGTYPE_p_std__string(opensimSimulationJNI.StationDefinedFrame_upd_ab_axis__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_ab_axis(int i, String value) {
    opensimSimulationJNI.StationDefinedFrame_set_ab_axis__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_ab_axis(String value) {
    return opensimSimulationJNI.StationDefinedFrame_append_ab_axis(swigCPtr, this, value);
  }

  public void constructProperty_ab_axis(String initValue) {
    opensimSimulationJNI.StationDefinedFrame_constructProperty_ab_axis(swigCPtr, this, initValue);
  }

  public String get_ab_axis() {
    return opensimSimulationJNI.StationDefinedFrame_get_ab_axis__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_ab_axis() {
    return new SWIGTYPE_p_std__string(opensimSimulationJNI.StationDefinedFrame_upd_ab_axis__SWIG_1(swigCPtr, this), false);
  }

  public void set_ab_axis(String value) {
    opensimSimulationJNI.StationDefinedFrame_set_ab_axis__SWIG_1(swigCPtr, this, value);
  }

  public void copyProperty_ab_x_ac_axis(StationDefinedFrame source) {
    opensimSimulationJNI.StationDefinedFrame_copyProperty_ab_x_ac_axis(swigCPtr, this, StationDefinedFrame.getCPtr(source), source);
  }

  public String get_ab_x_ac_axis(int i) {
    return opensimSimulationJNI.StationDefinedFrame_get_ab_x_ac_axis__SWIG_0(swigCPtr, this, i);
  }

  public SWIGTYPE_p_std__string upd_ab_x_ac_axis(int i) {
    return new SWIGTYPE_p_std__string(opensimSimulationJNI.StationDefinedFrame_upd_ab_x_ac_axis__SWIG_0(swigCPtr, this, i), false);
  }

  public void set_ab_x_ac_axis(int i, String value) {
    opensimSimulationJNI.StationDefinedFrame_set_ab_x_ac_axis__SWIG_0(swigCPtr, this, i, value);
  }

  public int append_ab_x_ac_axis(String value) {
    return opensimSimulationJNI.StationDefinedFrame_append_ab_x_ac_axis(swigCPtr, this, value);
  }

  public void constructProperty_ab_x_ac_axis(String initValue) {
    opensimSimulationJNI.StationDefinedFrame_constructProperty_ab_x_ac_axis(swigCPtr, this, initValue);
  }

  public String get_ab_x_ac_axis() {
    return opensimSimulationJNI.StationDefinedFrame_get_ab_x_ac_axis__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_std__string upd_ab_x_ac_axis() {
    return new SWIGTYPE_p_std__string(opensimSimulationJNI.StationDefinedFrame_upd_ab_x_ac_axis__SWIG_1(swigCPtr, this), false);
  }

  public void set_ab_x_ac_axis(String value) {
    opensimSimulationJNI.StationDefinedFrame_set_ab_x_ac_axis__SWIG_1(swigCPtr, this, value);
  }

  public void setPropertyIndex_socket_point_a(SWIGTYPE_p_OpenSim__PropertyIndex value) {
    opensimSimulationJNI.StationDefinedFrame_PropertyIndex_socket_point_a_set(swigCPtr, this, SWIGTYPE_p_OpenSim__PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_OpenSim__PropertyIndex getPropertyIndex_socket_point_a() {
    return new SWIGTYPE_p_OpenSim__PropertyIndex(opensimSimulationJNI.StationDefinedFrame_PropertyIndex_socket_point_a_get(swigCPtr, this), true);
  }

  public void connectSocket_point_a(OpenSimObject object) {
    opensimSimulationJNI.StationDefinedFrame_connectSocket_point_a(swigCPtr, this, OpenSimObject.getCPtr(object), object);
  }

  public void setPropertyIndex_socket_point_b(SWIGTYPE_p_OpenSim__PropertyIndex value) {
    opensimSimulationJNI.StationDefinedFrame_PropertyIndex_socket_point_b_set(swigCPtr, this, SWIGTYPE_p_OpenSim__PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_OpenSim__PropertyIndex getPropertyIndex_socket_point_b() {
    return new SWIGTYPE_p_OpenSim__PropertyIndex(opensimSimulationJNI.StationDefinedFrame_PropertyIndex_socket_point_b_get(swigCPtr, this), true);
  }

  public void connectSocket_point_b(OpenSimObject object) {
    opensimSimulationJNI.StationDefinedFrame_connectSocket_point_b(swigCPtr, this, OpenSimObject.getCPtr(object), object);
  }

  public void setPropertyIndex_socket_point_c(SWIGTYPE_p_OpenSim__PropertyIndex value) {
    opensimSimulationJNI.StationDefinedFrame_PropertyIndex_socket_point_c_set(swigCPtr, this, SWIGTYPE_p_OpenSim__PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_OpenSim__PropertyIndex getPropertyIndex_socket_point_c() {
    return new SWIGTYPE_p_OpenSim__PropertyIndex(opensimSimulationJNI.StationDefinedFrame_PropertyIndex_socket_point_c_get(swigCPtr, this), true);
  }

  public void connectSocket_point_c(OpenSimObject object) {
    opensimSimulationJNI.StationDefinedFrame_connectSocket_point_c(swigCPtr, this, OpenSimObject.getCPtr(object), object);
  }

  public void setPropertyIndex_socket_origin_point(SWIGTYPE_p_OpenSim__PropertyIndex value) {
    opensimSimulationJNI.StationDefinedFrame_PropertyIndex_socket_origin_point_set(swigCPtr, this, SWIGTYPE_p_OpenSim__PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_OpenSim__PropertyIndex getPropertyIndex_socket_origin_point() {
    return new SWIGTYPE_p_OpenSim__PropertyIndex(opensimSimulationJNI.StationDefinedFrame_PropertyIndex_socket_origin_point_get(swigCPtr, this), true);
  }

  public void connectSocket_origin_point(OpenSimObject object) {
    opensimSimulationJNI.StationDefinedFrame_connectSocket_origin_point(swigCPtr, this, OpenSimObject.getCPtr(object), object);
  }

  public StationDefinedFrame() {
    this(opensimSimulationJNI.new_StationDefinedFrame__SWIG_0(), true);
  }

  public StationDefinedFrame(String name, CoordinateDirection abAxis, CoordinateDirection abXacAxis, SWIGTYPE_p_Station pointA, SWIGTYPE_p_Station pointB, SWIGTYPE_p_Station pointC, SWIGTYPE_p_Station originPoint) {
    this(opensimSimulationJNI.new_StationDefinedFrame__SWIG_1(name, CoordinateDirection.getCPtr(abAxis), abAxis, CoordinateDirection.getCPtr(abXacAxis), abXacAxis, SWIGTYPE_p_Station.getCPtr(pointA), SWIGTYPE_p_Station.getCPtr(pointB), SWIGTYPE_p_Station.getCPtr(pointC), SWIGTYPE_p_Station.getCPtr(originPoint)), true);
  }

}
