/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class StatesDocument {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public StatesDocument(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(StatesDocument obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(StatesDocument obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_StatesDocument(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StatesDocument() {
    this(opensimSimulationJNI.new_StatesDocument__SWIG_0(), true);
  }

  public StatesDocument(String filename) {
    this(opensimSimulationJNI.new_StatesDocument__SWIG_1(filename), true);
  }

  public StatesDocument(Model model, SWIGTYPE_p_SimTK__Array_T_SimTK__State_unsigned_int_t trajectory, String note, int precision) {
    this(opensimSimulationJNI.new_StatesDocument__SWIG_2(Model.getCPtr(model), model, SWIGTYPE_p_SimTK__Array_T_SimTK__State_unsigned_int_t.getCPtr(trajectory), note, precision), true);
  }

  public StatesDocument(Model model, SWIGTYPE_p_SimTK__Array_T_SimTK__State_unsigned_int_t trajectory, String note) {
    this(opensimSimulationJNI.new_StatesDocument__SWIG_3(Model.getCPtr(model), model, SWIGTYPE_p_SimTK__Array_T_SimTK__State_unsigned_int_t.getCPtr(trajectory), note), true);
  }

  public StatesDocument(Model model, SWIGTYPE_p_SimTK__Array_T_SimTK__State_unsigned_int_t trajectory) {
    this(opensimSimulationJNI.new_StatesDocument__SWIG_4(Model.getCPtr(model), model, SWIGTYPE_p_SimTK__Array_T_SimTK__State_unsigned_int_t.getCPtr(trajectory)), true);
  }

  public StatesDocument(Model model, StdVectorState trajectory, String note, int precision) {
    this(opensimSimulationJNI.new_StatesDocument__SWIG_5(Model.getCPtr(model), model, StdVectorState.getCPtr(trajectory), trajectory, note, precision), true);
  }

  public StatesDocument(Model model, StdVectorState trajectory, String note) {
    this(opensimSimulationJNI.new_StatesDocument__SWIG_6(Model.getCPtr(model), model, StdVectorState.getCPtr(trajectory), trajectory, note), true);
  }

  public StatesDocument(Model model, StdVectorState trajectory) {
    this(opensimSimulationJNI.new_StatesDocument__SWIG_7(Model.getCPtr(model), model, StdVectorState.getCPtr(trajectory), trajectory), true);
  }

  public String getNote() {
    return opensimSimulationJNI.StatesDocument_getNote(swigCPtr, this);
  }

  public int getPrecision() {
    return opensimSimulationJNI.StatesDocument_getPrecision(swigCPtr, this);
  }

  public void serialize(String filename) {
    opensimSimulationJNI.StatesDocument_serialize(swigCPtr, this, filename);
  }

  public void deserialize(Model model, SWIGTYPE_p_SimTK__Array_T_SimTK__State_unsigned_int_t trajectory) {
    opensimSimulationJNI.StatesDocument_deserialize__SWIG_0(swigCPtr, this, Model.getCPtr(model), model, SWIGTYPE_p_SimTK__Array_T_SimTK__State_unsigned_int_t.getCPtr(trajectory));
  }

  public void deserialize(Model model, StdVectorState trajectory) {
    opensimSimulationJNI.StatesDocument_deserialize__SWIG_1(swigCPtr, this, Model.getCPtr(model), model, StdVectorState.getCPtr(trajectory), trajectory);
  }

}
