/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class StringLogSink extends LogSink {
  private transient long swigCPtr;
  private transient boolean swigCMemOwnDerived;

  protected StringLogSink(long cPtr, boolean cMemoryOwn) {
    super(opensimCommonJNI.StringLogSink_SWIGSmartPtrUpcast(cPtr), true);
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringLogSink obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void swigSetCMemOwn(boolean own) {
    swigCMemOwnDerived = own;
    super.swigSetCMemOwn(own);
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwnDerived) {
        swigCMemOwnDerived = false;
        opensimCommonJNI.delete_StringLogSink(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void clear() {
    opensimCommonJNI.StringLogSink_clear(swigCPtr, this);
  }

  public String getString() {
    return opensimCommonJNI.StringLogSink_getString(swigCPtr, this);
  }

  public StringLogSink() {
    this(opensimCommonJNI.new_StringLogSink(), true);
  }

}
