/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class SynergyController extends InputController {
  private transient long swigCPtr;

  public SynergyController(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.SynergyController_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(SynergyController obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(SynergyController obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_SynergyController(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static SynergyController safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.SynergyController_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new SynergyController(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.SynergyController_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.SynergyController_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.SynergyController_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new SynergyController(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.SynergyController_getConcreteClassName(swigCPtr, this);
  }

  public void copyProperty_synergy_vectors(SynergyController source) {
    opensimSimulationJNI.SynergyController_copyProperty_synergy_vectors(swigCPtr, this, SynergyController.getCPtr(source), source);
  }

  public SynergyVector get_synergy_vectors(int i) {
    return new SynergyVector(opensimSimulationJNI.SynergyController_get_synergy_vectors(swigCPtr, this, i), false);
  }

  public SynergyVector upd_synergy_vectors(int i) {
    return new SynergyVector(opensimSimulationJNI.SynergyController_upd_synergy_vectors(swigCPtr, this, i), false);
  }

  public void set_synergy_vectors(int i, SynergyVector value) {
    opensimSimulationJNI.SynergyController_set_synergy_vectors(swigCPtr, this, i, SynergyVector.getCPtr(value), value);
  }

  public int append_synergy_vectors(SynergyVector value) {
    return opensimSimulationJNI.SynergyController_append_synergy_vectors(swigCPtr, this, SynergyVector.getCPtr(value), value);
  }

  public void constructProperty_synergy_vectors() {
    opensimSimulationJNI.SynergyController_constructProperty_synergy_vectors(swigCPtr, this);
  }

  public SynergyController() {
    this(opensimSimulationJNI.new_SynergyController__SWIG_0(), true);
  }

  public SynergyController(SynergyController other) {
    this(opensimSimulationJNI.new_SynergyController__SWIG_1(SynergyController.getCPtr(other), other), true);
  }

  public void addSynergyVector(Vector vector) {
    opensimSimulationJNI.SynergyController_addSynergyVector(swigCPtr, this, Vector.getCPtr(vector), vector);
  }

  public void updSynergyVector(int index, Vector vector) {
    opensimSimulationJNI.SynergyController_updSynergyVector(swigCPtr, this, index, Vector.getCPtr(vector), vector);
  }

  public Vector getSynergyVector(int index) {
    return new Vector(opensimSimulationJNI.SynergyController_getSynergyVector(swigCPtr, this, index), false);
  }

  public int getNumSynergies() {
    return opensimSimulationJNI.SynergyController_getNumSynergies(swigCPtr, this);
  }

  public Matrix getSynergyVectorsAsMatrix() {
    return new Matrix(opensimSimulationJNI.SynergyController_getSynergyVectorsAsMatrix(swigCPtr, this), true);
  }

  public StdVectorString getInputControlLabels() {
    return new StdVectorString(opensimSimulationJNI.SynergyController_getInputControlLabels(swigCPtr, this), true);
  }

  public void computeControlsImpl(State s, Vector controls) {
    opensimSimulationJNI.SynergyController_computeControlsImpl(swigCPtr, this, State.getCPtr(s), s, Vector.getCPtr(controls), controls);
  }

}
