/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class TabOpUseAbsoluteStateNames extends TableOperator {
  private transient long swigCPtr;

  public TabOpUseAbsoluteStateNames(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.TabOpUseAbsoluteStateNames_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(TabOpUseAbsoluteStateNames obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(TabOpUseAbsoluteStateNames obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_TabOpUseAbsoluteStateNames(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static TabOpUseAbsoluteStateNames safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.TabOpUseAbsoluteStateNames_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new TabOpUseAbsoluteStateNames(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.TabOpUseAbsoluteStateNames_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.TabOpUseAbsoluteStateNames_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.TabOpUseAbsoluteStateNames_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new TabOpUseAbsoluteStateNames(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.TabOpUseAbsoluteStateNames_getConcreteClassName(swigCPtr, this);
  }

  public TabOpUseAbsoluteStateNames() {
    this(opensimSimulationJNI.new_TabOpUseAbsoluteStateNames(), true);
  }

  public void operate(TimeSeriesTable table, Model model) {
    opensimSimulationJNI.TabOpUseAbsoluteStateNames_operate(swigCPtr, this, TimeSeriesTable.getCPtr(table), table, Model.getCPtr(model), model);
  }

}
