/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.opensim.modeling;

public class TwoFrameLinkerForceProducer extends ForceProducer {
  private transient long swigCPtr;

  public TwoFrameLinkerForceProducer(long cPtr, boolean cMemoryOwn) {
    super(opensimSimulationJNI.TwoFrameLinkerForceProducer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  public static long getCPtr(TwoFrameLinkerForceProducer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(TwoFrameLinkerForceProducer obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        opensimSimulationJNI.delete_TwoFrameLinkerForceProducer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static TwoFrameLinkerForceProducer safeDownCast(OpenSimObject obj) {
    long cPtr = opensimSimulationJNI.TwoFrameLinkerForceProducer_safeDownCast(OpenSimObject.getCPtr(obj), obj);
    return (cPtr == 0) ? null : new TwoFrameLinkerForceProducer(cPtr, false);
  }

  public void assign(OpenSimObject aObject) {
    opensimSimulationJNI.TwoFrameLinkerForceProducer_assign(swigCPtr, this, OpenSimObject.getCPtr(aObject), aObject);
  }

  public static String getClassName() {
    return opensimSimulationJNI.TwoFrameLinkerForceProducer_getClassName();
  }

  public OpenSimObject clone() {
    long cPtr = opensimSimulationJNI.TwoFrameLinkerForceProducer_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new TwoFrameLinkerForceProducer(cPtr, true);
  }

  public String getConcreteClassName() {
    return opensimSimulationJNI.TwoFrameLinkerForceProducer_getConcreteClassName(swigCPtr, this);
  }

  public void copyProperty_frames(TwoFrameLinkerForceProducer source) {
    opensimSimulationJNI.TwoFrameLinkerForceProducer_copyProperty_frames(swigCPtr, this, TwoFrameLinkerForceProducer.getCPtr(source), source);
  }

  public PhysicalFrame get_frames(int i) {
    return new PhysicalFrame(opensimSimulationJNI.TwoFrameLinkerForceProducer_get_frames(swigCPtr, this, i), false);
  }

  public PhysicalFrame upd_frames(int i) {
    return new PhysicalFrame(opensimSimulationJNI.TwoFrameLinkerForceProducer_upd_frames(swigCPtr, this, i), false);
  }

  public void set_frames(int i, PhysicalFrame value) {
    opensimSimulationJNI.TwoFrameLinkerForceProducer_set_frames(swigCPtr, this, i, PhysicalFrame.getCPtr(value), value);
  }

  public int append_frames(PhysicalFrame value) {
    return opensimSimulationJNI.TwoFrameLinkerForceProducer_append_frames(swigCPtr, this, PhysicalFrame.getCPtr(value), value);
  }

  public void constructProperty_frames() {
    opensimSimulationJNI.TwoFrameLinkerForceProducer_constructProperty_frames(swigCPtr, this);
  }

  public void setPropertyIndex_socket_frame1(SWIGTYPE_p_OpenSim__PropertyIndex value) {
    opensimSimulationJNI.TwoFrameLinkerForceProducer_PropertyIndex_socket_frame1_set(swigCPtr, this, SWIGTYPE_p_OpenSim__PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_OpenSim__PropertyIndex getPropertyIndex_socket_frame1() {
    return new SWIGTYPE_p_OpenSim__PropertyIndex(opensimSimulationJNI.TwoFrameLinkerForceProducer_PropertyIndex_socket_frame1_get(swigCPtr, this), true);
  }

  public void connectSocket_frame1(OpenSimObject object) {
    opensimSimulationJNI.TwoFrameLinkerForceProducer_connectSocket_frame1(swigCPtr, this, OpenSimObject.getCPtr(object), object);
  }

  public void setPropertyIndex_socket_frame2(SWIGTYPE_p_OpenSim__PropertyIndex value) {
    opensimSimulationJNI.TwoFrameLinkerForceProducer_PropertyIndex_socket_frame2_set(swigCPtr, this, SWIGTYPE_p_OpenSim__PropertyIndex.getCPtr(value));
  }

  public SWIGTYPE_p_OpenSim__PropertyIndex getPropertyIndex_socket_frame2() {
    return new SWIGTYPE_p_OpenSim__PropertyIndex(opensimSimulationJNI.TwoFrameLinkerForceProducer_PropertyIndex_socket_frame2_get(swigCPtr, this), true);
  }

  public void connectSocket_frame2(OpenSimObject object) {
    opensimSimulationJNI.TwoFrameLinkerForceProducer_connectSocket_frame2(swigCPtr, this, OpenSimObject.getCPtr(object), object);
  }

  public PhysicalFrame getFrame1() {
    return new PhysicalFrame(opensimSimulationJNI.TwoFrameLinkerForceProducer_getFrame1(swigCPtr, this), false);
  }

  public PhysicalFrame getFrame2() {
    return new PhysicalFrame(opensimSimulationJNI.TwoFrameLinkerForceProducer_getFrame2(swigCPtr, this), false);
  }

  public Transform computeRelativeOffset(State s) {
    return new Transform(opensimSimulationJNI.TwoFrameLinkerForceProducer_computeRelativeOffset(swigCPtr, this, State.getCPtr(s), s), true);
  }

  public SpatialVec computeRelativeVelocity(State s) {
    return new SpatialVec(opensimSimulationJNI.TwoFrameLinkerForceProducer_computeRelativeVelocity(swigCPtr, this, State.getCPtr(s), s), true);
  }

  public Vec6 computeDeflection(State s) {
    return new Vec6(opensimSimulationJNI.TwoFrameLinkerForceProducer_computeDeflection(swigCPtr, this, State.getCPtr(s), s), true);
  }

  public Vec6 computeDeflectionRate(State s) {
    return new Vec6(opensimSimulationJNI.TwoFrameLinkerForceProducer_computeDeflectionRate(swigCPtr, this, State.getCPtr(s), s), true);
  }

}
